/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { R9SError } from "./r9serror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type SchemasBadRequestErrorError = {
  /**
   * Error message
   */
  message: string;
  /**
   * Error type
   */
  type: string;
  /**
   * Error code
   */
  code?: string | null | undefined;
  /**
   * Related parameter
   */
  param?: string | undefined;
};

export const SchemasBadRequestErrorStatus = {
  FourHundred: "400",
} as const;
export type SchemasBadRequestErrorStatus = ClosedEnum<
  typeof SchemasBadRequestErrorStatus
>;

export type BadRequestErrorData = {
  error: SchemasBadRequestErrorError;
  status?: SchemasBadRequestErrorStatus | undefined;
};

export class BadRequestError extends R9SError {
  error: SchemasBadRequestErrorError;
  status?: SchemasBadRequestErrorStatus | undefined;

  /** The original data that was passed to this error instance. */
  data$: BadRequestErrorData;

  constructor(
    err: BadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;
    if (err.status != null) this.status = err.status;

    this.name = "BadRequestError";
  }
}

/** @internal */
export const SchemasBadRequestErrorError$inboundSchema: z.ZodMiniType<
  SchemasBadRequestErrorError,
  unknown
> = z.object({
  message: types.string(),
  type: types.string(),
  code: z.optional(z.nullable(types.string())),
  param: types.optional(types.string()),
});

export function schemasBadRequestErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<SchemasBadRequestErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SchemasBadRequestErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SchemasBadRequestErrorError' from JSON`,
  );
}

/** @internal */
export const SchemasBadRequestErrorStatus$inboundSchema: z.ZodMiniEnum<
  typeof SchemasBadRequestErrorStatus
> = z.enum(SchemasBadRequestErrorStatus);

/** @internal */
export const BadRequestError$inboundSchema: z.ZodMiniType<
  BadRequestError,
  unknown
> = z.pipe(
  z.object({
    error: z.lazy(() => SchemasBadRequestErrorError$inboundSchema),
    status: types.optional(SchemasBadRequestErrorStatus$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new BadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
