/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { R9SError } from "./r9serror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type SchemasNotFoundErrorError = {
  /**
   * Error message
   */
  message: string;
  /**
   * Error type
   */
  type: string;
  /**
   * Error code
   */
  code?: string | null | undefined;
  /**
   * Related parameter
   */
  param?: string | undefined;
};

export const SchemasNotFoundErrorStatus = {
  FourHundredAndFour: "404",
} as const;
export type SchemasNotFoundErrorStatus = ClosedEnum<
  typeof SchemasNotFoundErrorStatus
>;

export type NotFoundErrorData = {
  error: SchemasNotFoundErrorError;
  status?: SchemasNotFoundErrorStatus | undefined;
};

export class NotFoundError extends R9SError {
  error: SchemasNotFoundErrorError;
  status?: SchemasNotFoundErrorStatus | undefined;

  /** The original data that was passed to this error instance. */
  data$: NotFoundErrorData;

  constructor(
    err: NotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;
    if (err.status != null) this.status = err.status;

    this.name = "NotFoundError";
  }
}

/** @internal */
export const SchemasNotFoundErrorError$inboundSchema: z.ZodMiniType<
  SchemasNotFoundErrorError,
  unknown
> = z.object({
  message: types.string(),
  type: types.string(),
  code: z.optional(z.nullable(types.string())),
  param: types.optional(types.string()),
});

export function schemasNotFoundErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<SchemasNotFoundErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SchemasNotFoundErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SchemasNotFoundErrorError' from JSON`,
  );
}

/** @internal */
export const SchemasNotFoundErrorStatus$inboundSchema: z.ZodMiniEnum<
  typeof SchemasNotFoundErrorStatus
> = z.enum(SchemasNotFoundErrorStatus);

/** @internal */
export const NotFoundError$inboundSchema: z.ZodMiniType<
  NotFoundError,
  unknown
> = z.pipe(
  z.object({
    error: z.lazy(() => SchemasNotFoundErrorError$inboundSchema),
    status: types.optional(SchemasNotFoundErrorStatus$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new NotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
