/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { R9SError } from "./r9serror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type SchemasError = {
  /**
   * Error message
   */
  message: string;
  /**
   * Error type
   */
  type: string;
  /**
   * Error code
   */
  code?: string | null | undefined;
  /**
   * Related parameter
   */
  param?: string | undefined;
};

export const SchemasStatus = {
  FourHundredAndThree: "403",
} as const;
export type SchemasStatus = ClosedEnum<typeof SchemasStatus>;

export type PermissionDeniedErrorData = {
  error: SchemasError;
  status?: SchemasStatus | undefined;
};

export class PermissionDeniedError extends R9SError {
  error: SchemasError;
  status?: SchemasStatus | undefined;

  /** The original data that was passed to this error instance. */
  data$: PermissionDeniedErrorData;

  constructor(
    err: PermissionDeniedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;
    if (err.status != null) this.status = err.status;

    this.name = "PermissionDeniedError";
  }
}

/** @internal */
export const SchemasError$inboundSchema: z.ZodMiniType<SchemasError, unknown> =
  z.object({
    message: types.string(),
    type: types.string(),
    code: z.optional(z.nullable(types.string())),
    param: types.optional(types.string()),
  });

export function schemasErrorFromJSON(
  jsonString: string,
): SafeParseResult<SchemasError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SchemasError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SchemasError' from JSON`,
  );
}

/** @internal */
export const SchemasStatus$inboundSchema: z.ZodMiniEnum<typeof SchemasStatus> =
  z.enum(SchemasStatus);

/** @internal */
export const PermissionDeniedError$inboundSchema: z.ZodMiniType<
  PermissionDeniedError,
  unknown
> = z.pipe(
  z.object({
    error: z.lazy(() => SchemasError$inboundSchema),
    status: types.optional(SchemasStatus$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new PermissionDeniedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
