/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { R9SError } from "./r9serror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type SchemasRateLimitErrorError = {
  /**
   * Error message
   */
  message: string;
  /**
   * Error type
   */
  type: string;
  /**
   * Error code
   */
  code?: string | null | undefined;
  /**
   * Related parameter
   */
  param?: string | undefined;
};

export const SchemasRateLimitErrorStatus = {
  FourHundredAndTwentyNine: "429",
} as const;
export type SchemasRateLimitErrorStatus = ClosedEnum<
  typeof SchemasRateLimitErrorStatus
>;

export type RateLimitErrorData = {
  error: SchemasRateLimitErrorError;
  status?: SchemasRateLimitErrorStatus | undefined;
};

export class RateLimitError extends R9SError {
  error: SchemasRateLimitErrorError;
  status?: SchemasRateLimitErrorStatus | undefined;

  /** The original data that was passed to this error instance. */
  data$: RateLimitErrorData;

  constructor(
    err: RateLimitErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;
    if (err.status != null) this.status = err.status;

    this.name = "RateLimitError";
  }
}

/** @internal */
export const SchemasRateLimitErrorError$inboundSchema: z.ZodMiniType<
  SchemasRateLimitErrorError,
  unknown
> = z.object({
  message: types.string(),
  type: types.string(),
  code: z.optional(z.nullable(types.string())),
  param: types.optional(types.string()),
});

export function schemasRateLimitErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<SchemasRateLimitErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SchemasRateLimitErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SchemasRateLimitErrorError' from JSON`,
  );
}

/** @internal */
export const SchemasRateLimitErrorStatus$inboundSchema: z.ZodMiniEnum<
  typeof SchemasRateLimitErrorStatus
> = z.enum(SchemasRateLimitErrorStatus);

/** @internal */
export const RateLimitError$inboundSchema: z.ZodMiniType<
  RateLimitError,
  unknown
> = z.pipe(
  z.object({
    error: z.lazy(() => SchemasRateLimitErrorError$inboundSchema),
    status: types.optional(SchemasRateLimitErrorStatus$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new RateLimitError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
