/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { R9SError } from "./r9serror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type SchemasServiceUnavailableErrorError = {
  /**
   * Error message
   */
  message: string;
  /**
   * Error type
   */
  type: string;
  /**
   * Error code
   */
  code?: string | null | undefined;
  /**
   * Related parameter
   */
  param?: string | undefined;
};

export const SchemasServiceUnavailableErrorStatus = {
  FiveHundredAndTwo: "502",
  FiveHundredAndThree: "503",
} as const;
export type SchemasServiceUnavailableErrorStatus = OpenEnum<
  typeof SchemasServiceUnavailableErrorStatus
>;

export type ServiceUnavailableErrorData = {
  error: SchemasServiceUnavailableErrorError;
  status?: SchemasServiceUnavailableErrorStatus | undefined;
};

export class ServiceUnavailableError extends R9SError {
  error: SchemasServiceUnavailableErrorError;
  status?: SchemasServiceUnavailableErrorStatus | undefined;

  /** The original data that was passed to this error instance. */
  data$: ServiceUnavailableErrorData;

  constructor(
    err: ServiceUnavailableErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;
    if (err.status != null) this.status = err.status;

    this.name = "ServiceUnavailableError";
  }
}

/** @internal */
export const SchemasServiceUnavailableErrorError$inboundSchema: z.ZodMiniType<
  SchemasServiceUnavailableErrorError,
  unknown
> = z.object({
  message: types.string(),
  type: types.string(),
  code: z.optional(z.nullable(types.string())),
  param: types.optional(types.string()),
});

export function schemasServiceUnavailableErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<SchemasServiceUnavailableErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SchemasServiceUnavailableErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SchemasServiceUnavailableErrorError' from JSON`,
  );
}

/** @internal */
export const SchemasServiceUnavailableErrorStatus$inboundSchema: z.ZodMiniType<
  SchemasServiceUnavailableErrorStatus,
  unknown
> = openEnums.inboundSchema(SchemasServiceUnavailableErrorStatus);

/** @internal */
export const ServiceUnavailableError$inboundSchema: z.ZodMiniType<
  ServiceUnavailableError,
  unknown
> = z.pipe(
  z.object({
    error: z.lazy(() => SchemasServiceUnavailableErrorError$inboundSchema),
    status: types.optional(SchemasServiceUnavailableErrorStatus$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ServiceUnavailableError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
