/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { R9SError } from "./r9serror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type SchemasUnprocessableEntityErrorError = {
  /**
   * Error message
   */
  message: string;
  /**
   * Error type
   */
  type: string;
  /**
   * Error code
   */
  code?: string | null | undefined;
  /**
   * Related parameter
   */
  param?: string | undefined;
};

export const SchemasUnprocessableEntityErrorStatus = {
  FourHundredAndTwentyTwo: "422",
} as const;
export type SchemasUnprocessableEntityErrorStatus = ClosedEnum<
  typeof SchemasUnprocessableEntityErrorStatus
>;

export type UnprocessableEntityErrorData = {
  error: SchemasUnprocessableEntityErrorError;
  status?: SchemasUnprocessableEntityErrorStatus | undefined;
};

export class UnprocessableEntityError extends R9SError {
  error: SchemasUnprocessableEntityErrorError;
  status?: SchemasUnprocessableEntityErrorStatus | undefined;

  /** The original data that was passed to this error instance. */
  data$: UnprocessableEntityErrorData;

  constructor(
    err: UnprocessableEntityErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;
    if (err.status != null) this.status = err.status;

    this.name = "UnprocessableEntityError";
  }
}

/** @internal */
export const SchemasUnprocessableEntityErrorError$inboundSchema: z.ZodMiniType<
  SchemasUnprocessableEntityErrorError,
  unknown
> = z.object({
  message: types.string(),
  type: types.string(),
  code: z.optional(z.nullable(types.string())),
  param: types.optional(types.string()),
});

export function schemasUnprocessableEntityErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<SchemasUnprocessableEntityErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SchemasUnprocessableEntityErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SchemasUnprocessableEntityErrorError' from JSON`,
  );
}

/** @internal */
export const SchemasUnprocessableEntityErrorStatus$inboundSchema: z.ZodMiniEnum<
  typeof SchemasUnprocessableEntityErrorStatus
> = z.enum(SchemasUnprocessableEntityErrorStatus);

/** @internal */
export const UnprocessableEntityError$inboundSchema: z.ZodMiniType<
  UnprocessableEntityError,
  unknown
> = z.pipe(
  z.object({
    error: z.lazy(() => SchemasUnprocessableEntityErrorError$inboundSchema),
    status: types.optional(SchemasUnprocessableEntityErrorStatus$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new UnprocessableEntityError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
