/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { R9SCore } from "../core.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../errors/httpclienterrors.js";
import * as errors from "../errors/index.js";
import { R9SError } from "../errors/r9serror.js";
import { ResponseValidationError } from "../errors/responsevalidationerror.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { encodeFormQuery, encodeJSON, encodeSimple } from "../lib/encodings.js";
import { EventStream } from "../lib/event-streams.js";
import { matchStatusCode } from "../lib/http.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import * as models from "../models/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Generate content (streaming)
 *
 * @remarks
 * Generates a streamed response from the model given an input GenerateContentRequest.
 * The response is returned as Server-Sent Events (SSE) for real-time streaming.
 *
 * Authentication uses Bearer token in Authorization header (compatible with your platform's OpenAI-style auth).
 */
export function geminiStreamGenerateContent(
  client: R9SCore,
  model: string,
  geminiGenerateContentRequest: models.GeminiGenerateContentRequest,
  alt?: models.Alt | undefined,
  options?: RequestOptions,
): APIPromise<
  Result<
    EventStream<models.GeminiGenerateContentResponse>,
    | errors.BadRequestError
    | errors.AuthenticationError
    | errors.RateLimitError
    | errors.InternalServerError
    | R9SError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    model,
    geminiGenerateContentRequest,
    alt,
    options,
  ));
}

async function $do(
  client: R9SCore,
  model: string,
  geminiGenerateContentRequest: models.GeminiGenerateContentRequest,
  alt?: models.Alt | undefined,
  options?: RequestOptions,
): Promise<
  [
    Result<
      EventStream<models.GeminiGenerateContentResponse>,
      | errors.BadRequestError
      | errors.AuthenticationError
      | errors.RateLimitError
      | errors.InternalServerError
      | R9SError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const input: models.StreamGenerateContentRequest = {
    model: model,
    geminiGenerateContentRequest: geminiGenerateContentRequest,
    alt: alt,
  };

  const parsed = safeParse(
    input,
    (value) =>
      z.parse(models.StreamGenerateContentRequest$outboundSchema, value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = encodeJSON("body", payload.GeminiGenerateContentRequest, {
    explode: true,
  });

  const pathParams = {
    model: encodeSimple("model", payload.model, {
      explode: false,
      charEncoding: "percent",
    }),
  };
  const path = pathToFunc("/v1beta/models/{model}:streamGenerateContent")(
    pathParams,
  );

  const query = encodeFormQuery({
    "alt": payload.alt,
  });

  const headers = new Headers(compactMap({
    "Content-Type": "application/json",
    Accept: "text/event-stream",
  }));

  const secConfig = await extractSecurity(client._options.apiKey);
  const securityInput = secConfig == null ? {} : { apiKey: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "streamGenerateContent",
    oAuth2Scopes: null,

    resolvedSecurity: requestSecurity,

    securitySource: client._options.apiKey,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "POST",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    query: query,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    isErrorStatusCode: (statusCode: number) =>
      matchStatusCode({ status: statusCode } as Response, ["4XX", "5XX"]),
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    EventStream<models.GeminiGenerateContentResponse>,
    | errors.BadRequestError
    | errors.AuthenticationError
    | errors.RateLimitError
    | errors.InternalServerError
    | R9SError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.sse(
      200,
      z.pipe(
        z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
        z.transform(stream => {
          return new EventStream(stream, rawEvent => {
            if (rawEvent.data === "[DONE]") {
              return { done: true, value: undefined };
            }
            return {
              done: false,
              value: z.parse(
                models.StreamGenerateContentResponseBody$inboundSchema,
                rawEvent,
              )?.data,
            };
          });
        }),
      ),
    ),
    M.jsonErr(400, errors.BadRequestError$inboundSchema),
    M.jsonErr(401, errors.AuthenticationError$inboundSchema),
    M.jsonErr(429, errors.RateLimitError$inboundSchema),
    M.jsonErr(500, errors.InternalServerError$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
