/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { R9SCore } from "../core.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../errors/httpclienterrors.js";
import * as errors from "../errors/index.js";
import { R9SError } from "../errors/r9serror.js";
import { ResponseValidationError } from "../errors/responsevalidationerror.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { appendForm, normalizeBlob } from "../lib/encodings.js";
import { EventStream } from "../lib/event-streams.js";
import {
  bytesToBlob,
  getContentTypeFromFileName,
  readableStreamToArrayBuffer,
} from "../lib/files.js";
import { matchStatusCode } from "../lib/http.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import * as models from "../models/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { isBlobLike } from "../types/blobs.js";
import { Result } from "../types/fp.js";
import { isReadableStream } from "../types/streams.js";

/**
 * Edit image
 *
 * @remarks
 * Create an edited or extended image given an original and prompt
 */
export function imagesCreateEdit(
  client: R9SCore,
  request: models.ImageEditRequest & { stream?: false },
  options?: RequestOptions,
): APIPromise<
  Result<
    models.ImageGenerationResponse,
    | errors.BadRequestError
    | errors.AuthenticationError
    | errors.PermissionDeniedError
    | errors.UnprocessableEntityError
    | errors.RateLimitError
    | errors.InternalServerError
    | errors.ServiceUnavailableError
    | R9SError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
>;
export function imagesCreateEdit(
  client: R9SCore,
  request: models.ImageEditRequest & { stream: true },
  options?: RequestOptions,
): APIPromise<
  Result<
    EventStream<models.ImageEditStreamEvent>,
    | errors.BadRequestError
    | errors.AuthenticationError
    | errors.PermissionDeniedError
    | errors.UnprocessableEntityError
    | errors.RateLimitError
    | errors.InternalServerError
    | errors.ServiceUnavailableError
    | R9SError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
>;
export function imagesCreateEdit(
  client: R9SCore,
  request: models.ImageEditRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    models.CreateImageEditResponse,
    | errors.BadRequestError
    | errors.AuthenticationError
    | errors.PermissionDeniedError
    | errors.UnprocessableEntityError
    | errors.RateLimitError
    | errors.InternalServerError
    | errors.ServiceUnavailableError
    | R9SError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
>;
export function imagesCreateEdit(
  client: R9SCore,
  request: models.ImageEditRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    models.CreateImageEditResponse,
    | errors.BadRequestError
    | errors.AuthenticationError
    | errors.PermissionDeniedError
    | errors.UnprocessableEntityError
    | errors.RateLimitError
    | errors.InternalServerError
    | errors.ServiceUnavailableError
    | R9SError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    request,
    options,
  ));
}

async function $do(
  client: R9SCore,
  request: models.ImageEditRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      models.CreateImageEditResponse,
      | errors.BadRequestError
      | errors.AuthenticationError
      | errors.PermissionDeniedError
      | errors.UnprocessableEntityError
      | errors.RateLimitError
      | errors.InternalServerError
      | errors.ServiceUnavailableError
      | R9SError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const parsed = safeParse(
    request,
    (value) => z.parse(models.ImageEditRequest$outboundSchema, value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = new FormData();

  appendForm(body, "image", payload.image);
  appendForm(body, "prompt", payload.prompt);
  if (payload.background !== undefined) {
    appendForm(body, "background", payload.background);
  }
  if (payload.input_fidelity !== undefined) {
    appendForm(body, "input_fidelity", payload.input_fidelity);
  }
  if (payload.mask !== undefined) {
    if (isBlobLike(payload.mask)) {
      const file = payload.mask;
      const blob = await normalizeBlob(file);
      const name = "name" in file ? (file.name as string) : undefined;
      appendForm(body, "mask", blob, name);
    } else if (isReadableStream(payload.mask.content)) {
      const buffer = await readableStreamToArrayBuffer(payload.mask.content);
      const contentType = getContentTypeFromFileName(payload.mask.fileName)
        || "application/octet-stream";
      appendForm(
        body,
        "mask",
        bytesToBlob(buffer, contentType),
        payload.mask.fileName,
      );
    } else {
      const contentType = getContentTypeFromFileName(payload.mask.fileName)
        || "application/octet-stream";
      appendForm(
        body,
        "mask",
        bytesToBlob(payload.mask.content, contentType),
        payload.mask.fileName,
      );
    }
  }
  if (payload.model !== undefined) {
    appendForm(body, "model", payload.model);
  }
  if (payload.moderation !== undefined) {
    appendForm(body, "moderation", payload.moderation);
  }
  if (payload.n !== undefined) {
    appendForm(body, "n", payload.n);
  }
  if (payload.output_compression !== undefined) {
    appendForm(body, "output_compression", payload.output_compression);
  }
  if (payload.output_format !== undefined) {
    appendForm(body, "output_format", payload.output_format);
  }
  if (payload.partial_images !== undefined) {
    appendForm(body, "partial_images", payload.partial_images);
  }
  if (payload.quality !== undefined) {
    appendForm(body, "quality", payload.quality);
  }
  if (payload.response_format !== undefined) {
    appendForm(body, "response_format", payload.response_format);
  }
  if (payload.size !== undefined) {
    appendForm(body, "size", payload.size);
  }
  if (payload.stream !== undefined) {
    appendForm(body, "stream", payload.stream);
  }
  if (payload.style !== undefined) {
    appendForm(body, "style", payload.style);
  }
  if (payload.user !== undefined) {
    appendForm(body, "user", payload.user);
  }

  const path = pathToFunc("/v1/images/edits")();

  const headers = new Headers(compactMap({
    Accept: request?.stream ? "text/event-stream" : "application/json",
  }));

  const secConfig = await extractSecurity(client._options.apiKey);
  const securityInput = secConfig == null ? {} : { apiKey: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "createImageEdit",
    oAuth2Scopes: null,

    resolvedSecurity: requestSecurity,

    securitySource: client._options.apiKey,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "POST",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    isErrorStatusCode: (statusCode: number) =>
      matchStatusCode({ status: statusCode } as Response, ["4XX", "5XX"]),
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    models.CreateImageEditResponse,
    | errors.BadRequestError
    | errors.AuthenticationError
    | errors.PermissionDeniedError
    | errors.UnprocessableEntityError
    | errors.RateLimitError
    | errors.InternalServerError
    | errors.ServiceUnavailableError
    | R9SError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(200, models.CreateImageEditResponse$inboundSchema),
    M.sse(200, models.CreateImageEditResponse$inboundSchema),
    M.jsonErr(400, errors.BadRequestError$inboundSchema),
    M.jsonErr(401, errors.AuthenticationError$inboundSchema),
    M.jsonErr(403, errors.PermissionDeniedError$inboundSchema),
    M.jsonErr(422, errors.UnprocessableEntityError$inboundSchema),
    M.jsonErr(429, errors.RateLimitError$inboundSchema),
    M.jsonErr(500, errors.InternalServerError$inboundSchema),
    M.jsonErr(503, errors.ServiceUnavailableError$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
