/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { R9SCore } from "../core.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../errors/httpclienterrors.js";
import * as errors from "../errors/index.js";
import { R9SError } from "../errors/r9serror.js";
import { ResponseValidationError } from "../errors/responsevalidationerror.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { encodeJSON, encodeSimple } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import * as models from "../models/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Proxy request
 *
 * @remarks
 * Proxy requests to target endpoint through specified channel
 */
export function proxyRequest(
  client: R9SCore,
  channelid: string,
  target: string,
  requestBody?: { [k: string]: any } | undefined,
  options?: RequestOptions,
): APIPromise<
  Result<
    { [k: string]: any },
    | errors.BadRequestError
    | errors.AuthenticationError
    | errors.PermissionDeniedError
    | errors.NotFoundError
    | errors.UnprocessableEntityError
    | errors.RateLimitError
    | errors.InternalServerError
    | errors.ServiceUnavailableError
    | R9SError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    channelid,
    target,
    requestBody,
    options,
  ));
}

async function $do(
  client: R9SCore,
  channelid: string,
  target: string,
  requestBody?: { [k: string]: any } | undefined,
  options?: RequestOptions,
): Promise<
  [
    Result<
      { [k: string]: any },
      | errors.BadRequestError
      | errors.AuthenticationError
      | errors.PermissionDeniedError
      | errors.NotFoundError
      | errors.UnprocessableEntityError
      | errors.RateLimitError
      | errors.InternalServerError
      | errors.ServiceUnavailableError
      | R9SError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const input: models.CreateProxyRequestRequest = {
    channelid: channelid,
    target: target,
    requestBody: requestBody,
  };

  const parsed = safeParse(
    input,
    (value) => z.parse(models.CreateProxyRequestRequest$outboundSchema, value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = encodeJSON("body", payload.RequestBody, { explode: true });

  const pathParams = {
    channelid: encodeSimple("channelid", payload.channelid, {
      explode: false,
      charEncoding: "percent",
    }),
    target: encodeSimple("target", payload.target, {
      explode: false,
      charEncoding: "percent",
    }),
  };

  const path = pathToFunc("/nextrouter/proxy/{channelid}/{target}")(pathParams);

  const headers = new Headers(compactMap({
    "Content-Type": "application/json",
    Accept: "application/json",
  }));

  const secConfig = await extractSecurity(client._options.apiKey);
  const securityInput = secConfig == null ? {} : { apiKey: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "createProxyRequest",
    oAuth2Scopes: null,

    resolvedSecurity: requestSecurity,

    securitySource: client._options.apiKey,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "POST",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    errorCodes: [
      "400",
      "401",
      "403",
      "404",
      "422",
      "429",
      "4XX",
      "500",
      "503",
      "5XX",
    ],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    { [k: string]: any },
    | errors.BadRequestError
    | errors.AuthenticationError
    | errors.PermissionDeniedError
    | errors.NotFoundError
    | errors.UnprocessableEntityError
    | errors.RateLimitError
    | errors.InternalServerError
    | errors.ServiceUnavailableError
    | R9SError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(200, z.record(z.string(), z.any())),
    M.jsonErr(400, errors.BadRequestError$inboundSchema),
    M.jsonErr(401, errors.AuthenticationError$inboundSchema),
    M.jsonErr(403, errors.PermissionDeniedError$inboundSchema),
    M.jsonErr(404, errors.NotFoundError$inboundSchema),
    M.jsonErr(422, errors.UnprocessableEntityError$inboundSchema),
    M.jsonErr(429, errors.RateLimitError$inboundSchema),
    M.jsonErr(500, errors.InternalServerError$inboundSchema),
    M.jsonErr(503, errors.ServiceUnavailableError$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
