/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { audioSpeech } from "../funcs/audioSpeech.js";
import { audioTranscribe } from "../funcs/audioTranscribe.js";
import { audioTranslate } from "../funcs/audioTranslate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class AudioSDK extends ClientSDK {
  /**
   * Text to speech
   *
   * @remarks
   * Convert text to speech
   */
  async speech(
    request: models.AudioSpeechRequest,
    options?: RequestOptions,
  ): Promise<models.CreateAudioSpeechResponse> {
    return unwrapAsync(audioSpeech(
      this,
      request,
      options,
    ));
  }

  /**
   * Speech to text
   *
   * @remarks
   * Transcribe speech to text. Supports multiple models and output formats.
   *
   * **Supported models:**
   * - whisper-1: Supports json, text, srt, verbose_json, vtt formats
   * - gpt-4o-transcribe, gpt-4o-mini-transcribe: Only support json and text formats
   *
   * **Note:** timestamp_granularities parameter only works when response_format is set to verbose_json
   */
  async transcribe(
    request: models.AudioTranscriptionRequest,
    options?: RequestOptions,
  ): Promise<models.CreateAudioTranscriptionResponse> {
    return unwrapAsync(audioTranscribe(
      this,
      request,
      options,
    ));
  }

  /**
   * Speech translation
   *
   * @remarks
   * Translate speech from any supported language to English text.
   *
   * **Important:** This endpoint only translates audio into English. The source language is automatically detected by the model.
   *
   * **Supported models:** whisper-1 (primary), gpt-4o-transcribe (extended support)
   */
  async translate(
    request: models.AudioTranslationRequest,
    options?: RequestOptions,
  ): Promise<models.CreateAudioTranslationResponse> {
    return unwrapAsync(audioTranslate(
      this,
      request,
      options,
    ));
  }
}
