/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { chatCreate } from "../funcs/chatCreate.js";
import { EventStream } from "../lib/event-streams.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Chat extends ClientSDK {
  /**
   * Create chat completion
   *
   * @remarks
   * Create a chat completion, supports streaming
   */
  async create(
    request: models.ChatCompletionRequest & { stream?: false | undefined },
    options?: RequestOptions,
  ): Promise<models.ChatCompletionResponse>;
  async create(
    request: models.ChatCompletionRequest & { stream: true },
    options?: RequestOptions,
  ): Promise<EventStream<models.ChatCompletionStreamEvent>>;
  async create(
    request: models.ChatCompletionRequest,
    options?: RequestOptions,
  ): Promise<models.CreateChatCompletionResponse>;
  async create(
    request: models.ChatCompletionRequest,
    options?: RequestOptions,
  ): Promise<models.CreateChatCompletionResponse> {
    return unwrapAsync(chatCreate(
      this,
      request,
      options,
    ));
  }
}
