/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { completionsCreate } from "../funcs/completionsCreate.js";
import { EventStream } from "../lib/event-streams.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Completions extends ClientSDK {
  /**
   * Create text completion
   *
   * @remarks
   * Create a text completion, supports streaming
   */
  async create(
    request: models.CompletionRequest & { stream?: false | undefined },
    options?: RequestOptions,
  ): Promise<models.CompletionResponse>;
  async create(
    request: models.CompletionRequest & { stream: true },
    options?: RequestOptions,
  ): Promise<EventStream<models.CompletionStreamEvent>>;
  async create(
    request: models.CompletionRequest,
    options?: RequestOptions,
  ): Promise<models.CreateCompletionResponse>;
  async create(
    request: models.CompletionRequest,
    options?: RequestOptions,
  ): Promise<models.CreateCompletionResponse> {
    return unwrapAsync(completionsCreate(
      this,
      request,
      options,
    ));
  }
}
