/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { editsCreate } from "../funcs/editsCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Edits extends ClientSDK {
  /**
   * Create text edit
   *
   * @remarks
   * Edit given text according to instructions
   */
  async create(
    request: models.EditRequest,
    options?: RequestOptions,
  ): Promise<models.EditResponse> {
    return unwrapAsync(editsCreate(
      this,
      request,
      options,
    ));
  }
}
