/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { embeddingsCreate } from "../funcs/embeddingsCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Embeddings extends ClientSDK {
  /**
   * Create embeddings
   *
   * @remarks
   * Create embedding vector representations for input text
   */
  async create(
    request: models.EmbeddingRequest,
    options?: RequestOptions,
  ): Promise<models.EmbeddingResponse> {
    return unwrapAsync(embeddingsCreate(
      this,
      request,
      options,
    ));
  }
}
