/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { engineEmbeddingsCreate } from "../funcs/engineEmbeddingsCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class EngineEmbeddings extends ClientSDK {
  /**
   * Create engine embeddings
   *
   * @remarks
   * Create embedding vectors for input text using specified engine
   */
  async create(
    model: string,
    engineEmbeddingRequest: models.EngineEmbeddingRequest,
    options?: RequestOptions,
  ): Promise<models.EmbeddingResponse> {
    return unwrapAsync(engineEmbeddingsCreate(
      this,
      model,
      engineEmbeddingRequest,
      options,
    ));
  }
}
