/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { geminiBatchGenerateContent } from "../funcs/geminiBatchGenerateContent.js";
import { geminiEmbedContent } from "../funcs/geminiEmbedContent.js";
import { geminiGenerateContent } from "../funcs/geminiGenerateContent.js";
import { geminiStreamGenerateContent } from "../funcs/geminiStreamGenerateContent.js";
import { EventStream } from "../lib/event-streams.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Gemini extends ClientSDK {
  /**
   * Generate content (non-streaming)
   *
   * @remarks
   * Generates a model response given an input GenerateContentRequest.
   * This endpoint supports multimodal inputs (text, images, audio, video, PDFs) and conversation history.
   *
   * Authentication uses Bearer token in Authorization header (compatible with your platform's OpenAI-style auth).
   */
  async generateContent(
    model: string,
    geminiGenerateContentRequest: models.GeminiGenerateContentRequest,
    options?: RequestOptions,
  ): Promise<models.GeminiGenerateContentResponse> {
    return unwrapAsync(geminiGenerateContent(
      this,
      model,
      geminiGenerateContentRequest,
      options,
    ));
  }

  /**
   * Generate content (streaming)
   *
   * @remarks
   * Generates a streamed response from the model given an input GenerateContentRequest.
   * The response is returned as Server-Sent Events (SSE) for real-time streaming.
   *
   * Authentication uses Bearer token in Authorization header (compatible with your platform's OpenAI-style auth).
   */
  async streamGenerateContent(
    model: string,
    geminiGenerateContentRequest: models.GeminiGenerateContentRequest,
    alt?: models.Alt | undefined,
    options?: RequestOptions,
  ): Promise<EventStream<models.GeminiGenerateContentResponse>> {
    return unwrapAsync(geminiStreamGenerateContent(
      this,
      model,
      geminiGenerateContentRequest,
      alt,
      options,
    ));
  }

  /**
   * Generate embeddings
   *
   * @remarks
   * Generates a text embedding vector from the input content using the specified embedding model.
   * Supports different task types for optimized embeddings (retrieval, similarity, classification, etc.).
   *
   * Authentication uses Bearer token in Authorization header (compatible with your platform's OpenAI-style auth).
   */
  async embedContent(
    model: string,
    geminiEmbedContentRequest: models.GeminiEmbedContentRequest,
    options?: RequestOptions,
  ): Promise<models.GeminiEmbedContentResponse> {
    return unwrapAsync(geminiEmbedContent(
      this,
      model,
      geminiEmbedContentRequest,
      options,
    ));
  }

  /**
   * Create async batch generation job
   *
   * @remarks
   * Creates an asynchronous batch job to process multiple generateContent requests.
   * Returns a job object immediately. Results are available within 24 hours at 50% lower cost.
   * Use GET /v1beta/batches/{name} to poll job status and retrieve results.
   */
  async batchGenerateContent(
    model: string,
    geminiBatchGenerateContentRequest: models.GeminiBatchGenerateContentRequest,
    options?: RequestOptions,
  ): Promise<models.GeminiBatchGenerateContentResponse> {
    return unwrapAsync(geminiBatchGenerateContent(
      this,
      model,
      geminiBatchGenerateContentRequest,
      options,
    ));
  }
}
