/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { imagesCreate } from "../funcs/imagesCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Images extends ClientSDK {
  /**
   * Create image
   *
   * @remarks
   * Generate images from text prompts
   */
  async create(
    request: models.ImageGenerationRequest,
    options?: RequestOptions,
  ): Promise<models.ImageGenerationResponse> {
    return unwrapAsync(imagesCreate(
      this,
      request,
      options,
    ));
  }
}
