/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { messagesCreate } from "../funcs/messagesCreate.js";
import { EventStream } from "../lib/event-streams.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Messages extends ClientSDK {
  /**
   * Create message (Claude native API)
   *
   * @remarks
   * Create a message using Anthropic Claude's native API format, supports streaming
   */
  async create(
    request: models.AnthropicMessageRequest & { stream?: false | undefined },
    options?: RequestOptions,
  ): Promise<models.AnthropicMessageResponse>;
  async create(
    request: models.AnthropicMessageRequest & { stream: true },
    options?: RequestOptions,
  ): Promise<EventStream<models.AnthropicStreamEvent>>;
  async create(
    request: models.AnthropicMessageRequest,
    options?: RequestOptions,
  ): Promise<models.CreateMessageResponse>;
  async create(
    request: models.AnthropicMessageRequest,
    options?: RequestOptions,
  ): Promise<models.CreateMessageResponse> {
    return unwrapAsync(messagesCreate(
      this,
      request,
      options,
    ));
  }
}
