/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { moderationsCreate } from "../funcs/moderationsCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Moderations extends ClientSDK {
  /**
   * Create content moderation
   *
   * @remarks
   * Perform content moderation on input text, detecting potentially harmful content
   */
  async create(
    request: models.ModerationRequest,
    options?: RequestOptions,
  ): Promise<models.ModerationResponse> {
    return unwrapAsync(moderationsCreate(
      this,
      request,
      options,
    ));
  }
}
