/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { modelsList } from "../funcs/modelsList.js";
import { modelsRetrieve } from "../funcs/modelsRetrieve.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Models extends ClientSDK {
  /**
   * List available models
   *
   * @remarks
   * List all available models
   */
  async list(
    options?: RequestOptions,
  ): Promise<models.ModelListResponse> {
    return unwrapAsync(modelsList(
      this,
      options,
    ));
  }

  /**
   * Retrieve model details
   *
   * @remarks
   * Retrieve detailed information for a specified model
   */
  async retrieve(
    model: string,
    options?: RequestOptions,
  ): Promise<models.Model> {
    return unwrapAsync(modelsRetrieve(
      this,
      model,
      options,
    ));
  }
}
