/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { proxyRequest } from "../funcs/proxyRequest.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";

export class Proxy extends ClientSDK {
  /**
   * Proxy request
   *
   * @remarks
   * Proxy requests to target endpoint through specified channel
   */
  async request(
    channelid: string,
    target: string,
    requestBody?: { [k: string]: any } | undefined,
    options?: RequestOptions,
  ): Promise<{ [k: string]: any }> {
    return unwrapAsync(proxyRequest(
      this,
      channelid,
      target,
      requestBody,
      options,
    ));
  }
}
