/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { responsesCreate } from "../funcs/responsesCreate.js";
import { EventStream } from "../lib/event-streams.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Responses extends ClientSDK {
  /**
   * Create response
   *
   * @remarks
   * Create a response with streaming support. This endpoint corresponds to OpenAI's Responses API.
   */
  async create(
    request: models.ResponseRequest & { stream?: false | undefined },
    options?: RequestOptions,
  ): Promise<models.ResponseObject>;
  async create(
    request: models.ResponseRequest & { stream: true },
    options?: RequestOptions,
  ): Promise<EventStream<models.ResponseStreamEvent>>;
  async create(
    request: models.ResponseRequest,
    options?: RequestOptions,
  ): Promise<models.CreateResponseResponse>;
  async create(
    request: models.ResponseRequest,
    options?: RequestOptions,
  ): Promise<models.CreateResponseResponse> {
    return unwrapAsync(responsesCreate(
      this,
      request,
      options,
    ));
  }
}
