/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { AudioSDK } from "./audiosdk.js";
import { Chat } from "./chat.js";
import { Completions } from "./completions.js";
import { Edits } from "./edits.js";
import { Embeddings } from "./embeddings.js";
import { EngineEmbeddings } from "./engineembeddings.js";
import { Images } from "./images.js";
import { Messages } from "./messages.js";
import { Models } from "./models.js";
import { Moderations } from "./moderations.js";
import { Proxy } from "./proxy.js";
import { Responses } from "./responses.js";
import { Search } from "./search.js";

export class R9S extends ClientSDK {
  private _models?: Models;
  get models(): Models {
    return (this._models ??= new Models(this._options));
  }

  private _chat?: Chat;
  get chat(): Chat {
    return (this._chat ??= new Chat(this._options));
  }

  private _responses?: Responses;
  get responses(): Responses {
    return (this._responses ??= new Responses(this._options));
  }

  private _messages?: Messages;
  get messages(): Messages {
    return (this._messages ??= new Messages(this._options));
  }

  private _completions?: Completions;
  get completions(): Completions {
    return (this._completions ??= new Completions(this._options));
  }

  private _edits?: Edits;
  get edits(): Edits {
    return (this._edits ??= new Edits(this._options));
  }

  private _images?: Images;
  get images(): Images {
    return (this._images ??= new Images(this._options));
  }

  private _embeddings?: Embeddings;
  get embeddings(): Embeddings {
    return (this._embeddings ??= new Embeddings(this._options));
  }

  private _engineEmbeddings?: EngineEmbeddings;
  get engineEmbeddings(): EngineEmbeddings {
    return (this._engineEmbeddings ??= new EngineEmbeddings(this._options));
  }

  private _moderations?: Moderations;
  get moderations(): Moderations {
    return (this._moderations ??= new Moderations(this._options));
  }

  private _audioSDK?: AudioSDK;
  get audioSDK(): AudioSDK {
    return (this._audioSDK ??= new AudioSDK(this._options));
  }

  private _search?: Search;
  get search(): Search {
    return (this._search ??= new Search(this._options));
  }

  private _proxy?: Proxy;
  get proxy(): Proxy {
    return (this._proxy ??= new Proxy(this._options));
  }
}
