/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { searchCreate } from "../funcs/searchCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Search extends ClientSDK {
  /**
   * Create search
   *
   * @remarks
   * Execute web search queries using specified search engine. Supports three search engines:Exa (AI-native search, default), Tavily (with AI summary), Google (custom search)
   */
  async create(
    request: models.SearchRequest,
    options?: RequestOptions,
  ): Promise<models.SearchResponse> {
    return unwrapAsync(searchCreate(
      this,
      request,
      options,
    ));
  }
}
