/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @r9s/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx modelsList.example.ts
 */

import { R9S } from "@r9s/sdk";

const r9S = new R9S({
  apiKey: "<YOUR_BEARER_TOKEN_HERE>",
});

async function main() {
  const result = await r9S.models.list();

  console.log(result);
}

main().catch(console.error);
