/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

export type AnthropicImageSourceUrl = {
  type: "url";
  /**
   * URL of the image to fetch
   */
  url: string;
};

/** @internal */
export const AnthropicImageSourceUrl$inboundSchema: z.ZodMiniType<
  AnthropicImageSourceUrl,
  unknown
> = z.object({
  type: types.literal("url"),
  url: types.string(),
});
/** @internal */
export type AnthropicImageSourceUrl$Outbound = {
  type: "url";
  url: string;
};

/** @internal */
export const AnthropicImageSourceUrl$outboundSchema: z.ZodMiniType<
  AnthropicImageSourceUrl$Outbound,
  AnthropicImageSourceUrl
> = z.object({
  type: z.literal("url"),
  url: z.string(),
});

export function anthropicImageSourceUrlToJSON(
  anthropicImageSourceUrl: AnthropicImageSourceUrl,
): string {
  return JSON.stringify(
    AnthropicImageSourceUrl$outboundSchema.parse(anthropicImageSourceUrl),
  );
}
export function anthropicImageSourceUrlFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicImageSourceUrl, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicImageSourceUrl$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicImageSourceUrl' from JSON`,
  );
}
