/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type Properties = {};

export type AnthropicInputSchema = {
  type: "object";
  properties?: Properties | undefined;
  required?: Array<string> | undefined;
};

/** @internal */
export type Properties$Outbound = {};

/** @internal */
export const Properties$outboundSchema: z.ZodMiniType<
  Properties$Outbound,
  Properties
> = z.object({});

export function propertiesToJSON(properties: Properties): string {
  return JSON.stringify(Properties$outboundSchema.parse(properties));
}

/** @internal */
export type AnthropicInputSchema$Outbound = {
  type: "object";
  properties?: Properties$Outbound | undefined;
  required?: Array<string> | undefined;
};

/** @internal */
export const AnthropicInputSchema$outboundSchema: z.ZodMiniType<
  AnthropicInputSchema$Outbound,
  AnthropicInputSchema
> = z.object({
  type: z.literal("object"),
  properties: z.optional(z.lazy(() => Properties$outboundSchema)),
  required: z.optional(z.array(z.string())),
});

export function anthropicInputSchemaToJSON(
  anthropicInputSchema: AnthropicInputSchema,
): string {
  return JSON.stringify(
    AnthropicInputSchema$outboundSchema.parse(anthropicInputSchema),
  );
}
