/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

/**
 * MIME type of the image
 */
export const MediaType = {
  ImageJpeg: "image/jpeg",
  ImagePng: "image/png",
  ImageGif: "image/gif",
  ImageWebp: "image/webp",
} as const;
/**
 * MIME type of the image
 */
export type MediaType = OpenEnum<typeof MediaType>;

export type AnthropicImageSourceBase64 = {
  type: "base64";
  /**
   * MIME type of the image
   */
  mediaType: MediaType;
  /**
   * Base64-encoded image data
   */
  data: string;
};

/** @internal */
export const MediaType$inboundSchema: z.ZodMiniType<MediaType, unknown> =
  openEnums.inboundSchema(MediaType);
/** @internal */
export const MediaType$outboundSchema: z.ZodMiniType<string, MediaType> =
  openEnums.outboundSchema(MediaType);

/** @internal */
export const AnthropicImageSourceBase64$inboundSchema: z.ZodMiniType<
  AnthropicImageSourceBase64,
  unknown
> = z.pipe(
  z.object({
    type: types.literal("base64"),
    media_type: MediaType$inboundSchema,
    data: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "media_type": "mediaType",
    });
  }),
);
/** @internal */
export type AnthropicImageSourceBase64$Outbound = {
  type: "base64";
  media_type: string;
  data: string;
};

/** @internal */
export const AnthropicImageSourceBase64$outboundSchema: z.ZodMiniType<
  AnthropicImageSourceBase64$Outbound,
  AnthropicImageSourceBase64
> = z.pipe(
  z.object({
    type: z.literal("base64"),
    mediaType: MediaType$outboundSchema,
    data: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      mediaType: "media_type",
    });
  }),
);

export function anthropicImageSourceBase64ToJSON(
  anthropicImageSourceBase64: AnthropicImageSourceBase64,
): string {
  return JSON.stringify(
    AnthropicImageSourceBase64$outboundSchema.parse(anthropicImageSourceBase64),
  );
}
export function anthropicImageSourceBase64FromJSON(
  jsonString: string,
): SafeParseResult<AnthropicImageSourceBase64, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicImageSourceBase64$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicImageSourceBase64' from JSON`,
  );
}
