/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

export type AnthropicDocumentSourceUrl = {
  type: "url";
  /**
   * URL of the document to fetch
   */
  url: string;
};

/** @internal */
export const AnthropicDocumentSourceUrl$inboundSchema: z.ZodMiniType<
  AnthropicDocumentSourceUrl,
  unknown
> = z.object({
  type: types.literal("url"),
  url: types.string(),
});
/** @internal */
export type AnthropicDocumentSourceUrl$Outbound = {
  type: "url";
  url: string;
};

/** @internal */
export const AnthropicDocumentSourceUrl$outboundSchema: z.ZodMiniType<
  AnthropicDocumentSourceUrl$Outbound,
  AnthropicDocumentSourceUrl
> = z.object({
  type: z.literal("url"),
  url: z.string(),
});

export function anthropicDocumentSourceUrlToJSON(
  anthropicDocumentSourceUrl: AnthropicDocumentSourceUrl,
): string {
  return JSON.stringify(
    AnthropicDocumentSourceUrl$outboundSchema.parse(anthropicDocumentSourceUrl),
  );
}
export function anthropicDocumentSourceUrlFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicDocumentSourceUrl, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicDocumentSourceUrl$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicDocumentSourceUrl' from JSON`,
  );
}
