/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminatedUnion.js";
import { discriminatedUnion } from "../types/discriminatedUnion.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AnthropicContentBlockDelta,
  AnthropicContentBlockDelta$inboundSchema,
} from "./anthropiccontentblockdelta.js";
import {
  AnthropicContentBlockStart,
  AnthropicContentBlockStart$inboundSchema,
} from "./anthropiccontentblockstart.js";
import {
  AnthropicContentBlockStop,
  AnthropicContentBlockStop$inboundSchema,
} from "./anthropiccontentblockstop.js";
import {
  AnthropicMessageDelta,
  AnthropicMessageDelta$inboundSchema,
} from "./anthropicmessagedelta.js";
import {
  AnthropicMessageStart,
  AnthropicMessageStart$inboundSchema,
} from "./anthropicmessagestart.js";
import { AnthropicPing, AnthropicPing$inboundSchema } from "./anthropicping.js";
import {
  AnthropicStreamMessageStop,
  AnthropicStreamMessageStop$inboundSchema,
} from "./anthropicstreammessagestop.js";

export type AnthropicStreamEvent =
  | AnthropicMessageStart
  | AnthropicContentBlockStart
  | AnthropicContentBlockDelta
  | AnthropicContentBlockStop
  | AnthropicMessageDelta
  | AnthropicStreamMessageStop
  | AnthropicPing
  | discriminatedUnionTypes.Unknown<"type">;

/** @internal */
export const AnthropicStreamEvent$inboundSchema: z.ZodMiniType<
  AnthropicStreamEvent,
  unknown
> = discriminatedUnion("type", {
  message_start: AnthropicMessageStart$inboundSchema,
  content_block_start: AnthropicContentBlockStart$inboundSchema,
  content_block_delta: AnthropicContentBlockDelta$inboundSchema,
  content_block_stop: AnthropicContentBlockStop$inboundSchema,
  message_delta: AnthropicMessageDelta$inboundSchema,
  message_stop: AnthropicStreamMessageStop$inboundSchema,
  ping: AnthropicPing$inboundSchema,
});

export function anthropicStreamEventFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicStreamEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicStreamEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicStreamEvent' from JSON`,
  );
}
