/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminatedUnion.js";
import { discriminatedUnion } from "../types/discriminatedUnion.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AnthropicToolResultContent,
  AnthropicToolResultContent$inboundSchema,
  AnthropicToolResultContent$Outbound,
  AnthropicToolResultContent$outboundSchema,
} from "./anthropictoolresultcontent.js";
import {
  AnthropicToolUseContent,
  AnthropicToolUseContent$inboundSchema,
  AnthropicToolUseContent$Outbound,
  AnthropicToolUseContent$outboundSchema,
} from "./anthropictoolusecontent.js";

export type AnthropicToolContent =
  | AnthropicToolUseContent
  | AnthropicToolResultContent
  | discriminatedUnionTypes.Unknown<"type">;

/** @internal */
export const AnthropicToolContent$inboundSchema: z.ZodMiniType<
  AnthropicToolContent,
  unknown
> = discriminatedUnion("type", {
  tool_use: AnthropicToolUseContent$inboundSchema,
  tool_result: AnthropicToolResultContent$inboundSchema,
});
/** @internal */
export type AnthropicToolContent$Outbound =
  | AnthropicToolUseContent$Outbound
  | AnthropicToolResultContent$Outbound;

/** @internal */
export const AnthropicToolContent$outboundSchema: z.ZodMiniType<
  AnthropicToolContent$Outbound,
  AnthropicToolContent
> = z.union([
  AnthropicToolUseContent$outboundSchema,
  AnthropicToolResultContent$outboundSchema,
]);

export function anthropicToolContentToJSON(
  anthropicToolContent: AnthropicToolContent,
): string {
  return JSON.stringify(
    AnthropicToolContent$outboundSchema.parse(anthropicToolContent),
  );
}
export function anthropicToolContentFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicToolContent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicToolContent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicToolContent' from JSON`,
  );
}
