/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminatedUnion.js";
import { discriminatedUnion } from "../types/discriminatedUnion.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AnthropicDocumentSourceBase64,
  AnthropicDocumentSourceBase64$inboundSchema,
  AnthropicDocumentSourceBase64$Outbound,
  AnthropicDocumentSourceBase64$outboundSchema,
} from "./anthropicdocumentsourcebase64.js";
import {
  AnthropicDocumentSourceUrl,
  AnthropicDocumentSourceUrl$inboundSchema,
  AnthropicDocumentSourceUrl$Outbound,
  AnthropicDocumentSourceUrl$outboundSchema,
} from "./anthropicdocumentsourceurl.js";

export type AnthropicDocumentSource =
  | AnthropicDocumentSourceBase64
  | AnthropicDocumentSourceUrl
  | discriminatedUnionTypes.Unknown<"type">;

/** @internal */
export const AnthropicDocumentSource$inboundSchema: z.ZodMiniType<
  AnthropicDocumentSource,
  unknown
> = discriminatedUnion("type", {
  base64: AnthropicDocumentSourceBase64$inboundSchema,
  url: AnthropicDocumentSourceUrl$inboundSchema,
});
/** @internal */
export type AnthropicDocumentSource$Outbound =
  | AnthropicDocumentSourceBase64$Outbound
  | AnthropicDocumentSourceUrl$Outbound;

/** @internal */
export const AnthropicDocumentSource$outboundSchema: z.ZodMiniType<
  AnthropicDocumentSource$Outbound,
  AnthropicDocumentSource
> = z.union([
  AnthropicDocumentSourceBase64$outboundSchema,
  AnthropicDocumentSourceUrl$outboundSchema,
]);

export function anthropicDocumentSourceToJSON(
  anthropicDocumentSource: AnthropicDocumentSource,
): string {
  return JSON.stringify(
    AnthropicDocumentSource$outboundSchema.parse(anthropicDocumentSource),
  );
}
export function anthropicDocumentSourceFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicDocumentSource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicDocumentSource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicDocumentSource' from JSON`,
  );
}
