/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

/**
 * Optional content block metadata
 */
export type AnthropicContentBlockStopContentBlock = {};

export type AnthropicContentBlockStop = {
  type: "content_block_stop";
  index: number;
  /**
   * Optional content block metadata
   */
  contentBlock?: AnthropicContentBlockStopContentBlock | undefined;
};

/** @internal */
export const AnthropicContentBlockStopContentBlock$inboundSchema: z.ZodMiniType<
  AnthropicContentBlockStopContentBlock,
  unknown
> = z.object({});

export function anthropicContentBlockStopContentBlockFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicContentBlockStopContentBlock, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AnthropicContentBlockStopContentBlock$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicContentBlockStopContentBlock' from JSON`,
  );
}

/** @internal */
export const AnthropicContentBlockStop$inboundSchema: z.ZodMiniType<
  AnthropicContentBlockStop,
  unknown
> = z.pipe(
  z.object({
    type: types.literal("content_block_stop"),
    index: types.number(),
    content_block: types.optional(
      z.lazy(() => AnthropicContentBlockStopContentBlock$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "content_block": "contentBlock",
    });
  }),
);

export function anthropicContentBlockStopFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicContentBlockStop, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicContentBlockStop$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicContentBlockStop' from JSON`,
  );
}
