/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

export type AnthropicToolResultContent = {
  type: "tool_result";
  /**
   * ID of the tool use this result corresponds to
   */
  toolUseId: string;
  /**
   * Result of the tool execution
   */
  content: string;
};

/** @internal */
export const AnthropicToolResultContent$inboundSchema: z.ZodMiniType<
  AnthropicToolResultContent,
  unknown
> = z.pipe(
  z.object({
    type: types.literal("tool_result"),
    tool_use_id: types.string(),
    content: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "tool_use_id": "toolUseId",
    });
  }),
);
/** @internal */
export type AnthropicToolResultContent$Outbound = {
  type: "tool_result";
  tool_use_id: string;
  content: string;
};

/** @internal */
export const AnthropicToolResultContent$outboundSchema: z.ZodMiniType<
  AnthropicToolResultContent$Outbound,
  AnthropicToolResultContent
> = z.pipe(
  z.object({
    type: z.literal("tool_result"),
    toolUseId: z.string(),
    content: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      toolUseId: "tool_use_id",
    });
  }),
);

export function anthropicToolResultContentToJSON(
  anthropicToolResultContent: AnthropicToolResultContent,
): string {
  return JSON.stringify(
    AnthropicToolResultContent$outboundSchema.parse(anthropicToolResultContent),
  );
}
export function anthropicToolResultContentFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicToolResultContent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicToolResultContent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicToolResultContent' from JSON`,
  );
}
