/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

export type AnthropicMessageStartContent = {};

export type AnthropicMessageStartUsage = {
  inputTokens: number;
  outputTokens: number;
};

export type AnthropicMessageStartMessage = {
  id: string;
  type: "message";
  role: "assistant";
  content: Array<AnthropicMessageStartContent>;
  model: string;
  stopReason: string | null;
  stopSequence: string | null;
  usage: AnthropicMessageStartUsage;
};

export type AnthropicMessageStart = {
  type: "message_start";
  message: AnthropicMessageStartMessage;
};

/** @internal */
export const AnthropicMessageStartContent$inboundSchema: z.ZodMiniType<
  AnthropicMessageStartContent,
  unknown
> = z.object({});

export function anthropicMessageStartContentFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicMessageStartContent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicMessageStartContent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicMessageStartContent' from JSON`,
  );
}

/** @internal */
export const AnthropicMessageStartUsage$inboundSchema: z.ZodMiniType<
  AnthropicMessageStartUsage,
  unknown
> = z.pipe(
  z.object({
    input_tokens: types.number(),
    output_tokens: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "input_tokens": "inputTokens",
      "output_tokens": "outputTokens",
    });
  }),
);

export function anthropicMessageStartUsageFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicMessageStartUsage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicMessageStartUsage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicMessageStartUsage' from JSON`,
  );
}

/** @internal */
export const AnthropicMessageStartMessage$inboundSchema: z.ZodMiniType<
  AnthropicMessageStartMessage,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    type: types.literal("message"),
    role: types.literal("assistant"),
    content: z.array(z.lazy(() => AnthropicMessageStartContent$inboundSchema)),
    model: types.string(),
    stop_reason: types.nullable(types.string()),
    stop_sequence: types.nullable(types.string()),
    usage: z.lazy(() => AnthropicMessageStartUsage$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "stop_reason": "stopReason",
      "stop_sequence": "stopSequence",
    });
  }),
);

export function anthropicMessageStartMessageFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicMessageStartMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicMessageStartMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicMessageStartMessage' from JSON`,
  );
}

/** @internal */
export const AnthropicMessageStart$inboundSchema: z.ZodMiniType<
  AnthropicMessageStart,
  unknown
> = z.object({
  type: types.literal("message_start"),
  message: z.lazy(() => AnthropicMessageStartMessage$inboundSchema),
});

export function anthropicMessageStartFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicMessageStart, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicMessageStart$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicMessageStart' from JSON`,
  );
}
