/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  AnthropicDocumentSource,
  AnthropicDocumentSource$inboundSchema,
  AnthropicDocumentSource$Outbound,
  AnthropicDocumentSource$outboundSchema,
} from "./anthropicdocumentsource.js";

export type AnthropicDocumentContent = {
  /**
   * Document content type (PDFs, text files, etc.)
   */
  type: "document";
  source: AnthropicDocumentSource;
};

/** @internal */
export const AnthropicDocumentContent$inboundSchema: z.ZodMiniType<
  AnthropicDocumentContent,
  unknown
> = z.object({
  type: types.literal("document"),
  source: AnthropicDocumentSource$inboundSchema,
});
/** @internal */
export type AnthropicDocumentContent$Outbound = {
  type: "document";
  source: AnthropicDocumentSource$Outbound;
};

/** @internal */
export const AnthropicDocumentContent$outboundSchema: z.ZodMiniType<
  AnthropicDocumentContent$Outbound,
  AnthropicDocumentContent
> = z.object({
  type: z.literal("document"),
  source: AnthropicDocumentSource$outboundSchema,
});

export function anthropicDocumentContentToJSON(
  anthropicDocumentContent: AnthropicDocumentContent,
): string {
  return JSON.stringify(
    AnthropicDocumentContent$outboundSchema.parse(anthropicDocumentContent),
  );
}
export function anthropicDocumentContentFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicDocumentContent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicDocumentContent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicDocumentContent' from JSON`,
  );
}
