/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { smartUnion } from "../types/smartUnion.js";
import {
  AnthropicDocumentContent,
  AnthropicDocumentContent$inboundSchema,
  AnthropicDocumentContent$Outbound,
  AnthropicDocumentContent$outboundSchema,
} from "./anthropicdocumentcontent.js";
import {
  AnthropicImageContent,
  AnthropicImageContent$inboundSchema,
  AnthropicImageContent$Outbound,
  AnthropicImageContent$outboundSchema,
} from "./anthropicimagecontent.js";
import {
  AnthropicTextContent,
  AnthropicTextContent$inboundSchema,
  AnthropicTextContent$Outbound,
  AnthropicTextContent$outboundSchema,
} from "./anthropictextcontent.js";
import {
  AnthropicThinkingContent,
  AnthropicThinkingContent$inboundSchema,
  AnthropicThinkingContent$Outbound,
  AnthropicThinkingContent$outboundSchema,
} from "./anthropicthinkingcontent.js";
import {
  AnthropicToolContent,
  AnthropicToolContent$inboundSchema,
  AnthropicToolContent$Outbound,
  AnthropicToolContent$outboundSchema,
} from "./anthropictoolcontent.js";

export type AnthropicContent =
  | AnthropicTextContent
  | AnthropicImageContent
  | AnthropicDocumentContent
  | AnthropicThinkingContent
  | AnthropicToolContent;

/** @internal */
export const AnthropicContent$inboundSchema: z.ZodMiniType<
  AnthropicContent,
  unknown
> = smartUnion([
  AnthropicTextContent$inboundSchema,
  AnthropicImageContent$inboundSchema,
  AnthropicDocumentContent$inboundSchema,
  AnthropicThinkingContent$inboundSchema,
  AnthropicToolContent$inboundSchema,
]);
/** @internal */
export type AnthropicContent$Outbound =
  | AnthropicTextContent$Outbound
  | AnthropicImageContent$Outbound
  | AnthropicDocumentContent$Outbound
  | AnthropicThinkingContent$Outbound
  | AnthropicToolContent$Outbound;

/** @internal */
export const AnthropicContent$outboundSchema: z.ZodMiniType<
  AnthropicContent$Outbound,
  AnthropicContent
> = smartUnion([
  AnthropicTextContent$outboundSchema,
  AnthropicImageContent$outboundSchema,
  AnthropicDocumentContent$outboundSchema,
  AnthropicThinkingContent$outboundSchema,
  AnthropicToolContent$outboundSchema,
]);

export function anthropicContentToJSON(
  anthropicContent: AnthropicContent,
): string {
  return JSON.stringify(
    AnthropicContent$outboundSchema.parse(anthropicContent),
  );
}
export function anthropicContentFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicContent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicContent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicContent' from JSON`,
  );
}
