/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  AnthropicImageSource,
  AnthropicImageSource$inboundSchema,
  AnthropicImageSource$Outbound,
  AnthropicImageSource$outboundSchema,
} from "./anthropicimagesource.js";

export type AnthropicImageContent = {
  type: "image";
  source: AnthropicImageSource;
};

/** @internal */
export const AnthropicImageContent$inboundSchema: z.ZodMiniType<
  AnthropicImageContent,
  unknown
> = z.object({
  type: types.literal("image"),
  source: AnthropicImageSource$inboundSchema,
});
/** @internal */
export type AnthropicImageContent$Outbound = {
  type: "image";
  source: AnthropicImageSource$Outbound;
};

/** @internal */
export const AnthropicImageContent$outboundSchema: z.ZodMiniType<
  AnthropicImageContent$Outbound,
  AnthropicImageContent
> = z.object({
  type: z.literal("image"),
  source: AnthropicImageSource$outboundSchema,
});

export function anthropicImageContentToJSON(
  anthropicImageContent: AnthropicImageContent,
): string {
  return JSON.stringify(
    AnthropicImageContent$outboundSchema.parse(anthropicImageContent),
  );
}
export function anthropicImageContentFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicImageContent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicImageContent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicImageContent' from JSON`,
  );
}
