/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

export type AnthropicStreamMessageStop = {
  type: "message_stop";
};

/** @internal */
export const AnthropicStreamMessageStop$inboundSchema: z.ZodMiniType<
  AnthropicStreamMessageStop,
  unknown
> = z.object({
  type: types.literal("message_stop"),
});

export function anthropicStreamMessageStopFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicStreamMessageStop, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicStreamMessageStop$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicStreamMessageStop' from JSON`,
  );
}
