/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

/**
 * Document MIME type
 */
export const AnthropicDocumentSourceBase64MediaType = {
  ApplicationPdf: "application/pdf",
  TextPlain: "text/plain",
} as const;
/**
 * Document MIME type
 */
export type AnthropicDocumentSourceBase64MediaType = OpenEnum<
  typeof AnthropicDocumentSourceBase64MediaType
>;

export type AnthropicDocumentSourceBase64 = {
  type: "base64";
  /**
   * Document MIME type
   */
  mediaType: AnthropicDocumentSourceBase64MediaType;
  /**
   * Base64-encoded document data
   */
  data: string;
};

/** @internal */
export const AnthropicDocumentSourceBase64MediaType$inboundSchema:
  z.ZodMiniType<AnthropicDocumentSourceBase64MediaType, unknown> = openEnums
    .inboundSchema(AnthropicDocumentSourceBase64MediaType);
/** @internal */
export const AnthropicDocumentSourceBase64MediaType$outboundSchema:
  z.ZodMiniType<string, AnthropicDocumentSourceBase64MediaType> = openEnums
    .outboundSchema(AnthropicDocumentSourceBase64MediaType);

/** @internal */
export const AnthropicDocumentSourceBase64$inboundSchema: z.ZodMiniType<
  AnthropicDocumentSourceBase64,
  unknown
> = z.pipe(
  z.object({
    type: types.literal("base64"),
    media_type: AnthropicDocumentSourceBase64MediaType$inboundSchema,
    data: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "media_type": "mediaType",
    });
  }),
);
/** @internal */
export type AnthropicDocumentSourceBase64$Outbound = {
  type: "base64";
  media_type: string;
  data: string;
};

/** @internal */
export const AnthropicDocumentSourceBase64$outboundSchema: z.ZodMiniType<
  AnthropicDocumentSourceBase64$Outbound,
  AnthropicDocumentSourceBase64
> = z.pipe(
  z.object({
    type: z.literal("base64"),
    mediaType: AnthropicDocumentSourceBase64MediaType$outboundSchema,
    data: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      mediaType: "media_type",
    });
  }),
);

export function anthropicDocumentSourceBase64ToJSON(
  anthropicDocumentSourceBase64: AnthropicDocumentSourceBase64,
): string {
  return JSON.stringify(
    AnthropicDocumentSourceBase64$outboundSchema.parse(
      anthropicDocumentSourceBase64,
    ),
  );
}
export function anthropicDocumentSourceBase64FromJSON(
  jsonString: string,
): SafeParseResult<AnthropicDocumentSourceBase64, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicDocumentSourceBase64$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicDocumentSourceBase64' from JSON`,
  );
}
