/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  AnthropicInputSchema,
  AnthropicInputSchema$Outbound,
  AnthropicInputSchema$outboundSchema,
} from "./anthropicinputschema.js";

export type AnthropicTool = {
  name: string;
  description?: string | undefined;
  inputSchema: AnthropicInputSchema;
};

/** @internal */
export type AnthropicTool$Outbound = {
  name: string;
  description?: string | undefined;
  input_schema: AnthropicInputSchema$Outbound;
};

/** @internal */
export const AnthropicTool$outboundSchema: z.ZodMiniType<
  AnthropicTool$Outbound,
  AnthropicTool
> = z.pipe(
  z.object({
    name: z.string(),
    description: z.optional(z.string()),
    inputSchema: AnthropicInputSchema$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      inputSchema: "input_schema",
    });
  }),
);

export function anthropicToolToJSON(anthropicTool: AnthropicTool): string {
  return JSON.stringify(AnthropicTool$outboundSchema.parse(anthropicTool));
}
