/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

/**
 * SSE heartbeat event to keep connection alive
 */
export type AnthropicPing = {
  type: "ping";
};

/** @internal */
export const AnthropicPing$inboundSchema: z.ZodMiniType<
  AnthropicPing,
  unknown
> = z.object({
  type: types.literal("ping"),
});

export function anthropicPingFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicPing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicPing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicPing' from JSON`,
  );
}
