/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

export type AnthropicToolUseContent = {
  type: "tool_use";
  /**
   * Unique identifier for this tool use
   */
  id: string;
  /**
   * Name of the tool being called
   */
  name: string;
  /**
   * Input parameters for the tool
   */
  input: { [k: string]: any };
};

/** @internal */
export const AnthropicToolUseContent$inboundSchema: z.ZodMiniType<
  AnthropicToolUseContent,
  unknown
> = z.object({
  type: types.literal("tool_use"),
  id: types.string(),
  name: types.string(),
  input: z.record(z.string(), z.any()),
});
/** @internal */
export type AnthropicToolUseContent$Outbound = {
  type: "tool_use";
  id: string;
  name: string;
  input: { [k: string]: any };
};

/** @internal */
export const AnthropicToolUseContent$outboundSchema: z.ZodMiniType<
  AnthropicToolUseContent$Outbound,
  AnthropicToolUseContent
> = z.object({
  type: z.literal("tool_use"),
  id: z.string(),
  name: z.string(),
  input: z.record(z.string(), z.any()),
});

export function anthropicToolUseContentToJSON(
  anthropicToolUseContent: AnthropicToolUseContent,
): string {
  return JSON.stringify(
    AnthropicToolUseContent$outboundSchema.parse(anthropicToolUseContent),
  );
}
export function anthropicToolUseContentFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicToolUseContent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicToolUseContent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicToolUseContent' from JSON`,
  );
}
