/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";
import { smartUnion } from "../types/smartUnion.js";
import {
  AnthropicContent,
  AnthropicContent$Outbound,
  AnthropicContent$outboundSchema,
} from "./anthropiccontent.js";

/**
 * Role of the message sender (user or assistant)
 */
export const AnthropicMessageMessageRole = {
  User: "user",
  Assistant: "assistant",
} as const;
/**
 * Role of the message sender (user or assistant)
 */
export type AnthropicMessageMessageRole = ClosedEnum<
  typeof AnthropicMessageMessageRole
>;

/**
 * Message content - can be array of content blocks or string
 */
export type AnthropicMessageMessageContent = Array<AnthropicContent> | string;

export type AnthropicMessageMessage = {
  /**
   * Role of the message sender (user or assistant)
   */
  role: AnthropicMessageMessageRole;
  /**
   * Message content - can be array of content blocks or string
   */
  content: Array<AnthropicContent> | string;
};

/** @internal */
export const AnthropicMessageMessageRole$outboundSchema: z.ZodMiniEnum<
  typeof AnthropicMessageMessageRole
> = z.enum(AnthropicMessageMessageRole);

/** @internal */
export type AnthropicMessageMessageContent$Outbound =
  | Array<AnthropicContent$Outbound>
  | string;

/** @internal */
export const AnthropicMessageMessageContent$outboundSchema: z.ZodMiniType<
  AnthropicMessageMessageContent$Outbound,
  AnthropicMessageMessageContent
> = smartUnion([z.array(AnthropicContent$outboundSchema), z.string()]);

export function anthropicMessageMessageContentToJSON(
  anthropicMessageMessageContent: AnthropicMessageMessageContent,
): string {
  return JSON.stringify(
    AnthropicMessageMessageContent$outboundSchema.parse(
      anthropicMessageMessageContent,
    ),
  );
}

/** @internal */
export type AnthropicMessageMessage$Outbound = {
  role: string;
  content: Array<AnthropicContent$Outbound> | string;
};

/** @internal */
export const AnthropicMessageMessage$outboundSchema: z.ZodMiniType<
  AnthropicMessageMessage$Outbound,
  AnthropicMessageMessage
> = z.object({
  role: AnthropicMessageMessageRole$outboundSchema,
  content: smartUnion([z.array(AnthropicContent$outboundSchema), z.string()]),
});

export function anthropicMessageMessageToJSON(
  anthropicMessageMessage: AnthropicMessageMessage,
): string {
  return JSON.stringify(
    AnthropicMessageMessage$outboundSchema.parse(anthropicMessageMessage),
  );
}
