/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

export type AnthropicTextContent = {
  type: "text";
  text: string;
};

/** @internal */
export const AnthropicTextContent$inboundSchema: z.ZodMiniType<
  AnthropicTextContent,
  unknown
> = z.object({
  type: types.literal("text"),
  text: types.string(),
});
/** @internal */
export type AnthropicTextContent$Outbound = {
  type: "text";
  text: string;
};

/** @internal */
export const AnthropicTextContent$outboundSchema: z.ZodMiniType<
  AnthropicTextContent$Outbound,
  AnthropicTextContent
> = z.object({
  type: z.literal("text"),
  text: z.string(),
});

export function anthropicTextContentToJSON(
  anthropicTextContent: AnthropicTextContent,
): string {
  return JSON.stringify(
    AnthropicTextContent$outboundSchema.parse(anthropicTextContent),
  );
}
export function anthropicTextContentFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicTextContent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicTextContent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicTextContent' from JSON`,
  );
}
