/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

export type AnthropicMessageDeltaDelta = {
  stopReason?: string | null | undefined;
};

export type AnthropicMessageDeltaUsage = {
  outputTokens?: number | undefined;
};

export type AnthropicMessageDelta = {
  type: "message_delta";
  delta: AnthropicMessageDeltaDelta;
  usage: AnthropicMessageDeltaUsage;
};

/** @internal */
export const AnthropicMessageDeltaDelta$inboundSchema: z.ZodMiniType<
  AnthropicMessageDeltaDelta,
  unknown
> = z.pipe(
  z.object({
    stop_reason: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "stop_reason": "stopReason",
    });
  }),
);

export function anthropicMessageDeltaDeltaFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicMessageDeltaDelta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicMessageDeltaDelta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicMessageDeltaDelta' from JSON`,
  );
}

/** @internal */
export const AnthropicMessageDeltaUsage$inboundSchema: z.ZodMiniType<
  AnthropicMessageDeltaUsage,
  unknown
> = z.pipe(
  z.object({
    output_tokens: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "output_tokens": "outputTokens",
    });
  }),
);

export function anthropicMessageDeltaUsageFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicMessageDeltaUsage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicMessageDeltaUsage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicMessageDeltaUsage' from JSON`,
  );
}

/** @internal */
export const AnthropicMessageDelta$inboundSchema: z.ZodMiniType<
  AnthropicMessageDelta,
  unknown
> = z.object({
  type: types.literal("message_delta"),
  delta: z.lazy(() => AnthropicMessageDeltaDelta$inboundSchema),
  usage: z.lazy(() => AnthropicMessageDeltaUsage$inboundSchema),
});

export function anthropicMessageDeltaFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicMessageDelta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicMessageDelta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicMessageDelta' from JSON`,
  );
}
