/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

export type AnthropicThinkingContent = {
  /**
   * Extended thinking output content
   */
  type: "thinking";
  /**
   * The model's thinking process/reasoning
   */
  thinking: string;
  /**
   * Cryptographic signature for thinking content verification
   */
  signature?: string | undefined;
};

/** @internal */
export const AnthropicThinkingContent$inboundSchema: z.ZodMiniType<
  AnthropicThinkingContent,
  unknown
> = z.object({
  type: types.literal("thinking"),
  thinking: types.string(),
  signature: types.optional(types.string()),
});
/** @internal */
export type AnthropicThinkingContent$Outbound = {
  type: "thinking";
  thinking: string;
  signature?: string | undefined;
};

/** @internal */
export const AnthropicThinkingContent$outboundSchema: z.ZodMiniType<
  AnthropicThinkingContent$Outbound,
  AnthropicThinkingContent
> = z.object({
  type: z.literal("thinking"),
  thinking: z.string(),
  signature: z.optional(z.string()),
});

export function anthropicThinkingContentToJSON(
  anthropicThinkingContent: AnthropicThinkingContent,
): string {
  return JSON.stringify(
    AnthropicThinkingContent$outboundSchema.parse(anthropicThinkingContent),
  );
}
export function anthropicThinkingContentFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicThinkingContent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicThinkingContent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicThinkingContent' from JSON`,
  );
}
