/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminatedUnion.js";
import { discriminatedUnion } from "../types/discriminatedUnion.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AnthropicImageSourceBase64,
  AnthropicImageSourceBase64$inboundSchema,
  AnthropicImageSourceBase64$Outbound,
  AnthropicImageSourceBase64$outboundSchema,
} from "./anthropicimagesourcebase64.js";
import {
  AnthropicImageSourceUrl,
  AnthropicImageSourceUrl$inboundSchema,
  AnthropicImageSourceUrl$Outbound,
  AnthropicImageSourceUrl$outboundSchema,
} from "./anthropicimagesourceurl.js";

export type AnthropicImageSource =
  | AnthropicImageSourceBase64
  | AnthropicImageSourceUrl
  | discriminatedUnionTypes.Unknown<"type">;

/** @internal */
export const AnthropicImageSource$inboundSchema: z.ZodMiniType<
  AnthropicImageSource,
  unknown
> = discriminatedUnion("type", {
  base64: AnthropicImageSourceBase64$inboundSchema,
  url: AnthropicImageSourceUrl$inboundSchema,
});
/** @internal */
export type AnthropicImageSource$Outbound =
  | AnthropicImageSourceBase64$Outbound
  | AnthropicImageSourceUrl$Outbound;

/** @internal */
export const AnthropicImageSource$outboundSchema: z.ZodMiniType<
  AnthropicImageSource$Outbound,
  AnthropicImageSource
> = z.union([
  AnthropicImageSourceBase64$outboundSchema,
  AnthropicImageSourceUrl$outboundSchema,
]);

export function anthropicImageSourceToJSON(
  anthropicImageSource: AnthropicImageSource,
): string {
  return JSON.stringify(
    AnthropicImageSource$outboundSchema.parse(anthropicImageSource),
  );
}
export function anthropicImageSourceFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicImageSource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicImageSource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicImageSource' from JSON`,
  );
}
