/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

export const AnthropicContentBlockDeltaType = {
  TextDelta: "text_delta",
  InputJsonDelta: "input_json_delta",
} as const;
export type AnthropicContentBlockDeltaType = OpenEnum<
  typeof AnthropicContentBlockDeltaType
>;

export type AnthropicContentBlockDeltaDelta = {
  type?: AnthropicContentBlockDeltaType | undefined;
  text?: string | undefined;
  partialJson?: string | undefined;
};

export type AnthropicContentBlockDelta = {
  type: "content_block_delta";
  index: number;
  delta: AnthropicContentBlockDeltaDelta;
};

/** @internal */
export const AnthropicContentBlockDeltaType$inboundSchema: z.ZodMiniType<
  AnthropicContentBlockDeltaType,
  unknown
> = openEnums.inboundSchema(AnthropicContentBlockDeltaType);

/** @internal */
export const AnthropicContentBlockDeltaDelta$inboundSchema: z.ZodMiniType<
  AnthropicContentBlockDeltaDelta,
  unknown
> = z.pipe(
  z.object({
    type: types.optional(AnthropicContentBlockDeltaType$inboundSchema),
    text: types.optional(types.string()),
    partial_json: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "partial_json": "partialJson",
    });
  }),
);

export function anthropicContentBlockDeltaDeltaFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicContentBlockDeltaDelta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicContentBlockDeltaDelta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicContentBlockDeltaDelta' from JSON`,
  );
}

/** @internal */
export const AnthropicContentBlockDelta$inboundSchema: z.ZodMiniType<
  AnthropicContentBlockDelta,
  unknown
> = z.object({
  type: types.literal("content_block_delta"),
  index: types.number(),
  delta: z.lazy(() => AnthropicContentBlockDeltaDelta$inboundSchema),
});

export function anthropicContentBlockDeltaFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicContentBlockDelta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicContentBlockDelta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicContentBlockDelta' from JSON`,
  );
}
