/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

export type Words = {
  word?: string | undefined;
  start?: number | undefined;
  end?: number | undefined;
};

export type Segments = {
  id?: number | undefined;
  seek?: number | undefined;
  start?: number | undefined;
  end?: number | undefined;
  text?: string | undefined;
  tokens?: Array<number> | undefined;
  temperature?: number | undefined;
  avgLogprob?: number | undefined;
  compressionRatio?: number | undefined;
  noSpeechProb?: number | undefined;
};

export type AudioTranscriptionResponse = {
  /**
   * Transcribed text
   */
  text: string;
  /**
   * Detected language
   */
  language?: string | undefined;
  /**
   * Audio duration (seconds)
   */
  duration?: number | undefined;
  words?: Array<Words> | undefined;
  segments?: Array<Segments> | undefined;
};

/** @internal */
export const Words$inboundSchema: z.ZodMiniType<Words, unknown> = z.object({
  word: types.optional(types.string()),
  start: types.optional(types.number()),
  end: types.optional(types.number()),
});

export function wordsFromJSON(
  jsonString: string,
): SafeParseResult<Words, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Words$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Words' from JSON`,
  );
}

/** @internal */
export const Segments$inboundSchema: z.ZodMiniType<Segments, unknown> = z.pipe(
  z.object({
    id: types.optional(types.number()),
    seek: types.optional(types.number()),
    start: types.optional(types.number()),
    end: types.optional(types.number()),
    text: types.optional(types.string()),
    tokens: types.optional(z.array(types.number())),
    temperature: types.optional(types.number()),
    avg_logprob: types.optional(types.number()),
    compression_ratio: types.optional(types.number()),
    no_speech_prob: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "avg_logprob": "avgLogprob",
      "compression_ratio": "compressionRatio",
      "no_speech_prob": "noSpeechProb",
    });
  }),
);

export function segmentsFromJSON(
  jsonString: string,
): SafeParseResult<Segments, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Segments$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Segments' from JSON`,
  );
}

/** @internal */
export const AudioTranscriptionResponse$inboundSchema: z.ZodMiniType<
  AudioTranscriptionResponse,
  unknown
> = z.object({
  text: types.string(),
  language: types.optional(types.string()),
  duration: types.optional(types.number()),
  words: types.optional(z.array(z.lazy(() => Words$inboundSchema))),
  segments: types.optional(z.array(z.lazy(() => Segments$inboundSchema))),
});

export function audioTranscriptionResponseFromJSON(
  jsonString: string,
): SafeParseResult<AudioTranscriptionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AudioTranscriptionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AudioTranscriptionResponse' from JSON`,
  );
}
