/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

/**
 * Voice type
 */
export const AudioSpeechRequestVoice = {
  Alloy: "alloy",
  Echo: "echo",
  Fable: "fable",
  Onyx: "onyx",
  Nova: "nova",
  Shimmer: "shimmer",
} as const;
/**
 * Voice type
 */
export type AudioSpeechRequestVoice = ClosedEnum<
  typeof AudioSpeechRequestVoice
>;

export const AudioSpeechRequestResponseFormat = {
  Mp3: "mp3",
  Opus: "opus",
  Aac: "aac",
  Flac: "flac",
  Wav: "wav",
  Pcm: "pcm",
} as const;
export type AudioSpeechRequestResponseFormat = ClosedEnum<
  typeof AudioSpeechRequestResponseFormat
>;

export type AudioSpeechRequest = {
  /**
   * TTS model name
   */
  model: string;
  /**
   * Text to convert to speech
   */
  input: string;
  /**
   * Voice type
   */
  voice: AudioSpeechRequestVoice;
  responseFormat?: AudioSpeechRequestResponseFormat | undefined;
  /**
   * Speech speed
   */
  speed?: number | undefined;
};

/** @internal */
export const AudioSpeechRequestVoice$outboundSchema: z.ZodMiniEnum<
  typeof AudioSpeechRequestVoice
> = z.enum(AudioSpeechRequestVoice);

/** @internal */
export const AudioSpeechRequestResponseFormat$outboundSchema: z.ZodMiniEnum<
  typeof AudioSpeechRequestResponseFormat
> = z.enum(AudioSpeechRequestResponseFormat);

/** @internal */
export type AudioSpeechRequest$Outbound = {
  model: string;
  input: string;
  voice: string;
  response_format: string;
  speed: number;
};

/** @internal */
export const AudioSpeechRequest$outboundSchema: z.ZodMiniType<
  AudioSpeechRequest$Outbound,
  AudioSpeechRequest
> = z.pipe(
  z.object({
    model: z.string(),
    input: z.string(),
    voice: AudioSpeechRequestVoice$outboundSchema,
    responseFormat: z._default(
      AudioSpeechRequestResponseFormat$outboundSchema,
      "mp3",
    ),
    speed: z._default(z.number(), 1),
  }),
  z.transform((v) => {
    return remap$(v, {
      responseFormat: "response_format",
    });
  }),
);

export function audioSpeechRequestToJSON(
  audioSpeechRequest: AudioSpeechRequest,
): string {
  return JSON.stringify(
    AudioSpeechRequest$outboundSchema.parse(audioSpeechRequest),
  );
}
