/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * Voice type for audio output
 */
export const Voice = {
  Alloy: "alloy",
  Echo: "echo",
  Fable: "fable",
  Onyx: "onyx",
  Nova: "nova",
  Shimmer: "shimmer",
} as const;
/**
 * Voice type for audio output
 */
export type Voice = ClosedEnum<typeof Voice>;

/**
 * Audio output format
 */
export const Format = {
  Mp3: "mp3",
  Opus: "opus",
  Aac: "aac",
  Flac: "flac",
  Wav: "wav",
  Pcm: "pcm",
} as const;
/**
 * Audio output format
 */
export type Format = ClosedEnum<typeof Format>;

export type Audio = {
  /**
   * Voice type for audio output
   */
  voice?: Voice | undefined;
  /**
   * Audio output format
   */
  format?: Format | undefined;
};

/** @internal */
export const Voice$outboundSchema: z.ZodMiniEnum<typeof Voice> = z.enum(Voice);

/** @internal */
export const Format$outboundSchema: z.ZodMiniEnum<typeof Format> = z.enum(
  Format,
);

/** @internal */
export type Audio$Outbound = {
  voice?: string | undefined;
  format?: string | undefined;
};

/** @internal */
export const Audio$outboundSchema: z.ZodMiniType<Audio$Outbound, Audio> = z
  .object({
    voice: z.optional(Voice$outboundSchema),
    format: z.optional(Format$outboundSchema),
  });

export function audioToJSON(audio: Audio): string {
  return JSON.stringify(Audio$outboundSchema.parse(audio));
}
