/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

export type AudioTranslationResponse = {
  /**
   * Translated English text
   */
  text: string;
  /**
   * Source language
   */
  language?: string | undefined;
  /**
   * Audio duration (seconds)
   */
  duration?: number | undefined;
};

/** @internal */
export const AudioTranslationResponse$inboundSchema: z.ZodMiniType<
  AudioTranslationResponse,
  unknown
> = z.object({
  text: types.string(),
  language: types.optional(types.string()),
  duration: types.optional(types.number()),
});

export function audioTranslationResponseFromJSON(
  jsonString: string,
): SafeParseResult<AudioTranslationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AudioTranslationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AudioTranslationResponse' from JSON`,
  );
}
