/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  GeminiBatchGenerateContentRequest,
  GeminiBatchGenerateContentRequest$Outbound,
  GeminiBatchGenerateContentRequest$outboundSchema,
} from "./geminibatchgeneratecontentrequest.js";

export type BatchGenerateContentRequest = {
  /**
   * Default model for all requests in the batch
   */
  model: string;
  geminiBatchGenerateContentRequest: GeminiBatchGenerateContentRequest;
};

/** @internal */
export type BatchGenerateContentRequest$Outbound = {
  model: string;
  GeminiBatchGenerateContentRequest: GeminiBatchGenerateContentRequest$Outbound;
};

/** @internal */
export const BatchGenerateContentRequest$outboundSchema: z.ZodMiniType<
  BatchGenerateContentRequest$Outbound,
  BatchGenerateContentRequest
> = z.pipe(
  z.object({
    model: z.string(),
    geminiBatchGenerateContentRequest:
      GeminiBatchGenerateContentRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      geminiBatchGenerateContentRequest: "GeminiBatchGenerateContentRequest",
    });
  }),
);

export function batchGenerateContentRequestToJSON(
  batchGenerateContentRequest: BatchGenerateContentRequest,
): string {
  return JSON.stringify(
    BatchGenerateContentRequest$outboundSchema.parse(
      batchGenerateContentRequest,
    ),
  );
}
