/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ChatCompletionStreamDelta,
  ChatCompletionStreamDelta$inboundSchema,
} from "./chatcompletionstreamdelta.js";

export const ChatCompletionStreamChoiceFinishReason = {
  Stop: "stop",
  Length: "length",
  ToolCalls: "tool_calls",
  ContentFilter: "content_filter",
} as const;
export type ChatCompletionStreamChoiceFinishReason = OpenEnum<
  typeof ChatCompletionStreamChoiceFinishReason
>;

export type ChatCompletionStreamChoiceLogprobs = {};

export type ChatCompletionStreamChoice = {
  index: number;
  delta: ChatCompletionStreamDelta;
  finishReason?: ChatCompletionStreamChoiceFinishReason | null | undefined;
  logprobs?: ChatCompletionStreamChoiceLogprobs | undefined;
};

/** @internal */
export const ChatCompletionStreamChoiceFinishReason$inboundSchema:
  z.ZodMiniType<ChatCompletionStreamChoiceFinishReason, unknown> = openEnums
    .inboundSchema(ChatCompletionStreamChoiceFinishReason);

/** @internal */
export const ChatCompletionStreamChoiceLogprobs$inboundSchema: z.ZodMiniType<
  ChatCompletionStreamChoiceLogprobs,
  unknown
> = z.object({});

export function chatCompletionStreamChoiceLogprobsFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletionStreamChoiceLogprobs, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ChatCompletionStreamChoiceLogprobs$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletionStreamChoiceLogprobs' from JSON`,
  );
}

/** @internal */
export const ChatCompletionStreamChoice$inboundSchema: z.ZodMiniType<
  ChatCompletionStreamChoice,
  unknown
> = z.pipe(
  z.object({
    index: types.number(),
    delta: ChatCompletionStreamDelta$inboundSchema,
    finish_reason: z.optional(
      z.nullable(ChatCompletionStreamChoiceFinishReason$inboundSchema),
    ),
    logprobs: types.optional(
      z.lazy(() => ChatCompletionStreamChoiceLogprobs$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "finish_reason": "finishReason",
    });
  }),
);

export function chatCompletionStreamChoiceFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletionStreamChoice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatCompletionStreamChoice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletionStreamChoice' from JSON`,
  );
}
