/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ChatCompletionChoice,
  ChatCompletionChoice$inboundSchema,
} from "./chatcompletionchoice.js";
import { Usage, Usage$inboundSchema } from "./usage.js";

export type ChatCompletionResponse = {
  id: string;
  object: "chat.completion";
  created: number;
  model: string;
  choices: Array<ChatCompletionChoice>;
  usage?: Usage | undefined;
  systemFingerprint?: string | undefined;
};

/** @internal */
export const ChatCompletionResponse$inboundSchema: z.ZodMiniType<
  ChatCompletionResponse,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    object: types.literal("chat.completion"),
    created: types.number(),
    model: types.string(),
    choices: z.array(ChatCompletionChoice$inboundSchema),
    usage: types.optional(Usage$inboundSchema),
    system_fingerprint: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "system_fingerprint": "systemFingerprint",
    });
  }),
);

export function chatCompletionResponseFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatCompletionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletionResponse' from JSON`,
  );
}
