/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ChatCompletionStreamChoice,
  ChatCompletionStreamChoice$inboundSchema,
} from "./chatcompletionstreamchoice.js";
import { Usage, Usage$inboundSchema } from "./usage.js";

/**
 * Chat completion chunk event (data payload for SSE stream)
 */
export type ChatCompletionStreamEvent = {
  id: string;
  object: "chat.completion.chunk";
  /**
   * Unix timestamp
   */
  created: number;
  model: string;
  /**
   * Array of completion choices. May be empty in the final chunk when only usage is returned.
   */
  choices: Array<ChatCompletionStreamChoice>;
  systemFingerprint?: string | undefined;
  usage?: Usage | undefined;
};

/** @internal */
export const ChatCompletionStreamEvent$inboundSchema: z.ZodMiniType<
  ChatCompletionStreamEvent,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    object: types.literal("chat.completion.chunk"),
    created: types.number(),
    model: types.string(),
    choices: z.array(ChatCompletionStreamChoice$inboundSchema),
    system_fingerprint: types.optional(types.string()),
    usage: types.optional(Usage$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "system_fingerprint": "systemFingerprint",
    });
  }),
);

export function chatCompletionStreamEventFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletionStreamEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatCompletionStreamEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletionStreamEvent' from JSON`,
  );
}
