/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { Message, Message$inboundSchema } from "./message.js";

export const FinishReason = {
  Stop: "stop",
  Length: "length",
  ToolCalls: "tool_calls",
  ContentFilter: "content_filter",
} as const;
export type FinishReason = OpenEnum<typeof FinishReason>;

export type Logprobs = {};

export type ChatCompletionChoice = {
  index: number;
  /**
   * Message object. Note: Different API endpoints have different field requirements and support.
   *
   * @remarks
   *
   * **Field support:**
   * - /v1/chat/completions: Supports all fields (tool_calls, tool_call_id, etc.)
   * - /v1/responses: Only supports basic fields (role, content, name); does not support tool_calls and tool_call_id
   *
   * **content field requirements:**
   * - /v1/chat/completions: When tool_calls is present, content can be omitted or null
   * - /v1/responses: content field is always required and cannot be null; tool_calls field is not supported
   */
  message: Message;
  finishReason: FinishReason;
  logprobs?: Logprobs | undefined;
};

/** @internal */
export const FinishReason$inboundSchema: z.ZodMiniType<FinishReason, unknown> =
  openEnums.inboundSchema(FinishReason);

/** @internal */
export const Logprobs$inboundSchema: z.ZodMiniType<Logprobs, unknown> = z
  .object({});

export function logprobsFromJSON(
  jsonString: string,
): SafeParseResult<Logprobs, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Logprobs$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Logprobs' from JSON`,
  );
}

/** @internal */
export const ChatCompletionChoice$inboundSchema: z.ZodMiniType<
  ChatCompletionChoice,
  unknown
> = z.pipe(
  z.object({
    index: types.number(),
    message: Message$inboundSchema,
    finish_reason: FinishReason$inboundSchema,
    logprobs: types.optional(z.lazy(() => Logprobs$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "finish_reason": "finishReason",
    });
  }),
);

export function chatCompletionChoiceFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletionChoice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatCompletionChoice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletionChoice' from JSON`,
  );
}
