/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { ToolCall, ToolCall$inboundSchema } from "./toolcall.js";

export const ChatCompletionStreamDeltaRole = {
  System: "system",
  User: "user",
  Assistant: "assistant",
} as const;
export type ChatCompletionStreamDeltaRole = OpenEnum<
  typeof ChatCompletionStreamDeltaRole
>;

export type ChatCompletionStreamDelta = {
  role?: ChatCompletionStreamDeltaRole | undefined;
  content?: string | undefined;
  toolCalls?: Array<ToolCall> | undefined;
  reasoningContent?: string | undefined;
};

/** @internal */
export const ChatCompletionStreamDeltaRole$inboundSchema: z.ZodMiniType<
  ChatCompletionStreamDeltaRole,
  unknown
> = openEnums.inboundSchema(ChatCompletionStreamDeltaRole);

/** @internal */
export const ChatCompletionStreamDelta$inboundSchema: z.ZodMiniType<
  ChatCompletionStreamDelta,
  unknown
> = z.pipe(
  z.object({
    role: types.optional(ChatCompletionStreamDeltaRole$inboundSchema),
    content: types.optional(types.string()),
    tool_calls: types.optional(z.array(ToolCall$inboundSchema)),
    reasoning_content: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "tool_calls": "toolCalls",
      "reasoning_content": "reasoningContent",
    });
  }),
);

export function chatCompletionStreamDeltaFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletionStreamDelta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatCompletionStreamDelta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletionStreamDelta' from JSON`,
  );
}
