/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { smartUnion } from "../types/smartUnion.js";

export type CompletionRequestStop = string | Array<string>;

export type CompletionRequest = {
  /**
   * Model name
   */
  model: string;
  /**
   * Prompt text
   */
  prompt: string;
  /**
   * Generate multiple results and return the best one
   */
  bestOf?: number | undefined;
  /**
   * Whether to echo the prompt
   */
  echo?: boolean | undefined;
  frequencyPenalty?: number | undefined;
  logitBias?: { [k: string]: number } | undefined;
  maxTokens?: number | undefined;
  n?: number | undefined;
  presencePenalty?: number | undefined;
  seed?: number | undefined;
  stop?: string | Array<string> | undefined;
  stream?: boolean | undefined;
  temperature?: number | undefined;
  topP?: number | undefined;
  user?: string | undefined;
};

/** @internal */
export type CompletionRequestStop$Outbound = string | Array<string>;

/** @internal */
export const CompletionRequestStop$outboundSchema: z.ZodMiniType<
  CompletionRequestStop$Outbound,
  CompletionRequestStop
> = smartUnion([z.string(), z.array(z.string())]);

export function completionRequestStopToJSON(
  completionRequestStop: CompletionRequestStop,
): string {
  return JSON.stringify(
    CompletionRequestStop$outboundSchema.parse(completionRequestStop),
  );
}

/** @internal */
export type CompletionRequest$Outbound = {
  model: string;
  prompt: string;
  best_of?: number | undefined;
  echo: boolean;
  frequency_penalty: number;
  logit_bias?: { [k: string]: number } | undefined;
  max_tokens?: number | undefined;
  n: number;
  presence_penalty: number;
  seed?: number | undefined;
  stop?: string | Array<string> | undefined;
  stream: boolean;
  temperature: number;
  top_p: number;
  user?: string | undefined;
};

/** @internal */
export const CompletionRequest$outboundSchema: z.ZodMiniType<
  CompletionRequest$Outbound,
  CompletionRequest
> = z.pipe(
  z.object({
    model: z.string(),
    prompt: z.string(),
    bestOf: z.optional(z.int()),
    echo: z._default(z.boolean(), false),
    frequencyPenalty: z._default(z.number(), 0),
    logitBias: z.optional(z.record(z.string(), z.number())),
    maxTokens: z.optional(z.int()),
    n: z._default(z.int(), 1),
    presencePenalty: z._default(z.number(), 0),
    seed: z.optional(z.int()),
    stop: z.optional(smartUnion([z.string(), z.array(z.string())])),
    stream: z._default(z.boolean(), false),
    temperature: z._default(z.number(), 1),
    topP: z._default(z.number(), 1),
    user: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      bestOf: "best_of",
      frequencyPenalty: "frequency_penalty",
      logitBias: "logit_bias",
      maxTokens: "max_tokens",
      presencePenalty: "presence_penalty",
      topP: "top_p",
    });
  }),
);

export function completionRequestToJSON(
  completionRequest: CompletionRequest,
): string {
  return JSON.stringify(
    CompletionRequest$outboundSchema.parse(completionRequest),
  );
}
