/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

export type CompletionStreamChoiceLogprobs = {};

export const CompletionStreamChoiceFinishReason = {
  Stop: "stop",
  Length: "length",
  ContentFilter: "content_filter",
} as const;
export type CompletionStreamChoiceFinishReason = OpenEnum<
  typeof CompletionStreamChoiceFinishReason
>;

export type CompletionStreamChoice = {
  text: string;
  index: number;
  logprobs?: CompletionStreamChoiceLogprobs | null | undefined;
  finishReason?: CompletionStreamChoiceFinishReason | null | undefined;
};

/** @internal */
export const CompletionStreamChoiceLogprobs$inboundSchema: z.ZodMiniType<
  CompletionStreamChoiceLogprobs,
  unknown
> = z.object({});

export function completionStreamChoiceLogprobsFromJSON(
  jsonString: string,
): SafeParseResult<CompletionStreamChoiceLogprobs, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CompletionStreamChoiceLogprobs$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompletionStreamChoiceLogprobs' from JSON`,
  );
}

/** @internal */
export const CompletionStreamChoiceFinishReason$inboundSchema: z.ZodMiniType<
  CompletionStreamChoiceFinishReason,
  unknown
> = openEnums.inboundSchema(CompletionStreamChoiceFinishReason);

/** @internal */
export const CompletionStreamChoice$inboundSchema: z.ZodMiniType<
  CompletionStreamChoice,
  unknown
> = z.pipe(
  z.object({
    text: types.string(),
    index: types.number(),
    logprobs: z.optional(
      z.nullable(z.lazy(() => CompletionStreamChoiceLogprobs$inboundSchema)),
    ),
    finish_reason: z.optional(
      z.nullable(CompletionStreamChoiceFinishReason$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "finish_reason": "finishReason",
    });
  }),
);

export function completionStreamChoiceFromJSON(
  jsonString: string,
): SafeParseResult<CompletionStreamChoice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CompletionStreamChoice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompletionStreamChoice' from JSON`,
  );
}
