/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  CompletionStreamChoice,
  CompletionStreamChoice$inboundSchema,
} from "./completionstreamchoice.js";

/**
 * Completion stream event (data payload for SSE stream)
 */
export type CompletionStreamEvent = {
  id: string;
  object: "completion";
  /**
   * Unix timestamp
   */
  created: number;
  model: string;
  choices: Array<CompletionStreamChoice>;
  systemFingerprint?: string | undefined;
  /**
   * Obfuscation token (server-specific field)
   */
  obfuscation?: string | undefined;
};

/** @internal */
export const CompletionStreamEvent$inboundSchema: z.ZodMiniType<
  CompletionStreamEvent,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    object: types.literal("completion"),
    created: types.number(),
    model: types.string(),
    choices: z.array(CompletionStreamChoice$inboundSchema),
    system_fingerprint: types.optional(types.string()),
    obfuscation: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "system_fingerprint": "systemFingerprint",
    });
  }),
);

export function completionStreamEventFromJSON(
  jsonString: string,
): SafeParseResult<CompletionStreamEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CompletionStreamEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompletionStreamEvent' from JSON`,
  );
}
