/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

export type CompletionChoiceLogprobs = {};

export const CompletionChoiceFinishReason = {
  Stop: "stop",
  Length: "length",
  ContentFilter: "content_filter",
} as const;
export type CompletionChoiceFinishReason = OpenEnum<
  typeof CompletionChoiceFinishReason
>;

export type CompletionChoice = {
  text: string;
  index: number;
  logprobs?: CompletionChoiceLogprobs | null | undefined;
  finishReason: CompletionChoiceFinishReason;
};

/** @internal */
export const CompletionChoiceLogprobs$inboundSchema: z.ZodMiniType<
  CompletionChoiceLogprobs,
  unknown
> = z.object({});

export function completionChoiceLogprobsFromJSON(
  jsonString: string,
): SafeParseResult<CompletionChoiceLogprobs, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CompletionChoiceLogprobs$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompletionChoiceLogprobs' from JSON`,
  );
}

/** @internal */
export const CompletionChoiceFinishReason$inboundSchema: z.ZodMiniType<
  CompletionChoiceFinishReason,
  unknown
> = openEnums.inboundSchema(CompletionChoiceFinishReason);

/** @internal */
export const CompletionChoice$inboundSchema: z.ZodMiniType<
  CompletionChoice,
  unknown
> = z.pipe(
  z.object({
    text: types.string(),
    index: types.number(),
    logprobs: z.optional(
      z.nullable(z.lazy(() => CompletionChoiceLogprobs$inboundSchema)),
    ),
    finish_reason: CompletionChoiceFinishReason$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "finish_reason": "finishReason",
    });
  }),
);

export function completionChoiceFromJSON(
  jsonString: string,
): SafeParseResult<CompletionChoice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CompletionChoice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompletionChoice' from JSON`,
  );
}
