/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  CompletionChoice,
  CompletionChoice$inboundSchema,
} from "./completionchoice.js";
import { Usage, Usage$inboundSchema } from "./usage.js";

export type CompletionResponse = {
  id: string;
  object: "completion";
  created: number;
  model: string;
  choices: Array<CompletionChoice>;
  usage?: Usage | undefined;
};

/** @internal */
export const CompletionResponse$inboundSchema: z.ZodMiniType<
  CompletionResponse,
  unknown
> = z.object({
  id: types.string(),
  object: types.literal("completion"),
  created: types.number(),
  model: types.string(),
  choices: z.array(CompletionChoice$inboundSchema),
  usage: types.optional(Usage$inboundSchema),
});

export function completionResponseFromJSON(
  jsonString: string,
): SafeParseResult<CompletionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CompletionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompletionResponse' from JSON`,
  );
}
