/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { EventStream } from "../lib/event-streams.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import {
  ResponseObject,
  ResponseObject$inboundSchema,
} from "./responseobject.js";
import {
  ResponseStreamEvent,
  ResponseStreamEvent$inboundSchema,
} from "./responsestreamevent.js";

/**
 * Successful response
 */
export type CreateResponseResponseBody = {
  /**
   * Response stream event (data payload for SSE stream)
   */
  data: ResponseStreamEvent;
  id?: string | undefined;
  event?: string | undefined;
  retry?: number | undefined;
};

export type CreateResponseResponse =
  | ResponseObject
  | EventStream<ResponseStreamEvent>;

/** @internal */
export const CreateResponseResponseBody$inboundSchema: z.ZodMiniType<
  CreateResponseResponseBody,
  unknown
> = z.object({
  data: z.pipe(
    z.pipe(
      z.string(),
      z.transform((v, ctx) => {
        try {
          return JSON.parse(v);
        } catch (err) {
          ctx.issues.push({
            input: v,
            code: "custom",
            message: `malformed json: ${err}`,
          });
          return z.NEVER;
        }
      }),
    ),
    ResponseStreamEvent$inboundSchema,
  ),
  id: types.optional(types.string()),
  event: types.optional(types.string()),
  retry: types.optional(types.number()),
});

export function createResponseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateResponseResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateResponseResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateResponseResponseBody' from JSON`,
  );
}

/** @internal */
export const CreateResponseResponse$inboundSchema: z.ZodMiniType<
  CreateResponseResponse,
  unknown
> = smartUnion([
  ResponseObject$inboundSchema,
  z.pipe(
    z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
    z.transform(stream => {
      return new EventStream(stream, rawEvent => {
        if (rawEvent.data === "[DONE]") return { done: true };
        return {
          value: z.parse(
            z.lazy(() => CreateResponseResponseBody$inboundSchema),
            rawEvent,
          )?.data,
        };
      });
    }),
  ),
]);

export function createResponseResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateResponseResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateResponseResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateResponseResponse' from JSON`,
  );
}
