/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type CreateProxyRequestRequest = {
  /**
   * Channel ID
   */
  channelid: string;
  /**
   * Target path
   */
  target: string;
  requestBody?: { [k: string]: any } | undefined;
};

/** @internal */
export type CreateProxyRequestRequest$Outbound = {
  channelid: string;
  target: string;
  RequestBody?: { [k: string]: any } | undefined;
};

/** @internal */
export const CreateProxyRequestRequest$outboundSchema: z.ZodMiniType<
  CreateProxyRequestRequest$Outbound,
  CreateProxyRequestRequest
> = z.pipe(
  z.object({
    channelid: z.string(),
    target: z.string(),
    requestBody: z.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      requestBody: "RequestBody",
    });
  }),
);

export function createProxyRequestRequestToJSON(
  createProxyRequestRequest: CreateProxyRequestRequest,
): string {
  return JSON.stringify(
    CreateProxyRequestRequest$outboundSchema.parse(createProxyRequestRequest),
  );
}
