/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { EventStream } from "../lib/event-streams.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import {
  ImageGenerationResponse,
  ImageGenerationResponse$inboundSchema,
} from "./imagegenerationresponse.js";
import {
  ImageGenerationStreamEvent,
  ImageGenerationStreamEvent$inboundSchema,
} from "./imagegenerationstreamevent.js";

/**
 * Successful response
 */
export type CreateImageGenerationResponseBody = {
  data: ImageGenerationStreamEvent;
  id?: string | undefined;
  event?: string | undefined;
  retry?: number | undefined;
};

export type CreateImageGenerationResponse =
  | ImageGenerationResponse
  | EventStream<ImageGenerationStreamEvent>;

/** @internal */
export const CreateImageGenerationResponseBody$inboundSchema: z.ZodMiniType<
  CreateImageGenerationResponseBody,
  unknown
> = z.object({
  data: z.pipe(
    z.pipe(
      z.string(),
      z.transform((v, ctx) => {
        try {
          return JSON.parse(v);
        } catch (err) {
          ctx.issues.push({
            input: v,
            code: "custom",
            message: `malformed json: ${err}`,
          });
          return z.NEVER;
        }
      }),
    ),
    ImageGenerationStreamEvent$inboundSchema,
  ),
  id: types.optional(types.string()),
  event: types.optional(types.string()),
  retry: types.optional(types.number()),
});

export function createImageGenerationResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateImageGenerationResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateImageGenerationResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateImageGenerationResponseBody' from JSON`,
  );
}

/** @internal */
export const CreateImageGenerationResponse$inboundSchema: z.ZodMiniType<
  CreateImageGenerationResponse,
  unknown
> = smartUnion([
  ImageGenerationResponse$inboundSchema,
  z.pipe(
    z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
    z.transform(stream => {
      return new EventStream(stream, rawEvent => {
        if (rawEvent.data === "[DONE]") return { done: true, value: undefined };
        return {
          done: false,
          value: z.parse(
            z.lazy(() => CreateImageGenerationResponseBody$inboundSchema),
            rawEvent,
          )?.data,
        };
      });
    }),
  ),
]);

export function createImageGenerationResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateImageGenerationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateImageGenerationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateImageGenerationResponse' from JSON`,
  );
}
