/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { EventStream } from "../lib/event-streams.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import {
  CompletionResponse,
  CompletionResponse$inboundSchema,
} from "./completionresponse.js";
import {
  CompletionStreamEvent,
  CompletionStreamEvent$inboundSchema,
} from "./completionstreamevent.js";

/**
 * Successful response
 */
export type CreateCompletionResponseBody = {
  /**
   * Completion stream event (data payload for SSE stream)
   */
  data: CompletionStreamEvent;
  id?: string | undefined;
  event?: string | undefined;
  retry?: number | undefined;
};

export type CreateCompletionResponse =
  | CompletionResponse
  | EventStream<CompletionStreamEvent>;

/** @internal */
export const CreateCompletionResponseBody$inboundSchema: z.ZodMiniType<
  CreateCompletionResponseBody,
  unknown
> = z.object({
  data: z.pipe(
    z.pipe(
      z.string(),
      z.transform((v, ctx) => {
        try {
          return JSON.parse(v);
        } catch (err) {
          ctx.issues.push({
            input: v,
            code: "custom",
            message: `malformed json: ${err}`,
          });
          return z.NEVER;
        }
      }),
    ),
    CompletionStreamEvent$inboundSchema,
  ),
  id: types.optional(types.string()),
  event: types.optional(types.string()),
  retry: types.optional(types.number()),
});

export function createCompletionResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateCompletionResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateCompletionResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateCompletionResponseBody' from JSON`,
  );
}

/** @internal */
export const CreateCompletionResponse$inboundSchema: z.ZodMiniType<
  CreateCompletionResponse,
  unknown
> = smartUnion([
  CompletionResponse$inboundSchema,
  z.pipe(
    z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
    z.transform(stream => {
      return new EventStream(stream, rawEvent => {
        if (rawEvent.data === "[DONE]") return { done: true };
        return {
          value: z.parse(
            z.lazy(() => CreateCompletionResponseBody$inboundSchema),
            rawEvent,
          )?.data,
        };
      });
    }),
  ),
]);

export function createCompletionResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateCompletionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateCompletionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateCompletionResponse' from JSON`,
  );
}
