/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { EventStream } from "../lib/event-streams.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import {
  AnthropicMessageResponse,
  AnthropicMessageResponse$inboundSchema,
} from "./anthropicmessageresponse.js";
import {
  AnthropicStreamEvent,
  AnthropicStreamEvent$inboundSchema,
} from "./anthropicstreamevent.js";

/**
 * Successful response
 */
export type CreateMessageResponseBody = {
  data: AnthropicStreamEvent;
  id?: string | undefined;
  event?: string | undefined;
  retry?: number | undefined;
};

export type CreateMessageResponse =
  | AnthropicMessageResponse
  | EventStream<AnthropicStreamEvent>;

/** @internal */
export const CreateMessageResponseBody$inboundSchema: z.ZodMiniType<
  CreateMessageResponseBody,
  unknown
> = z.object({
  data: z.pipe(
    z.pipe(
      z.string(),
      z.transform((v, ctx) => {
        try {
          return JSON.parse(v);
        } catch (err) {
          ctx.issues.push({
            input: v,
            code: "custom",
            message: `malformed json: ${err}`,
          });
          return z.NEVER;
        }
      }),
    ),
    AnthropicStreamEvent$inboundSchema,
  ),
  id: types.optional(types.string()),
  event: types.optional(types.string()),
  retry: types.optional(types.number()),
});

export function createMessageResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateMessageResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateMessageResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateMessageResponseBody' from JSON`,
  );
}

/** @internal */
export const CreateMessageResponse$inboundSchema: z.ZodMiniType<
  CreateMessageResponse,
  unknown
> = smartUnion([
  AnthropicMessageResponse$inboundSchema,
  z.pipe(
    z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
    z.transform(stream => {
      return new EventStream(stream, rawEvent => {
        return {
          value: z.parse(
            z.lazy(() => CreateMessageResponseBody$inboundSchema),
            rawEvent,
          )?.data,
        };
      });
    }),
  ),
]);

export function createMessageResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateMessageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateMessageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateMessageResponse' from JSON`,
  );
}
