/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { smartUnion } from "../types/smartUnion.js";

export type CreateAudioSpeechResponse =
  | ReadableStream<Uint8Array>
  | ReadableStream<Uint8Array>
  | ReadableStream<Uint8Array>
  | ReadableStream<Uint8Array>
  | ReadableStream<Uint8Array>
  | ReadableStream<Uint8Array>;

/** @internal */
export const CreateAudioSpeechResponse$inboundSchema: z.ZodMiniType<
  CreateAudioSpeechResponse,
  unknown
> = smartUnion([
  z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
  z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
  z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
  z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
  z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
  z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
]);

export function createAudioSpeechResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateAudioSpeechResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateAudioSpeechResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateAudioSpeechResponse' from JSON`,
  );
}
