/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import {
  AudioTranscriptionResponse,
  AudioTranscriptionResponse$inboundSchema,
} from "./audiotranscriptionresponse.js";

export type CreateAudioTranscriptionResponse =
  | AudioTranscriptionResponse
  | string
  | string
  | string;

/** @internal */
export const CreateAudioTranscriptionResponse$inboundSchema: z.ZodMiniType<
  CreateAudioTranscriptionResponse,
  unknown
> = smartUnion([
  AudioTranscriptionResponse$inboundSchema,
  types.string(),
  types.string(),
  types.string(),
]);

export function createAudioTranscriptionResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateAudioTranscriptionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateAudioTranscriptionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateAudioTranscriptionResponse' from JSON`,
  );
}
