/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import {
  AudioTranslationResponse,
  AudioTranslationResponse$inboundSchema,
} from "./audiotranslationresponse.js";

export type CreateAudioTranslationResponse = AudioTranslationResponse | string;

/** @internal */
export const CreateAudioTranslationResponse$inboundSchema: z.ZodMiniType<
  CreateAudioTranslationResponse,
  unknown
> = smartUnion([AudioTranslationResponse$inboundSchema, types.string()]);

export function createAudioTranslationResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateAudioTranslationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateAudioTranslationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateAudioTranslationResponse' from JSON`,
  );
}
