/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  EngineEmbeddingRequest,
  EngineEmbeddingRequest$Outbound,
  EngineEmbeddingRequest$outboundSchema,
} from "./engineembeddingrequest.js";

export type CreateEngineEmbeddingRequest = {
  /**
   * Engine model name
   */
  model: string;
  engineEmbeddingRequest: EngineEmbeddingRequest;
};

/** @internal */
export type CreateEngineEmbeddingRequest$Outbound = {
  model: string;
  EngineEmbeddingRequest: EngineEmbeddingRequest$Outbound;
};

/** @internal */
export const CreateEngineEmbeddingRequest$outboundSchema: z.ZodMiniType<
  CreateEngineEmbeddingRequest$Outbound,
  CreateEngineEmbeddingRequest
> = z.pipe(
  z.object({
    model: z.string(),
    engineEmbeddingRequest: EngineEmbeddingRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      engineEmbeddingRequest: "EngineEmbeddingRequest",
    });
  }),
);

export function createEngineEmbeddingRequestToJSON(
  createEngineEmbeddingRequest: CreateEngineEmbeddingRequest,
): string {
  return JSON.stringify(
    CreateEngineEmbeddingRequest$outboundSchema.parse(
      createEngineEmbeddingRequest,
    ),
  );
}
