/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { EventStream } from "../lib/event-streams.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import {
  ChatCompletionResponse,
  ChatCompletionResponse$inboundSchema,
} from "./chatcompletionresponse.js";
import {
  ChatCompletionStreamEvent,
  ChatCompletionStreamEvent$inboundSchema,
} from "./chatcompletionstreamevent.js";

/**
 * Successful response
 */
export type CreateChatCompletionResponseBody = {
  /**
   * Chat completion chunk event (data payload for SSE stream)
   */
  data: ChatCompletionStreamEvent;
  id?: string | undefined;
  event?: string | undefined;
  retry?: number | undefined;
};

export type CreateChatCompletionResponse =
  | ChatCompletionResponse
  | EventStream<ChatCompletionStreamEvent>;

/** @internal */
export const CreateChatCompletionResponseBody$inboundSchema: z.ZodMiniType<
  CreateChatCompletionResponseBody,
  unknown
> = z.object({
  data: z.pipe(
    z.pipe(
      z.string(),
      z.transform((v, ctx) => {
        try {
          return JSON.parse(v);
        } catch (err) {
          ctx.issues.push({
            input: v,
            code: "custom",
            message: `malformed json: ${err}`,
          });
          return z.NEVER;
        }
      }),
    ),
    ChatCompletionStreamEvent$inboundSchema,
  ),
  id: types.optional(types.string()),
  event: types.optional(types.string()),
  retry: types.optional(types.number()),
});

export function createChatCompletionResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateChatCompletionResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateChatCompletionResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateChatCompletionResponseBody' from JSON`,
  );
}

/** @internal */
export const CreateChatCompletionResponse$inboundSchema: z.ZodMiniType<
  CreateChatCompletionResponse,
  unknown
> = smartUnion([
  ChatCompletionResponse$inboundSchema,
  z.pipe(
    z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
    z.transform(stream => {
      return new EventStream(stream, rawEvent => {
        if (rawEvent.data === "[DONE]") return { done: true };
        return {
          value: z.parse(
            z.lazy(() => CreateChatCompletionResponseBody$inboundSchema),
            rawEvent,
          )?.data,
        };
      });
    }),
  ),
]);

export function createChatCompletionResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateChatCompletionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateChatCompletionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateChatCompletionResponse' from JSON`,
  );
}
