/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type EditRequest = {
  /**
   * Model name
   */
  model: string;
  /**
   * Input text to edit
   */
  input?: string | undefined;
  /**
   * Edit instruction
   */
  instruction: string;
  n?: number | undefined;
  temperature?: number | undefined;
  topP?: number | undefined;
};

/** @internal */
export type EditRequest$Outbound = {
  model: string;
  input: string;
  instruction: string;
  n: number;
  temperature: number;
  top_p: number;
};

/** @internal */
export const EditRequest$outboundSchema: z.ZodMiniType<
  EditRequest$Outbound,
  EditRequest
> = z.pipe(
  z.object({
    model: z.string(),
    input: z._default(z.string(), ""),
    instruction: z.string(),
    n: z._default(z.int(), 1),
    temperature: z._default(z.number(), 1),
    topP: z._default(z.number(), 1),
  }),
  z.transform((v) => {
    return remap$(v, {
      topP: "top_p",
    });
  }),
);

export function editRequestToJSON(editRequest: EditRequest): string {
  return JSON.stringify(EditRequest$outboundSchema.parse(editRequest));
}
