/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { EditChoice, EditChoice$inboundSchema } from "./editchoice.js";
import { Usage, Usage$inboundSchema } from "./usage.js";

export type EditResponse = {
  object: "edit";
  created: number;
  choices: Array<EditChoice>;
  usage: Usage;
};

/** @internal */
export const EditResponse$inboundSchema: z.ZodMiniType<EditResponse, unknown> =
  z.object({
    object: types.literal("edit"),
    created: types.number(),
    choices: z.array(EditChoice$inboundSchema),
    usage: Usage$inboundSchema,
  });

export function editResponseFromJSON(
  jsonString: string,
): SafeParseResult<EditResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EditResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EditResponse' from JSON`,
  );
}
