/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

export type EmbeddingObject = {
  object: "embedding";
  /**
   * Embedding vector
   */
  embedding: Array<number>;
  index: number;
};

/** @internal */
export const EmbeddingObject$inboundSchema: z.ZodMiniType<
  EmbeddingObject,
  unknown
> = z.object({
  object: types.literal("embedding"),
  embedding: z.array(types.number()),
  index: types.number(),
});

export function embeddingObjectFromJSON(
  jsonString: string,
): SafeParseResult<EmbeddingObject, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmbeddingObject$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmbeddingObject' from JSON`,
  );
}
