/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import { smartUnion } from "../types/smartUnion.js";

/**
 * Input text
 */
export type EmbeddingRequestInput = string | Array<string>;

export const EncodingFormat = {
  Float: "float",
  Base64: "base64",
} as const;
export type EncodingFormat = ClosedEnum<typeof EncodingFormat>;

export type EmbeddingRequest = {
  /**
   * Model name
   */
  model: string;
  /**
   * Input text
   */
  input: string | Array<string>;
  encodingFormat?: EncodingFormat | undefined;
  /**
   * Output dimensions
   */
  dimensions?: number | undefined;
  user?: string | undefined;
};

/** @internal */
export type EmbeddingRequestInput$Outbound = string | Array<string>;

/** @internal */
export const EmbeddingRequestInput$outboundSchema: z.ZodMiniType<
  EmbeddingRequestInput$Outbound,
  EmbeddingRequestInput
> = smartUnion([z.string(), z.array(z.string())]);

export function embeddingRequestInputToJSON(
  embeddingRequestInput: EmbeddingRequestInput,
): string {
  return JSON.stringify(
    EmbeddingRequestInput$outboundSchema.parse(embeddingRequestInput),
  );
}

/** @internal */
export const EncodingFormat$outboundSchema: z.ZodMiniEnum<
  typeof EncodingFormat
> = z.enum(EncodingFormat);

/** @internal */
export type EmbeddingRequest$Outbound = {
  model: string;
  input: string | Array<string>;
  encoding_format: string;
  dimensions?: number | undefined;
  user?: string | undefined;
};

/** @internal */
export const EmbeddingRequest$outboundSchema: z.ZodMiniType<
  EmbeddingRequest$Outbound,
  EmbeddingRequest
> = z.pipe(
  z.object({
    model: z.string(),
    input: smartUnion([z.string(), z.array(z.string())]),
    encodingFormat: z._default(EncodingFormat$outboundSchema, "float"),
    dimensions: z.optional(z.int()),
    user: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      encodingFormat: "encoding_format",
    });
  }),
);

export function embeddingRequestToJSON(
  embeddingRequest: EmbeddingRequest,
): string {
  return JSON.stringify(
    EmbeddingRequest$outboundSchema.parse(embeddingRequest),
  );
}
