/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  EmbeddingObject,
  EmbeddingObject$inboundSchema,
} from "./embeddingobject.js";
import { Usage, Usage$inboundSchema } from "./usage.js";

export type EmbeddingResponse = {
  object: "list";
  data: Array<EmbeddingObject>;
  model: string;
  usage: Usage;
};

/** @internal */
export const EmbeddingResponse$inboundSchema: z.ZodMiniType<
  EmbeddingResponse,
  unknown
> = z.object({
  object: types.literal("list"),
  data: z.array(EmbeddingObject$inboundSchema),
  model: types.string(),
  usage: Usage$inboundSchema,
});

export function embeddingResponseFromJSON(
  jsonString: string,
): SafeParseResult<EmbeddingResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmbeddingResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmbeddingResponse' from JSON`,
  );
}
