/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  GeminiEmbedContentRequest,
  GeminiEmbedContentRequest$Outbound,
  GeminiEmbedContentRequest$outboundSchema,
} from "./geminiembedcontentrequest.js";

export type EmbedContentRequest = {
  /**
   * The embedding model resource name.
   *
   * @remarks
   * Examples: models/text-embedding-005, models/embedding-001
   */
  model: string;
  geminiEmbedContentRequest: GeminiEmbedContentRequest;
};

/** @internal */
export type EmbedContentRequest$Outbound = {
  model: string;
  GeminiEmbedContentRequest: GeminiEmbedContentRequest$Outbound;
};

/** @internal */
export const EmbedContentRequest$outboundSchema: z.ZodMiniType<
  EmbedContentRequest$Outbound,
  EmbedContentRequest
> = z.pipe(
  z.object({
    model: z.string(),
    geminiEmbedContentRequest: GeminiEmbedContentRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      geminiEmbedContentRequest: "GeminiEmbedContentRequest",
    });
  }),
);

export function embedContentRequestToJSON(
  embedContentRequest: EmbedContentRequest,
): string {
  return JSON.stringify(
    EmbedContentRequest$outboundSchema.parse(embedContentRequest),
  );
}
