/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import { smartUnion } from "../types/smartUnion.js";

/**
 * Input text
 */
export type EngineEmbeddingRequestInput = string | Array<string>;

export const EngineEmbeddingRequestEncodingFormat = {
  Float: "float",
  Base64: "base64",
} as const;
export type EngineEmbeddingRequestEncodingFormat = ClosedEnum<
  typeof EngineEmbeddingRequestEncodingFormat
>;

export type EngineEmbeddingRequest = {
  /**
   * Input text
   */
  input: string | Array<string>;
  encodingFormat?: EngineEmbeddingRequestEncodingFormat | undefined;
  /**
   * Output dimensions
   */
  dimensions?: number | undefined;
  user?: string | undefined;
};

/** @internal */
export type EngineEmbeddingRequestInput$Outbound = string | Array<string>;

/** @internal */
export const EngineEmbeddingRequestInput$outboundSchema: z.ZodMiniType<
  EngineEmbeddingRequestInput$Outbound,
  EngineEmbeddingRequestInput
> = smartUnion([z.string(), z.array(z.string())]);

export function engineEmbeddingRequestInputToJSON(
  engineEmbeddingRequestInput: EngineEmbeddingRequestInput,
): string {
  return JSON.stringify(
    EngineEmbeddingRequestInput$outboundSchema.parse(
      engineEmbeddingRequestInput,
    ),
  );
}

/** @internal */
export const EngineEmbeddingRequestEncodingFormat$outboundSchema: z.ZodMiniEnum<
  typeof EngineEmbeddingRequestEncodingFormat
> = z.enum(EngineEmbeddingRequestEncodingFormat);

/** @internal */
export type EngineEmbeddingRequest$Outbound = {
  input: string | Array<string>;
  encoding_format: string;
  dimensions?: number | undefined;
  user?: string | undefined;
};

/** @internal */
export const EngineEmbeddingRequest$outboundSchema: z.ZodMiniType<
  EngineEmbeddingRequest$Outbound,
  EngineEmbeddingRequest
> = z.pipe(
  z.object({
    input: smartUnion([z.string(), z.array(z.string())]),
    encodingFormat: z._default(
      EngineEmbeddingRequestEncodingFormat$outboundSchema,
      "float",
    ),
    dimensions: z.optional(z.int()),
    user: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      encodingFormat: "encoding_format",
    });
  }),
);

export function engineEmbeddingRequestToJSON(
  engineEmbeddingRequest: EngineEmbeddingRequest,
): string {
  return JSON.stringify(
    EngineEmbeddingRequest$outboundSchema.parse(engineEmbeddingRequest),
  );
}
