/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

export type FunctionCall = {
  name: string;
  arguments?: string | undefined;
};

/** @internal */
export const FunctionCall$inboundSchema: z.ZodMiniType<FunctionCall, unknown> =
  z.object({
    name: types.string(),
    arguments: types.optional(types.string()),
  });
/** @internal */
export type FunctionCall$Outbound = {
  name: string;
  arguments?: string | undefined;
};

/** @internal */
export const FunctionCall$outboundSchema: z.ZodMiniType<
  FunctionCall$Outbound,
  FunctionCall
> = z.object({
  name: z.string(),
  arguments: z.optional(z.string()),
});

export function functionCallToJSON(functionCall: FunctionCall): string {
  return JSON.stringify(FunctionCall$outboundSchema.parse(functionCall));
}
export function functionCallFromJSON(
  jsonString: string,
): SafeParseResult<FunctionCall, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FunctionCall$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FunctionCall' from JSON`,
  );
}
