/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  GeminiGenerateContentRequest,
  GeminiGenerateContentRequest$inboundSchema,
  GeminiGenerateContentRequest$Outbound,
  GeminiGenerateContentRequest$outboundSchema,
} from "./geminigeneratecontentrequest.js";

/**
 * Single request in a batch with optional metadata
 */
export type GeminiBatchRequestItem = {
  /**
   * Request to generate content
   */
  request: GeminiGenerateContentRequest;
  /**
   * Optional metadata for tracking this request
   */
  metadata?: { [k: string]: string } | undefined;
};

/** @internal */
export const GeminiBatchRequestItem$inboundSchema: z.ZodMiniType<
  GeminiBatchRequestItem,
  unknown
> = z.object({
  request: GeminiGenerateContentRequest$inboundSchema,
  metadata: types.optional(z.record(z.string(), types.string())),
});
/** @internal */
export type GeminiBatchRequestItem$Outbound = {
  request: GeminiGenerateContentRequest$Outbound;
  metadata?: { [k: string]: string } | undefined;
};

/** @internal */
export const GeminiBatchRequestItem$outboundSchema: z.ZodMiniType<
  GeminiBatchRequestItem$Outbound,
  GeminiBatchRequestItem
> = z.object({
  request: GeminiGenerateContentRequest$outboundSchema,
  metadata: z.optional(z.record(z.string(), z.string())),
});

export function geminiBatchRequestItemToJSON(
  geminiBatchRequestItem: GeminiBatchRequestItem,
): string {
  return JSON.stringify(
    GeminiBatchRequestItem$outboundSchema.parse(geminiBatchRequestItem),
  );
}
export function geminiBatchRequestItemFromJSON(
  jsonString: string,
): SafeParseResult<GeminiBatchRequestItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiBatchRequestItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiBatchRequestItem' from JSON`,
  );
}
