/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

/**
 * Token usage metadata
 */
export type GeminiUsageMetadata = {
  /**
   * Number of tokens in the prompt
   */
  promptTokenCount?: number | undefined;
  /**
   * Total tokens across all candidates
   */
  candidatesTokenCount?: number | undefined;
  /**
   * Total token count
   */
  totalTokenCount?: number | undefined;
  /**
   * Cached content token count
   */
  cachedContentTokenCount?: number | undefined;
};

/** @internal */
export const GeminiUsageMetadata$inboundSchema: z.ZodMiniType<
  GeminiUsageMetadata,
  unknown
> = z.object({
  promptTokenCount: types.optional(types.number()),
  candidatesTokenCount: types.optional(types.number()),
  totalTokenCount: types.optional(types.number()),
  cachedContentTokenCount: types.optional(types.number()),
});

export function geminiUsageMetadataFromJSON(
  jsonString: string,
): SafeParseResult<GeminiUsageMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiUsageMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiUsageMetadata' from JSON`,
  );
}
