/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  GeminiInlineResponseItem,
  GeminiInlineResponseItem$inboundSchema,
} from "./geminiinlineresponseitem.js";

/**
 * Output configuration containing results
 */
export type GeminiOutputConfig = {
  /**
   * Inline response results (for inline input)
   */
  inlinedResponses?: Array<GeminiInlineResponseItem> | undefined;
  /**
   * Output JSONL file name (for file input)
   */
  fileName?: string | undefined;
};

/** @internal */
export const GeminiOutputConfig$inboundSchema: z.ZodMiniType<
  GeminiOutputConfig,
  unknown
> = z.pipe(
  z.object({
    inlined_responses: types.optional(
      z.array(GeminiInlineResponseItem$inboundSchema),
    ),
    file_name: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "inlined_responses": "inlinedResponses",
      "file_name": "fileName",
    });
  }),
);

export function geminiOutputConfigFromJSON(
  jsonString: string,
): SafeParseResult<GeminiOutputConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiOutputConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiOutputConfig' from JSON`,
  );
}
