/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

/**
 * OpenAPI 3.0 schema object for parameters
 */
export type GeminiFunctionDeclarationParameters = {};

/**
 * Function declaration for tool use
 */
export type GeminiFunctionDeclaration = {
  /**
   * Function name
   */
  name: string;
  /**
   * Function description
   */
  description: string;
  /**
   * OpenAPI 3.0 schema object for parameters
   */
  parameters?: GeminiFunctionDeclarationParameters | undefined;
};

/** @internal */
export const GeminiFunctionDeclarationParameters$inboundSchema: z.ZodMiniType<
  GeminiFunctionDeclarationParameters,
  unknown
> = z.object({});
/** @internal */
export type GeminiFunctionDeclarationParameters$Outbound = {};

/** @internal */
export const GeminiFunctionDeclarationParameters$outboundSchema: z.ZodMiniType<
  GeminiFunctionDeclarationParameters$Outbound,
  GeminiFunctionDeclarationParameters
> = z.object({});

export function geminiFunctionDeclarationParametersToJSON(
  geminiFunctionDeclarationParameters: GeminiFunctionDeclarationParameters,
): string {
  return JSON.stringify(
    GeminiFunctionDeclarationParameters$outboundSchema.parse(
      geminiFunctionDeclarationParameters,
    ),
  );
}
export function geminiFunctionDeclarationParametersFromJSON(
  jsonString: string,
): SafeParseResult<GeminiFunctionDeclarationParameters, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GeminiFunctionDeclarationParameters$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiFunctionDeclarationParameters' from JSON`,
  );
}

/** @internal */
export const GeminiFunctionDeclaration$inboundSchema: z.ZodMiniType<
  GeminiFunctionDeclaration,
  unknown
> = z.object({
  name: types.string(),
  description: types.string(),
  parameters: types.optional(
    z.lazy(() => GeminiFunctionDeclarationParameters$inboundSchema),
  ),
});
/** @internal */
export type GeminiFunctionDeclaration$Outbound = {
  name: string;
  description: string;
  parameters?: GeminiFunctionDeclarationParameters$Outbound | undefined;
};

/** @internal */
export const GeminiFunctionDeclaration$outboundSchema: z.ZodMiniType<
  GeminiFunctionDeclaration$Outbound,
  GeminiFunctionDeclaration
> = z.object({
  name: z.string(),
  description: z.string(),
  parameters: z.optional(
    z.lazy(() => GeminiFunctionDeclarationParameters$outboundSchema),
  ),
});

export function geminiFunctionDeclarationToJSON(
  geminiFunctionDeclaration: GeminiFunctionDeclaration,
): string {
  return JSON.stringify(
    GeminiFunctionDeclaration$outboundSchema.parse(geminiFunctionDeclaration),
  );
}
export function geminiFunctionDeclarationFromJSON(
  jsonString: string,
): SafeParseResult<GeminiFunctionDeclaration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiFunctionDeclaration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiFunctionDeclaration' from JSON`,
  );
}
