/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  GeminiContent,
  GeminiContent$inboundSchema,
  GeminiContent$Outbound,
  GeminiContent$outboundSchema,
} from "./geminicontent.js";
import {
  GeminiGenerationConfig,
  GeminiGenerationConfig$inboundSchema,
  GeminiGenerationConfig$Outbound,
  GeminiGenerationConfig$outboundSchema,
} from "./geminigenerationconfig.js";
import {
  GeminiSafetySetting,
  GeminiSafetySetting$inboundSchema,
  GeminiSafetySetting$Outbound,
  GeminiSafetySetting$outboundSchema,
} from "./geminisafetysetting.js";
import {
  GeminiSystemInstruction,
  GeminiSystemInstruction$inboundSchema,
  GeminiSystemInstruction$Outbound,
  GeminiSystemInstruction$outboundSchema,
} from "./geminisysteminstruction.js";
import {
  GeminiTool,
  GeminiTool$inboundSchema,
  GeminiTool$Outbound,
  GeminiTool$outboundSchema,
} from "./geminitool.js";
import {
  GeminiToolConfig,
  GeminiToolConfig$inboundSchema,
  GeminiToolConfig$Outbound,
  GeminiToolConfig$outboundSchema,
} from "./geminitoolconfig.js";

/**
 * Request to generate content
 */
export type GeminiGenerateContentRequest = {
  /**
   * Content array (conversation history)
   */
  contents: Array<GeminiContent>;
  /**
   * Configuration options for model generation
   */
  generationConfig?: GeminiGenerationConfig | undefined;
  safetySettings?: Array<GeminiSafetySetting> | undefined;
  /**
   * System instruction to guide model behavior
   */
  systemInstruction?: GeminiSystemInstruction | undefined;
  tools?: Array<GeminiTool> | undefined;
  /**
   * Tool configuration
   */
  toolConfig?: GeminiToolConfig | undefined;
  /**
   * Cached content reference
   */
  cachedContent?: string | undefined;
};

/** @internal */
export const GeminiGenerateContentRequest$inboundSchema: z.ZodMiniType<
  GeminiGenerateContentRequest,
  unknown
> = z.object({
  contents: z.array(GeminiContent$inboundSchema),
  generationConfig: types.optional(GeminiGenerationConfig$inboundSchema),
  safetySettings: types.optional(z.array(GeminiSafetySetting$inboundSchema)),
  systemInstruction: types.optional(GeminiSystemInstruction$inboundSchema),
  tools: types.optional(z.array(GeminiTool$inboundSchema)),
  toolConfig: types.optional(GeminiToolConfig$inboundSchema),
  cachedContent: types.optional(types.string()),
});
/** @internal */
export type GeminiGenerateContentRequest$Outbound = {
  contents: Array<GeminiContent$Outbound>;
  generationConfig?: GeminiGenerationConfig$Outbound | undefined;
  safetySettings?: Array<GeminiSafetySetting$Outbound> | undefined;
  systemInstruction?: GeminiSystemInstruction$Outbound | undefined;
  tools?: Array<GeminiTool$Outbound> | undefined;
  toolConfig?: GeminiToolConfig$Outbound | undefined;
  cachedContent?: string | undefined;
};

/** @internal */
export const GeminiGenerateContentRequest$outboundSchema: z.ZodMiniType<
  GeminiGenerateContentRequest$Outbound,
  GeminiGenerateContentRequest
> = z.object({
  contents: z.array(GeminiContent$outboundSchema),
  generationConfig: z.optional(GeminiGenerationConfig$outboundSchema),
  safetySettings: z.optional(z.array(GeminiSafetySetting$outboundSchema)),
  systemInstruction: z.optional(GeminiSystemInstruction$outboundSchema),
  tools: z.optional(z.array(GeminiTool$outboundSchema)),
  toolConfig: z.optional(GeminiToolConfig$outboundSchema),
  cachedContent: z.optional(z.string()),
});

export function geminiGenerateContentRequestToJSON(
  geminiGenerateContentRequest: GeminiGenerateContentRequest,
): string {
  return JSON.stringify(
    GeminiGenerateContentRequest$outboundSchema.parse(
      geminiGenerateContentRequest,
    ),
  );
}
export function geminiGenerateContentRequestFromJSON(
  jsonString: string,
): SafeParseResult<GeminiGenerateContentRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiGenerateContentRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiGenerateContentRequest' from JSON`,
  );
}
