/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  GeminiGenerateContentResponse,
  GeminiGenerateContentResponse$inboundSchema,
} from "./geminigeneratecontentresponse.js";

/**
 * Error if this request failed
 */
export type GeminiInlineResponseItemError = {
  code?: number | undefined;
  message?: string | undefined;
  status?: string | undefined;
};

/**
 * Single response item in batch results
 */
export type GeminiInlineResponseItem = {
  /**
   * Response from generateContent or streamGenerateContent
   */
  response?: GeminiGenerateContentResponse | undefined;
  /**
   * Error if this request failed
   */
  error?: GeminiInlineResponseItemError | undefined;
};

/** @internal */
export const GeminiInlineResponseItemError$inboundSchema: z.ZodMiniType<
  GeminiInlineResponseItemError,
  unknown
> = z.object({
  code: types.optional(types.number()),
  message: types.optional(types.string()),
  status: types.optional(types.string()),
});

export function geminiInlineResponseItemErrorFromJSON(
  jsonString: string,
): SafeParseResult<GeminiInlineResponseItemError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiInlineResponseItemError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiInlineResponseItemError' from JSON`,
  );
}

/** @internal */
export const GeminiInlineResponseItem$inboundSchema: z.ZodMiniType<
  GeminiInlineResponseItem,
  unknown
> = z.object({
  response: types.optional(GeminiGenerateContentResponse$inboundSchema),
  error: types.optional(
    z.lazy(() => GeminiInlineResponseItemError$inboundSchema),
  ),
});

export function geminiInlineResponseItemFromJSON(
  jsonString: string,
): SafeParseResult<GeminiInlineResponseItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiInlineResponseItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiInlineResponseItem' from JSON`,
  );
}
