/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

/**
 * Embedding vector
 */
export type GeminiEmbedding = {
  /**
   * Embedding values (floats)
   */
  values: Array<number>;
};

/** @internal */
export const GeminiEmbedding$inboundSchema: z.ZodMiniType<
  GeminiEmbedding,
  unknown
> = z.object({
  values: z.array(types.number()),
});

export function geminiEmbeddingFromJSON(
  jsonString: string,
): SafeParseResult<GeminiEmbedding, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiEmbedding$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiEmbedding' from JSON`,
  );
}
