/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  GeminiBatchRequestItem,
  GeminiBatchRequestItem$inboundSchema,
  GeminiBatchRequestItem$Outbound,
  GeminiBatchRequestItem$outboundSchema,
} from "./geminibatchrequestitem.js";

/**
 * Inline requests configuration (max 20MB)
 */
export type GeminiInlineRequestConfig = {
  /**
   * Array of request items
   */
  requests: Array<GeminiBatchRequestItem>;
};

/** @internal */
export const GeminiInlineRequestConfig$inboundSchema: z.ZodMiniType<
  GeminiInlineRequestConfig,
  unknown
> = z.object({
  requests: z.array(GeminiBatchRequestItem$inboundSchema),
});
/** @internal */
export type GeminiInlineRequestConfig$Outbound = {
  requests: Array<GeminiBatchRequestItem$Outbound>;
};

/** @internal */
export const GeminiInlineRequestConfig$outboundSchema: z.ZodMiniType<
  GeminiInlineRequestConfig$Outbound,
  GeminiInlineRequestConfig
> = z.object({
  requests: z.array(GeminiBatchRequestItem$outboundSchema),
});

export function geminiInlineRequestConfigToJSON(
  geminiInlineRequestConfig: GeminiInlineRequestConfig,
): string {
  return JSON.stringify(
    GeminiInlineRequestConfig$outboundSchema.parse(geminiInlineRequestConfig),
  );
}
export function geminiInlineRequestConfigFromJSON(
  jsonString: string,
): SafeParseResult<GeminiInlineRequestConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiInlineRequestConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiInlineRequestConfig' from JSON`,
  );
}
