/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  GeminiFunctionDeclaration,
  GeminiFunctionDeclaration$inboundSchema,
  GeminiFunctionDeclaration$Outbound,
  GeminiFunctionDeclaration$outboundSchema,
} from "./geminifunctiondeclaration.js";

/**
 * Tool that the model can use
 */
export type GeminiTool = {
  functionDeclarations?: Array<GeminiFunctionDeclaration> | undefined;
};

/** @internal */
export const GeminiTool$inboundSchema: z.ZodMiniType<GeminiTool, unknown> = z
  .object({
    functionDeclarations: types.optional(
      z.array(GeminiFunctionDeclaration$inboundSchema),
    ),
  });
/** @internal */
export type GeminiTool$Outbound = {
  functionDeclarations?: Array<GeminiFunctionDeclaration$Outbound> | undefined;
};

/** @internal */
export const GeminiTool$outboundSchema: z.ZodMiniType<
  GeminiTool$Outbound,
  GeminiTool
> = z.object({
  functionDeclarations: z.optional(
    z.array(GeminiFunctionDeclaration$outboundSchema),
  ),
});

export function geminiToolToJSON(geminiTool: GeminiTool): string {
  return JSON.stringify(GeminiTool$outboundSchema.parse(geminiTool));
}
export function geminiToolFromJSON(
  jsonString: string,
): SafeParseResult<GeminiTool, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiTool$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiTool' from JSON`,
  );
}
