/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import {
  GeminiFileData,
  GeminiFileData$inboundSchema,
  GeminiFileData$Outbound,
  GeminiFileData$outboundSchema,
} from "./geminifiledata.js";
import {
  GeminiInlineData,
  GeminiInlineData$inboundSchema,
  GeminiInlineData$Outbound,
  GeminiInlineData$outboundSchema,
} from "./geminiinlinedata.js";

export type ResponseT = {};

/**
 * Response from function execution
 */
export type FunctionResponse = {
  name?: string | undefined;
  response?: ResponseT | undefined;
};

export type Five = {
  /**
   * Response from function execution
   */
  functionResponse: FunctionResponse;
};

export type Args = {};

/**
 * Function call from the model
 */
export type GeminiPartFunctionCall = {
  name?: string | undefined;
  args?: Args | undefined;
};

export type Four = {
  /**
   * Function call from the model
   */
  functionCall: GeminiPartFunctionCall;
};

export type Three = {
  /**
   * URI-based data reference
   */
  fileData: GeminiFileData;
};

export type GeminiPart2 = {
  /**
   * Content data inline in the request (base64 encoded)
   */
  inlineData: GeminiInlineData;
};

export type GeminiPart1 = {
  /**
   * Text content
   */
  text: string;
};

/**
 * A single part of content that can be text, inline data, file data, or function call
 */
export type GeminiPart = GeminiPart1 | GeminiPart2 | Three | Four | Five;

/** @internal */
export const ResponseT$inboundSchema: z.ZodMiniType<ResponseT, unknown> = z
  .object({});
/** @internal */
export type ResponseT$Outbound = {};

/** @internal */
export const ResponseT$outboundSchema: z.ZodMiniType<
  ResponseT$Outbound,
  ResponseT
> = z.object({});

export function responseToJSON(responseT: ResponseT): string {
  return JSON.stringify(ResponseT$outboundSchema.parse(responseT));
}
export function responseFromJSON(
  jsonString: string,
): SafeParseResult<ResponseT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseT' from JSON`,
  );
}

/** @internal */
export const FunctionResponse$inboundSchema: z.ZodMiniType<
  FunctionResponse,
  unknown
> = z.object({
  name: types.optional(types.string()),
  response: types.optional(z.lazy(() => ResponseT$inboundSchema)),
});
/** @internal */
export type FunctionResponse$Outbound = {
  name?: string | undefined;
  response?: ResponseT$Outbound | undefined;
};

/** @internal */
export const FunctionResponse$outboundSchema: z.ZodMiniType<
  FunctionResponse$Outbound,
  FunctionResponse
> = z.object({
  name: z.optional(z.string()),
  response: z.optional(z.lazy(() => ResponseT$outboundSchema)),
});

export function functionResponseToJSON(
  functionResponse: FunctionResponse,
): string {
  return JSON.stringify(
    FunctionResponse$outboundSchema.parse(functionResponse),
  );
}
export function functionResponseFromJSON(
  jsonString: string,
): SafeParseResult<FunctionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FunctionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FunctionResponse' from JSON`,
  );
}

/** @internal */
export const Five$inboundSchema: z.ZodMiniType<Five, unknown> = z.object({
  functionResponse: z.lazy(() => FunctionResponse$inboundSchema),
});
/** @internal */
export type Five$Outbound = {
  functionResponse: FunctionResponse$Outbound;
};

/** @internal */
export const Five$outboundSchema: z.ZodMiniType<Five$Outbound, Five> = z.object(
  {
    functionResponse: z.lazy(() => FunctionResponse$outboundSchema),
  },
);

export function fiveToJSON(five: Five): string {
  return JSON.stringify(Five$outboundSchema.parse(five));
}
export function fiveFromJSON(
  jsonString: string,
): SafeParseResult<Five, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Five$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Five' from JSON`,
  );
}

/** @internal */
export const Args$inboundSchema: z.ZodMiniType<Args, unknown> = z.object({});
/** @internal */
export type Args$Outbound = {};

/** @internal */
export const Args$outboundSchema: z.ZodMiniType<Args$Outbound, Args> = z.object(
  {},
);

export function argsToJSON(args: Args): string {
  return JSON.stringify(Args$outboundSchema.parse(args));
}
export function argsFromJSON(
  jsonString: string,
): SafeParseResult<Args, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Args$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Args' from JSON`,
  );
}

/** @internal */
export const GeminiPartFunctionCall$inboundSchema: z.ZodMiniType<
  GeminiPartFunctionCall,
  unknown
> = z.object({
  name: types.optional(types.string()),
  args: types.optional(z.lazy(() => Args$inboundSchema)),
});
/** @internal */
export type GeminiPartFunctionCall$Outbound = {
  name?: string | undefined;
  args?: Args$Outbound | undefined;
};

/** @internal */
export const GeminiPartFunctionCall$outboundSchema: z.ZodMiniType<
  GeminiPartFunctionCall$Outbound,
  GeminiPartFunctionCall
> = z.object({
  name: z.optional(z.string()),
  args: z.optional(z.lazy(() => Args$outboundSchema)),
});

export function geminiPartFunctionCallToJSON(
  geminiPartFunctionCall: GeminiPartFunctionCall,
): string {
  return JSON.stringify(
    GeminiPartFunctionCall$outboundSchema.parse(geminiPartFunctionCall),
  );
}
export function geminiPartFunctionCallFromJSON(
  jsonString: string,
): SafeParseResult<GeminiPartFunctionCall, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiPartFunctionCall$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiPartFunctionCall' from JSON`,
  );
}

/** @internal */
export const Four$inboundSchema: z.ZodMiniType<Four, unknown> = z.object({
  functionCall: z.lazy(() => GeminiPartFunctionCall$inboundSchema),
});
/** @internal */
export type Four$Outbound = {
  functionCall: GeminiPartFunctionCall$Outbound;
};

/** @internal */
export const Four$outboundSchema: z.ZodMiniType<Four$Outbound, Four> = z.object(
  {
    functionCall: z.lazy(() => GeminiPartFunctionCall$outboundSchema),
  },
);

export function fourToJSON(four: Four): string {
  return JSON.stringify(Four$outboundSchema.parse(four));
}
export function fourFromJSON(
  jsonString: string,
): SafeParseResult<Four, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Four$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Four' from JSON`,
  );
}

/** @internal */
export const Three$inboundSchema: z.ZodMiniType<Three, unknown> = z.pipe(
  z.object({
    file_data: GeminiFileData$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "file_data": "fileData",
    });
  }),
);
/** @internal */
export type Three$Outbound = {
  file_data: GeminiFileData$Outbound;
};

/** @internal */
export const Three$outboundSchema: z.ZodMiniType<Three$Outbound, Three> = z
  .pipe(
    z.object({
      fileData: GeminiFileData$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        fileData: "file_data",
      });
    }),
  );

export function threeToJSON(three: Three): string {
  return JSON.stringify(Three$outboundSchema.parse(three));
}
export function threeFromJSON(
  jsonString: string,
): SafeParseResult<Three, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Three$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Three' from JSON`,
  );
}

/** @internal */
export const GeminiPart2$inboundSchema: z.ZodMiniType<GeminiPart2, unknown> = z
  .pipe(
    z.object({
      inline_data: GeminiInlineData$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "inline_data": "inlineData",
      });
    }),
  );
/** @internal */
export type GeminiPart2$Outbound = {
  inline_data: GeminiInlineData$Outbound;
};

/** @internal */
export const GeminiPart2$outboundSchema: z.ZodMiniType<
  GeminiPart2$Outbound,
  GeminiPart2
> = z.pipe(
  z.object({
    inlineData: GeminiInlineData$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      inlineData: "inline_data",
    });
  }),
);

export function geminiPart2ToJSON(geminiPart2: GeminiPart2): string {
  return JSON.stringify(GeminiPart2$outboundSchema.parse(geminiPart2));
}
export function geminiPart2FromJSON(
  jsonString: string,
): SafeParseResult<GeminiPart2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiPart2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiPart2' from JSON`,
  );
}

/** @internal */
export const GeminiPart1$inboundSchema: z.ZodMiniType<GeminiPart1, unknown> = z
  .object({
    text: types.string(),
  });
/** @internal */
export type GeminiPart1$Outbound = {
  text: string;
};

/** @internal */
export const GeminiPart1$outboundSchema: z.ZodMiniType<
  GeminiPart1$Outbound,
  GeminiPart1
> = z.object({
  text: z.string(),
});

export function geminiPart1ToJSON(geminiPart1: GeminiPart1): string {
  return JSON.stringify(GeminiPart1$outboundSchema.parse(geminiPart1));
}
export function geminiPart1FromJSON(
  jsonString: string,
): SafeParseResult<GeminiPart1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiPart1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiPart1' from JSON`,
  );
}

/** @internal */
export const GeminiPart$inboundSchema: z.ZodMiniType<GeminiPart, unknown> =
  smartUnion([
    z.lazy(() => GeminiPart1$inboundSchema),
    z.lazy(() => GeminiPart2$inboundSchema),
    z.lazy(() => Three$inboundSchema),
    z.lazy(() => Four$inboundSchema),
    z.lazy(() => Five$inboundSchema),
  ]);
/** @internal */
export type GeminiPart$Outbound =
  | GeminiPart1$Outbound
  | GeminiPart2$Outbound
  | Three$Outbound
  | Four$Outbound
  | Five$Outbound;

/** @internal */
export const GeminiPart$outboundSchema: z.ZodMiniType<
  GeminiPart$Outbound,
  GeminiPart
> = smartUnion([
  z.lazy(() => GeminiPart1$outboundSchema),
  z.lazy(() => GeminiPart2$outboundSchema),
  z.lazy(() => Three$outboundSchema),
  z.lazy(() => Four$outboundSchema),
  z.lazy(() => Five$outboundSchema),
]);

export function geminiPartToJSON(geminiPart: GeminiPart): string {
  return JSON.stringify(GeminiPart$outboundSchema.parse(geminiPart));
}
export function geminiPartFromJSON(
  jsonString: string,
): SafeParseResult<GeminiPart, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiPart$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiPart' from JSON`,
  );
}
