/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  GeminiSafetyRating,
  GeminiSafetyRating$inboundSchema,
} from "./geminisafetyrating.js";

/**
 * Reason for blocking the prompt
 */
export const BlockReason = {
  BlockReasonUnspecified: "BLOCK_REASON_UNSPECIFIED",
  Safety: "SAFETY",
  Other: "OTHER",
} as const;
/**
 * Reason for blocking the prompt
 */
export type BlockReason = OpenEnum<typeof BlockReason>;

/**
 * Feedback about the prompt
 */
export type GeminiPromptFeedback = {
  /**
   * Reason for blocking the prompt
   */
  blockReason?: BlockReason | undefined;
  safetyRatings?: Array<GeminiSafetyRating> | undefined;
};

/** @internal */
export const BlockReason$inboundSchema: z.ZodMiniType<BlockReason, unknown> =
  openEnums.inboundSchema(BlockReason);

/** @internal */
export const GeminiPromptFeedback$inboundSchema: z.ZodMiniType<
  GeminiPromptFeedback,
  unknown
> = z.object({
  blockReason: types.optional(BlockReason$inboundSchema),
  safetyRatings: types.optional(z.array(GeminiSafetyRating$inboundSchema)),
});

export function geminiPromptFeedbackFromJSON(
  jsonString: string,
): SafeParseResult<GeminiPromptFeedback, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiPromptFeedback$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiPromptFeedback' from JSON`,
  );
}
