/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

export type Parts = {
  text?: string | undefined;
};

/**
 * System instruction to guide model behavior
 */
export type GeminiSystemInstruction = {
  parts: Array<Parts>;
};

/** @internal */
export const Parts$inboundSchema: z.ZodMiniType<Parts, unknown> = z.object({
  text: types.optional(types.string()),
});
/** @internal */
export type Parts$Outbound = {
  text?: string | undefined;
};

/** @internal */
export const Parts$outboundSchema: z.ZodMiniType<Parts$Outbound, Parts> = z
  .object({
    text: z.optional(z.string()),
  });

export function partsToJSON(parts: Parts): string {
  return JSON.stringify(Parts$outboundSchema.parse(parts));
}
export function partsFromJSON(
  jsonString: string,
): SafeParseResult<Parts, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Parts$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Parts' from JSON`,
  );
}

/** @internal */
export const GeminiSystemInstruction$inboundSchema: z.ZodMiniType<
  GeminiSystemInstruction,
  unknown
> = z.object({
  parts: z.array(z.lazy(() => Parts$inboundSchema)),
});
/** @internal */
export type GeminiSystemInstruction$Outbound = {
  parts: Array<Parts$Outbound>;
};

/** @internal */
export const GeminiSystemInstruction$outboundSchema: z.ZodMiniType<
  GeminiSystemInstruction$Outbound,
  GeminiSystemInstruction
> = z.object({
  parts: z.array(z.lazy(() => Parts$outboundSchema)),
});

export function geminiSystemInstructionToJSON(
  geminiSystemInstruction: GeminiSystemInstruction,
): string {
  return JSON.stringify(
    GeminiSystemInstruction$outboundSchema.parse(geminiSystemInstruction),
  );
}
export function geminiSystemInstructionFromJSON(
  jsonString: string,
): SafeParseResult<GeminiSystemInstruction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiSystemInstruction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiSystemInstruction' from JSON`,
  );
}
