/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  GeminiPart,
  GeminiPart$inboundSchema,
  GeminiPart$Outbound,
  GeminiPart$outboundSchema,
} from "./geminipart.js";

/**
 * Role of the content creator
 */
export const GeminiContentRole = {
  User: "user",
  Model: "model",
} as const;
/**
 * Role of the content creator
 */
export type GeminiContentRole = OpenEnum<typeof GeminiContentRole>;

/**
 * Content object containing role and parts
 */
export type GeminiContent = {
  /**
   * Role of the content creator
   */
  role?: GeminiContentRole | undefined;
  /**
   * Ordered parts that make up the content
   */
  parts: Array<GeminiPart>;
};

/** @internal */
export const GeminiContentRole$inboundSchema: z.ZodMiniType<
  GeminiContentRole,
  unknown
> = openEnums.inboundSchema(GeminiContentRole);
/** @internal */
export const GeminiContentRole$outboundSchema: z.ZodMiniType<
  string,
  GeminiContentRole
> = openEnums.outboundSchema(GeminiContentRole);

/** @internal */
export const GeminiContent$inboundSchema: z.ZodMiniType<
  GeminiContent,
  unknown
> = z.object({
  role: types.optional(GeminiContentRole$inboundSchema),
  parts: z.array(GeminiPart$inboundSchema),
});
/** @internal */
export type GeminiContent$Outbound = {
  role?: string | undefined;
  parts: Array<GeminiPart$Outbound>;
};

/** @internal */
export const GeminiContent$outboundSchema: z.ZodMiniType<
  GeminiContent$Outbound,
  GeminiContent
> = z.object({
  role: z.optional(GeminiContentRole$outboundSchema),
  parts: z.array(GeminiPart$outboundSchema),
});

export function geminiContentToJSON(geminiContent: GeminiContent): string {
  return JSON.stringify(GeminiContent$outboundSchema.parse(geminiContent));
}
export function geminiContentFromJSON(
  jsonString: string,
): SafeParseResult<GeminiContent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiContent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiContent' from JSON`,
  );
}
