/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

/**
 * Statistics about batch processing
 */
export type GeminiBatchStats = {
  /**
   * Number of failed requests
   */
  failedRequestCount?: number | undefined;
  /**
   * Number of successful requests
   */
  successfulRequestCount?: number | undefined;
};

/** @internal */
export const GeminiBatchStats$inboundSchema: z.ZodMiniType<
  GeminiBatchStats,
  unknown
> = z.object({
  failedRequestCount: types.optional(types.number()),
  successfulRequestCount: types.optional(types.number()),
});

export function geminiBatchStatsFromJSON(
  jsonString: string,
): SafeParseResult<GeminiBatchStats, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiBatchStats$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiBatchStats' from JSON`,
  );
}
