/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";

/**
 * Harm category to configure
 */
export const Category = {
  HarmCategoryHarassment: "HARM_CATEGORY_HARASSMENT",
  HarmCategoryHateSpeech: "HARM_CATEGORY_HATE_SPEECH",
  HarmCategorySexuallyExplicit: "HARM_CATEGORY_SEXUALLY_EXPLICIT",
  HarmCategoryDangerousContent: "HARM_CATEGORY_DANGEROUS_CONTENT",
} as const;
/**
 * Harm category to configure
 */
export type Category = OpenEnum<typeof Category>;

/**
 * Threshold for blocking content
 */
export const Threshold = {
  BlockNone: "BLOCK_NONE",
  BlockOnlyHigh: "BLOCK_ONLY_HIGH",
  BlockMediumAndAbove: "BLOCK_MEDIUM_AND_ABOVE",
  BlockLowAndAbove: "BLOCK_LOW_AND_ABOVE",
} as const;
/**
 * Threshold for blocking content
 */
export type Threshold = OpenEnum<typeof Threshold>;

/**
 * Safety setting for a specific harm category
 */
export type GeminiSafetySetting = {
  /**
   * Harm category to configure
   */
  category: Category;
  /**
   * Threshold for blocking content
   */
  threshold: Threshold;
};

/** @internal */
export const Category$inboundSchema: z.ZodMiniType<Category, unknown> =
  openEnums.inboundSchema(Category);
/** @internal */
export const Category$outboundSchema: z.ZodMiniType<string, Category> =
  openEnums.outboundSchema(Category);

/** @internal */
export const Threshold$inboundSchema: z.ZodMiniType<Threshold, unknown> =
  openEnums.inboundSchema(Threshold);
/** @internal */
export const Threshold$outboundSchema: z.ZodMiniType<string, Threshold> =
  openEnums.outboundSchema(Threshold);

/** @internal */
export const GeminiSafetySetting$inboundSchema: z.ZodMiniType<
  GeminiSafetySetting,
  unknown
> = z.object({
  category: Category$inboundSchema,
  threshold: Threshold$inboundSchema,
});
/** @internal */
export type GeminiSafetySetting$Outbound = {
  category: string;
  threshold: string;
};

/** @internal */
export const GeminiSafetySetting$outboundSchema: z.ZodMiniType<
  GeminiSafetySetting$Outbound,
  GeminiSafetySetting
> = z.object({
  category: Category$outboundSchema,
  threshold: Threshold$outboundSchema,
});

export function geminiSafetySettingToJSON(
  geminiSafetySetting: GeminiSafetySetting,
): string {
  return JSON.stringify(
    GeminiSafetySetting$outboundSchema.parse(geminiSafetySetting),
  );
}
export function geminiSafetySettingFromJSON(
  jsonString: string,
): SafeParseResult<GeminiSafetySetting, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiSafetySetting$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiSafetySetting' from JSON`,
  );
}
