/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

/**
 * Error information for failed batch job
 */
export type GeminiBatchError = {
  /**
   * Error code
   */
  code?: number | undefined;
  /**
   * Error message
   */
  message?: string | undefined;
  /**
   * Error status
   */
  status?: string | undefined;
};

/** @internal */
export const GeminiBatchError$inboundSchema: z.ZodMiniType<
  GeminiBatchError,
  unknown
> = z.object({
  code: types.optional(types.number()),
  message: types.optional(types.string()),
  status: types.optional(types.string()),
});

export function geminiBatchErrorFromJSON(
  jsonString: string,
): SafeParseResult<GeminiBatchError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiBatchError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiBatchError' from JSON`,
  );
}
