/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

/**
 * URI-based data reference
 */
export type GeminiFileData = {
  /**
   * MIME type of the file
   */
  mimeType: string;
  /**
   * URI of the file (e.g., gs:// or https://)
   */
  fileUri: string;
};

/** @internal */
export const GeminiFileData$inboundSchema: z.ZodMiniType<
  GeminiFileData,
  unknown
> = z.pipe(
  z.object({
    mime_type: types.string(),
    file_uri: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "mime_type": "mimeType",
      "file_uri": "fileUri",
    });
  }),
);
/** @internal */
export type GeminiFileData$Outbound = {
  mime_type: string;
  file_uri: string;
};

/** @internal */
export const GeminiFileData$outboundSchema: z.ZodMiniType<
  GeminiFileData$Outbound,
  GeminiFileData
> = z.pipe(
  z.object({
    mimeType: z.string(),
    fileUri: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      mimeType: "mime_type",
      fileUri: "file_uri",
    });
  }),
);

export function geminiFileDataToJSON(geminiFileData: GeminiFileData): string {
  return JSON.stringify(GeminiFileData$outboundSchema.parse(geminiFileData));
}
export function geminiFileDataFromJSON(
  jsonString: string,
): SafeParseResult<GeminiFileData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiFileData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiFileData' from JSON`,
  );
}
