/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

/**
 * Function calling mode
 */
export const Mode = {
  Auto: "AUTO",
  Any: "ANY",
  None: "NONE",
} as const;
/**
 * Function calling mode
 */
export type Mode = OpenEnum<typeof Mode>;

export type FunctionCallingConfig = {
  /**
   * Function calling mode
   */
  mode?: Mode | undefined;
};

/**
 * Tool configuration
 */
export type GeminiToolConfig = {
  functionCallingConfig?: FunctionCallingConfig | undefined;
};

/** @internal */
export const Mode$inboundSchema: z.ZodMiniType<Mode, unknown> = openEnums
  .inboundSchema(Mode);
/** @internal */
export const Mode$outboundSchema: z.ZodMiniType<string, Mode> = openEnums
  .outboundSchema(Mode);

/** @internal */
export const FunctionCallingConfig$inboundSchema: z.ZodMiniType<
  FunctionCallingConfig,
  unknown
> = z.object({
  mode: types.optional(Mode$inboundSchema),
});
/** @internal */
export type FunctionCallingConfig$Outbound = {
  mode?: string | undefined;
};

/** @internal */
export const FunctionCallingConfig$outboundSchema: z.ZodMiniType<
  FunctionCallingConfig$Outbound,
  FunctionCallingConfig
> = z.object({
  mode: z.optional(Mode$outboundSchema),
});

export function functionCallingConfigToJSON(
  functionCallingConfig: FunctionCallingConfig,
): string {
  return JSON.stringify(
    FunctionCallingConfig$outboundSchema.parse(functionCallingConfig),
  );
}
export function functionCallingConfigFromJSON(
  jsonString: string,
): SafeParseResult<FunctionCallingConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FunctionCallingConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FunctionCallingConfig' from JSON`,
  );
}

/** @internal */
export const GeminiToolConfig$inboundSchema: z.ZodMiniType<
  GeminiToolConfig,
  unknown
> = z.object({
  functionCallingConfig: types.optional(
    z.lazy(() => FunctionCallingConfig$inboundSchema),
  ),
});
/** @internal */
export type GeminiToolConfig$Outbound = {
  functionCallingConfig?: FunctionCallingConfig$Outbound | undefined;
};

/** @internal */
export const GeminiToolConfig$outboundSchema: z.ZodMiniType<
  GeminiToolConfig$Outbound,
  GeminiToolConfig
> = z.object({
  functionCallingConfig: z.optional(
    z.lazy(() => FunctionCallingConfig$outboundSchema),
  ),
});

export function geminiToolConfigToJSON(
  geminiToolConfig: GeminiToolConfig,
): string {
  return JSON.stringify(
    GeminiToolConfig$outboundSchema.parse(geminiToolConfig),
  );
}
export function geminiToolConfigFromJSON(
  jsonString: string,
): SafeParseResult<GeminiToolConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiToolConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiToolConfig' from JSON`,
  );
}
