/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  GeminiCandidate,
  GeminiCandidate$inboundSchema,
} from "./geminicandidate.js";
import {
  GeminiPromptFeedback,
  GeminiPromptFeedback$inboundSchema,
} from "./geminipromptfeedback.js";
import {
  GeminiUsageMetadata,
  GeminiUsageMetadata$inboundSchema,
} from "./geminiusagemetadata.js";

/**
 * Current model operational status
 */
export type ModelStatus = {};

/**
 * Response from generateContent or streamGenerateContent
 */
export type GeminiGenerateContentResponse = {
  candidates?: Array<GeminiCandidate> | undefined;
  /**
   * Feedback about the prompt
   */
  promptFeedback?: GeminiPromptFeedback | undefined;
  /**
   * Token usage metadata
   */
  usageMetadata?: GeminiUsageMetadata | undefined;
  /**
   * Model version used
   */
  modelVersion?: string | undefined;
  /**
   * Unique identifier for this response
   */
  responseId?: string | undefined;
  /**
   * Current model operational status
   */
  modelStatus?: ModelStatus | undefined;
};

/** @internal */
export const ModelStatus$inboundSchema: z.ZodMiniType<ModelStatus, unknown> = z
  .object({});

export function modelStatusFromJSON(
  jsonString: string,
): SafeParseResult<ModelStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelStatus' from JSON`,
  );
}

/** @internal */
export const GeminiGenerateContentResponse$inboundSchema: z.ZodMiniType<
  GeminiGenerateContentResponse,
  unknown
> = z.object({
  candidates: types.optional(z.array(GeminiCandidate$inboundSchema)),
  promptFeedback: types.optional(GeminiPromptFeedback$inboundSchema),
  usageMetadata: types.optional(GeminiUsageMetadata$inboundSchema),
  modelVersion: types.optional(types.string()),
  responseId: types.optional(types.string()),
  modelStatus: types.optional(z.lazy(() => ModelStatus$inboundSchema)),
});

export function geminiGenerateContentResponseFromJSON(
  jsonString: string,
): SafeParseResult<GeminiGenerateContentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiGenerateContentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiGenerateContentResponse' from JSON`,
  );
}
