/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  GeminiInputConfig,
  GeminiInputConfig$Outbound,
  GeminiInputConfig$outboundSchema,
} from "./geminiinputconfig.js";

export type Batch = {
  /**
   * Human-readable name for this batch job
   */
  displayName?: string | undefined;
  /**
   * Input configuration - either inline requests or file reference
   */
  inputConfig: GeminiInputConfig;
};

/**
 * Request to create an async batch generation job
 */
export type GeminiBatchGenerateContentRequest = {
  batch: Batch;
};

/** @internal */
export type Batch$Outbound = {
  display_name?: string | undefined;
  input_config: GeminiInputConfig$Outbound;
};

/** @internal */
export const Batch$outboundSchema: z.ZodMiniType<Batch$Outbound, Batch> = z
  .pipe(
    z.object({
      displayName: z.optional(z.string()),
      inputConfig: GeminiInputConfig$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        displayName: "display_name",
        inputConfig: "input_config",
      });
    }),
  );

export function batchToJSON(batch: Batch): string {
  return JSON.stringify(Batch$outboundSchema.parse(batch));
}

/** @internal */
export type GeminiBatchGenerateContentRequest$Outbound = {
  batch: Batch$Outbound;
};

/** @internal */
export const GeminiBatchGenerateContentRequest$outboundSchema: z.ZodMiniType<
  GeminiBatchGenerateContentRequest$Outbound,
  GeminiBatchGenerateContentRequest
> = z.object({
  batch: z.lazy(() => Batch$outboundSchema),
});

export function geminiBatchGenerateContentRequestToJSON(
  geminiBatchGenerateContentRequest: GeminiBatchGenerateContentRequest,
): string {
  return JSON.stringify(
    GeminiBatchGenerateContentRequest$outboundSchema.parse(
      geminiBatchGenerateContentRequest,
    ),
  );
}
