/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";
import {
  GeminiContent,
  GeminiContent$Outbound,
  GeminiContent$outboundSchema,
} from "./geminicontent.js";

/**
 * Task type for the embedding
 */
export const TaskType = {
  RetrievalQuery: "RETRIEVAL_QUERY",
  RetrievalDocument: "RETRIEVAL_DOCUMENT",
  SemanticSimilarity: "SEMANTIC_SIMILARITY",
  Classification: "CLASSIFICATION",
  Clustering: "CLUSTERING",
  QuestionAnswering: "QUESTION_ANSWERING",
  FactVerification: "FACT_VERIFICATION",
  CodeRetrievalQuery: "CODE_RETRIEVAL_QUERY",
} as const;
/**
 * Task type for the embedding
 */
export type TaskType = ClosedEnum<typeof TaskType>;

/**
 * Request to generate embeddings
 */
export type GeminiEmbedContentRequest = {
  /**
   * Content object containing role and parts
   */
  content: GeminiContent;
  /**
   * Task type for the embedding
   */
  taskType?: TaskType | undefined;
  /**
   * Optional title (for RETRIEVAL_DOCUMENT task type)
   */
  title?: string | undefined;
  /**
   * Reduced dimension for output embedding
   */
  outputDimensionality?: number | undefined;
};

/** @internal */
export const TaskType$outboundSchema: z.ZodMiniEnum<typeof TaskType> = z.enum(
  TaskType,
);

/** @internal */
export type GeminiEmbedContentRequest$Outbound = {
  content: GeminiContent$Outbound;
  taskType?: string | undefined;
  title?: string | undefined;
  outputDimensionality?: number | undefined;
};

/** @internal */
export const GeminiEmbedContentRequest$outboundSchema: z.ZodMiniType<
  GeminiEmbedContentRequest$Outbound,
  GeminiEmbedContentRequest
> = z.object({
  content: GeminiContent$outboundSchema,
  taskType: z.optional(TaskType$outboundSchema),
  title: z.optional(z.string()),
  outputDimensionality: z.optional(z.int()),
});

export function geminiEmbedContentRequestToJSON(
  geminiEmbedContentRequest: GeminiEmbedContentRequest,
): string {
  return JSON.stringify(
    GeminiEmbedContentRequest$outboundSchema.parse(geminiEmbedContentRequest),
  );
}
