/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

/**
 * Content data inline in the request (base64 encoded)
 */
export type GeminiInlineData = {
  /**
   * MIME type of the data (e.g., image/jpeg, image/png, audio/mp3)
   */
  mimeType: string;
  /**
   * Base64 encoded data
   */
  data: string;
};

/** @internal */
export const GeminiInlineData$inboundSchema: z.ZodMiniType<
  GeminiInlineData,
  unknown
> = z.pipe(
  z.object({
    mime_type: types.string(),
    data: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "mime_type": "mimeType",
    });
  }),
);
/** @internal */
export type GeminiInlineData$Outbound = {
  mime_type: string;
  data: string;
};

/** @internal */
export const GeminiInlineData$outboundSchema: z.ZodMiniType<
  GeminiInlineData$Outbound,
  GeminiInlineData
> = z.pipe(
  z.object({
    mimeType: z.string(),
    data: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      mimeType: "mime_type",
    });
  }),
);

export function geminiInlineDataToJSON(
  geminiInlineData: GeminiInlineData,
): string {
  return JSON.stringify(
    GeminiInlineData$outboundSchema.parse(geminiInlineData),
  );
}
export function geminiInlineDataFromJSON(
  jsonString: string,
): SafeParseResult<GeminiInlineData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiInlineData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiInlineData' from JSON`,
  );
}
