/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

/**
 * Output format MIME type
 */
export const ResponseMimeType = {
  TextPlain: "text/plain",
  ApplicationJson: "application/json",
  ImagePng: "image/png",
  ImageJpeg: "image/jpeg",
  ImageWebp: "image/webp",
} as const;
/**
 * Output format MIME type
 */
export type ResponseMimeType = OpenEnum<typeof ResponseMimeType>;

/**
 * Schema for structured output (when responseMimeType is application/json)
 */
export type ResponseSchema = {};

/**
 * Configuration options for model generation
 */
export type GeminiGenerationConfig = {
  /**
   * Controls randomness (0.0-2.0)
   */
  temperature?: number | undefined;
  /**
   * Nucleus sampling threshold
   */
  topP?: number | undefined;
  /**
   * Top-k sampling parameter
   */
  topK?: number | undefined;
  /**
   * Number of response candidates to generate
   */
  candidateCount?: number | undefined;
  /**
   * Maximum number of tokens in the response
   */
  maxOutputTokens?: number | undefined;
  /**
   * Sequences that will stop generation
   */
  stopSequences?: Array<string> | undefined;
  /**
   * Output format MIME type
   */
  responseMimeType?: ResponseMimeType | undefined;
  /**
   * Schema for structured output (when responseMimeType is application/json)
   */
  responseSchema?: ResponseSchema | undefined;
};

/** @internal */
export const ResponseMimeType$inboundSchema: z.ZodMiniType<
  ResponseMimeType,
  unknown
> = openEnums.inboundSchema(ResponseMimeType);
/** @internal */
export const ResponseMimeType$outboundSchema: z.ZodMiniType<
  string,
  ResponseMimeType
> = openEnums.outboundSchema(ResponseMimeType);

/** @internal */
export const ResponseSchema$inboundSchema: z.ZodMiniType<
  ResponseSchema,
  unknown
> = z.object({});
/** @internal */
export type ResponseSchema$Outbound = {};

/** @internal */
export const ResponseSchema$outboundSchema: z.ZodMiniType<
  ResponseSchema$Outbound,
  ResponseSchema
> = z.object({});

export function responseSchemaToJSON(responseSchema: ResponseSchema): string {
  return JSON.stringify(ResponseSchema$outboundSchema.parse(responseSchema));
}
export function responseSchemaFromJSON(
  jsonString: string,
): SafeParseResult<ResponseSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseSchema' from JSON`,
  );
}

/** @internal */
export const GeminiGenerationConfig$inboundSchema: z.ZodMiniType<
  GeminiGenerationConfig,
  unknown
> = z.object({
  temperature: types.optional(types.number()),
  topP: types.optional(types.number()),
  topK: types.optional(types.number()),
  candidateCount: types.optional(types.number()),
  maxOutputTokens: types.optional(types.number()),
  stopSequences: types.optional(z.array(types.string())),
  responseMimeType: types.optional(ResponseMimeType$inboundSchema),
  responseSchema: types.optional(z.lazy(() => ResponseSchema$inboundSchema)),
});
/** @internal */
export type GeminiGenerationConfig$Outbound = {
  temperature?: number | undefined;
  topP?: number | undefined;
  topK?: number | undefined;
  candidateCount?: number | undefined;
  maxOutputTokens?: number | undefined;
  stopSequences?: Array<string> | undefined;
  responseMimeType?: string | undefined;
  responseSchema?: ResponseSchema$Outbound | undefined;
};

/** @internal */
export const GeminiGenerationConfig$outboundSchema: z.ZodMiniType<
  GeminiGenerationConfig$Outbound,
  GeminiGenerationConfig
> = z.object({
  temperature: z.optional(z.number()),
  topP: z.optional(z.number()),
  topK: z.optional(z.int()),
  candidateCount: z.optional(z.int()),
  maxOutputTokens: z.optional(z.int()),
  stopSequences: z.optional(z.array(z.string())),
  responseMimeType: z.optional(ResponseMimeType$outboundSchema),
  responseSchema: z.optional(z.lazy(() => ResponseSchema$outboundSchema)),
});

export function geminiGenerationConfigToJSON(
  geminiGenerationConfig: GeminiGenerationConfig,
): string {
  return JSON.stringify(
    GeminiGenerationConfig$outboundSchema.parse(geminiGenerationConfig),
  );
}
export function geminiGenerationConfigFromJSON(
  jsonString: string,
): SafeParseResult<GeminiGenerationConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiGenerationConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiGenerationConfig' from JSON`,
  );
}
