/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  GeminiBatchError,
  GeminiBatchError$inboundSchema,
} from "./geminibatcherror.js";
import {
  GeminiBatchStats,
  GeminiBatchStats$inboundSchema,
} from "./geminibatchstats.js";
import {
  GeminiInputConfig,
  GeminiInputConfig$inboundSchema,
} from "./geminiinputconfig.js";
import {
  GeminiJobState,
  GeminiJobState$inboundSchema,
} from "./geminijobstate.js";
import {
  GeminiOutputConfig,
  GeminiOutputConfig$inboundSchema,
} from "./geminioutputconfig.js";

/**
 * Response from batch job creation (returns job metadata)
 */
export type GeminiBatchGenerateContentResponse = {
  /**
   * Batch job identifier
   */
  name?: string | undefined;
  /**
   * User-defined label for this batch
   */
  displayName?: string | undefined;
  /**
   * State of the batch job
   */
  state?: GeminiJobState | undefined;
  /**
   * Job creation timestamp
   */
  createTime?: Date | undefined;
  /**
   * Last update timestamp
   */
  updateTime?: Date | undefined;
  /**
   * Input configuration - either inline requests or file reference
   */
  inputConfig?: GeminiInputConfig | undefined;
  /**
   * Output configuration containing results
   */
  outputConfig?: GeminiOutputConfig | undefined;
  /**
   * Error information for failed batch job
   */
  error?: GeminiBatchError | undefined;
  /**
   * Statistics about batch processing
   */
  batchStats?: GeminiBatchStats | undefined;
};

/** @internal */
export const GeminiBatchGenerateContentResponse$inboundSchema: z.ZodMiniType<
  GeminiBatchGenerateContentResponse,
  unknown
> = z.pipe(
  z.object({
    name: types.optional(types.string()),
    display_name: types.optional(types.string()),
    state: types.optional(GeminiJobState$inboundSchema),
    create_time: types.optional(types.date()),
    update_time: types.optional(types.date()),
    input_config: types.optional(GeminiInputConfig$inboundSchema),
    output_config: types.optional(GeminiOutputConfig$inboundSchema),
    error: types.optional(GeminiBatchError$inboundSchema),
    batch_stats: types.optional(GeminiBatchStats$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "display_name": "displayName",
      "create_time": "createTime",
      "update_time": "updateTime",
      "input_config": "inputConfig",
      "output_config": "outputConfig",
      "batch_stats": "batchStats",
    });
  }),
);

export function geminiBatchGenerateContentResponseFromJSON(
  jsonString: string,
): SafeParseResult<GeminiBatchGenerateContentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GeminiBatchGenerateContentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiBatchGenerateContentResponse' from JSON`,
  );
}
