/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  GeminiEmbedding,
  GeminiEmbedding$inboundSchema,
} from "./geminiembedding.js";

/**
 * Response from embedContent
 */
export type GeminiEmbedContentResponse = {
  /**
   * Embedding vector
   */
  embedding: GeminiEmbedding;
};

/** @internal */
export const GeminiEmbedContentResponse$inboundSchema: z.ZodMiniType<
  GeminiEmbedContentResponse,
  unknown
> = z.object({
  embedding: GeminiEmbedding$inboundSchema,
});

export function geminiEmbedContentResponseFromJSON(
  jsonString: string,
): SafeParseResult<GeminiEmbedContentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiEmbedContentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiEmbedContentResponse' from JSON`,
  );
}
