/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

/**
 * Probability of harm
 */
export const Probability = {
  Negligible: "NEGLIGIBLE",
  Low: "LOW",
  Medium: "MEDIUM",
  High: "HIGH",
} as const;
/**
 * Probability of harm
 */
export type Probability = OpenEnum<typeof Probability>;

/**
 * Safety rating for a piece of content
 */
export type GeminiSafetyRating = {
  /**
   * Harm category
   */
  category?: string | undefined;
  /**
   * Probability of harm
   */
  probability?: Probability | undefined;
  /**
   * Whether content was blocked
   */
  blocked?: boolean | undefined;
};

/** @internal */
export const Probability$inboundSchema: z.ZodMiniType<Probability, unknown> =
  openEnums.inboundSchema(Probability);

/** @internal */
export const GeminiSafetyRating$inboundSchema: z.ZodMiniType<
  GeminiSafetyRating,
  unknown
> = z.object({
  category: types.optional(types.string()),
  probability: types.optional(Probability$inboundSchema),
  blocked: types.optional(types.boolean()),
});

export function geminiSafetyRatingFromJSON(
  jsonString: string,
): SafeParseResult<GeminiSafetyRating, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiSafetyRating$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiSafetyRating' from JSON`,
  );
}
