/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { GeminiContent, GeminiContent$inboundSchema } from "./geminicontent.js";
import {
  GeminiSafetyRating,
  GeminiSafetyRating$inboundSchema,
} from "./geminisafetyrating.js";

/**
 * Reason for finishing generation
 */
export const GeminiCandidateFinishReason = {
  Stop: "STOP",
  MaxTokens: "MAX_TOKENS",
  Safety: "SAFETY",
  Recitation: "RECITATION",
  Other: "OTHER",
} as const;
/**
 * Reason for finishing generation
 */
export type GeminiCandidateFinishReason = OpenEnum<
  typeof GeminiCandidateFinishReason
>;

/**
 * Citation information
 */
export type CitationMetadata = {};

/**
 * A response candidate
 */
export type GeminiCandidate = {
  /**
   * Content object containing role and parts
   */
  content?: GeminiContent | undefined;
  /**
   * Reason for finishing generation
   */
  finishReason?: GeminiCandidateFinishReason | undefined;
  safetyRatings?: Array<GeminiSafetyRating> | undefined;
  /**
   * Citation information
   */
  citationMetadata?: CitationMetadata | undefined;
  /**
   * Token count for this candidate
   */
  tokenCount?: number | undefined;
};

/** @internal */
export const GeminiCandidateFinishReason$inboundSchema: z.ZodMiniType<
  GeminiCandidateFinishReason,
  unknown
> = openEnums.inboundSchema(GeminiCandidateFinishReason);

/** @internal */
export const CitationMetadata$inboundSchema: z.ZodMiniType<
  CitationMetadata,
  unknown
> = z.object({});

export function citationMetadataFromJSON(
  jsonString: string,
): SafeParseResult<CitationMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CitationMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CitationMetadata' from JSON`,
  );
}

/** @internal */
export const GeminiCandidate$inboundSchema: z.ZodMiniType<
  GeminiCandidate,
  unknown
> = z.object({
  content: types.optional(GeminiContent$inboundSchema),
  finishReason: types.optional(GeminiCandidateFinishReason$inboundSchema),
  safetyRatings: types.optional(z.array(GeminiSafetyRating$inboundSchema)),
  citationMetadata: types.optional(
    z.lazy(() => CitationMetadata$inboundSchema),
  ),
  tokenCount: types.optional(types.number()),
});

export function geminiCandidateFromJSON(
  jsonString: string,
): SafeParseResult<GeminiCandidate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeminiCandidate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeminiCandidate' from JSON`,
  );
}
