/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  GeminiGenerateContentRequest,
  GeminiGenerateContentRequest$Outbound,
  GeminiGenerateContentRequest$outboundSchema,
} from "./geminigeneratecontentrequest.js";

export type GenerateContentSecurity = {
  googApiKey: string;
};

export type GenerateContentRequest = {
  /**
   * The model resource name in format models/{model}.
   *
   * @remarks
   * Examples: models/gemini-3-flash, models/gemini-3-pro,
   */
  model: string;
  geminiGenerateContentRequest: GeminiGenerateContentRequest;
};

/** @internal */
export type GenerateContentSecurity$Outbound = {
  goog_api_key: string;
};

/** @internal */
export const GenerateContentSecurity$outboundSchema: z.ZodMiniType<
  GenerateContentSecurity$Outbound,
  GenerateContentSecurity
> = z.pipe(
  z.object({
    googApiKey: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      googApiKey: "goog_api_key",
    });
  }),
);

export function generateContentSecurityToJSON(
  generateContentSecurity: GenerateContentSecurity,
): string {
  return JSON.stringify(
    GenerateContentSecurity$outboundSchema.parse(generateContentSecurity),
  );
}

/** @internal */
export type GenerateContentRequest$Outbound = {
  model: string;
  GeminiGenerateContentRequest: GeminiGenerateContentRequest$Outbound;
};

/** @internal */
export const GenerateContentRequest$outboundSchema: z.ZodMiniType<
  GenerateContentRequest$Outbound,
  GenerateContentRequest
> = z.pipe(
  z.object({
    model: z.string(),
    geminiGenerateContentRequest: GeminiGenerateContentRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      geminiGenerateContentRequest: "GeminiGenerateContentRequest",
    });
  }),
);

export function generateContentRequestToJSON(
  generateContentRequest: GenerateContentRequest,
): string {
  return JSON.stringify(
    GenerateContentRequest$outboundSchema.parse(generateContentRequest),
  );
}
