/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

export const Quality = {
  Standard: "standard",
  Hd: "hd",
} as const;
export type Quality = ClosedEnum<typeof Quality>;

export const ImageGenerationRequestResponseFormat = {
  Url: "url",
  B64Json: "b64_json",
} as const;
export type ImageGenerationRequestResponseFormat = ClosedEnum<
  typeof ImageGenerationRequestResponseFormat
>;

export const Size = {
  TwoHundredAndFiftySixx256: "256x256",
  FiveHundredAndTwelvex512: "512x512",
  OneThousandAndTwentyFourx1024: "1024x1024",
  OneThousandSevenHundredAndNinetyTwox1024: "1792x1024",
  OneThousandAndTwentyFourx1792: "1024x1792",
} as const;
export type Size = ClosedEnum<typeof Size>;

export const Style = {
  Vivid: "vivid",
  Natural: "natural",
} as const;
export type Style = ClosedEnum<typeof Style>;

export type ImageGenerationRequest = {
  /**
   * Image description prompt
   */
  prompt: string;
  /**
   * Model name
   */
  model?: string | undefined;
  /**
   * Number of images to generate
   */
  n?: number | undefined;
  quality?: Quality | undefined;
  responseFormat?: ImageGenerationRequestResponseFormat | undefined;
  size?: Size | undefined;
  style?: Style | undefined;
  user?: string | undefined;
};

/** @internal */
export const Quality$outboundSchema: z.ZodMiniEnum<typeof Quality> = z.enum(
  Quality,
);

/** @internal */
export const ImageGenerationRequestResponseFormat$outboundSchema: z.ZodMiniEnum<
  typeof ImageGenerationRequestResponseFormat
> = z.enum(ImageGenerationRequestResponseFormat);

/** @internal */
export const Size$outboundSchema: z.ZodMiniEnum<typeof Size> = z.enum(Size);

/** @internal */
export const Style$outboundSchema: z.ZodMiniEnum<typeof Style> = z.enum(Style);

/** @internal */
export type ImageGenerationRequest$Outbound = {
  prompt: string;
  model?: string | undefined;
  n: number;
  quality: string;
  response_format: string;
  size: string;
  style: string;
  user?: string | undefined;
};

/** @internal */
export const ImageGenerationRequest$outboundSchema: z.ZodMiniType<
  ImageGenerationRequest$Outbound,
  ImageGenerationRequest
> = z.pipe(
  z.object({
    prompt: z.string(),
    model: z.optional(z.string()),
    n: z._default(z.int(), 1),
    quality: z._default(Quality$outboundSchema, "standard"),
    responseFormat: z._default(
      ImageGenerationRequestResponseFormat$outboundSchema,
      "url",
    ),
    size: z._default(Size$outboundSchema, "1024x1024"),
    style: z._default(Style$outboundSchema, "vivid"),
    user: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      responseFormat: "response_format",
    });
  }),
);

export function imageGenerationRequestToJSON(
  imageGenerationRequest: ImageGenerationRequest,
): string {
  return JSON.stringify(
    ImageGenerationRequest$outboundSchema.parse(imageGenerationRequest),
  );
}
