/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

export type ImageObject = {
  /**
   * Image URL
   */
  url?: string | undefined;
  /**
   * Base64-encoded JSON
   */
  b64Json?: string | undefined;
  /**
   * Revised prompt
   */
  revisedPrompt?: string | undefined;
};

/** @internal */
export const ImageObject$inboundSchema: z.ZodMiniType<ImageObject, unknown> = z
  .pipe(
    z.object({
      url: types.optional(types.string()),
      b64_json: types.optional(types.string()),
      revised_prompt: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "b64_json": "b64Json",
        "revised_prompt": "revisedPrompt",
      });
    }),
  );

export function imageObjectFromJSON(
  jsonString: string,
): SafeParseResult<ImageObject, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImageObject$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImageObject' from JSON`,
  );
}
