/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { blobLikeSchema } from "../types/blobs.js";
import { ClosedEnum } from "../types/enums.js";
import { smartUnion } from "../types/smartUnion.js";

export type ImageEditRequest2 = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type ImageEditRequest1 = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/**
 * The image(s) to edit. Must be a supported image file or an array of images.
 *
 * @remarks
 *
 * For the GPT image models (gpt-image-1, gpt-image-1-mini, and gpt-image-1.5):
 * - Each image should be a png, webp, or jpg file less than 50MB
 * - You can provide up to 16 images
 *
 * For dall-e-2:
 * - You can only provide one image
 * - It should be a square png file less than 4MB
 */
export type Image = ImageEditRequest1 | Array<ImageEditRequest2>;

export type Mask = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export const ImageEditRequestBackground = {
  Transparent: "transparent",
  Opaque: "opaque",
  Auto: "auto",
} as const;
export type ImageEditRequestBackground = ClosedEnum<
  typeof ImageEditRequestBackground
>;

/**
 * Control how much effort the model will exert to match the style and features, especially facial features, of input images.
 *
 * @remarks
 * This parameter is only supported for gpt-image-1. Unsupported for gpt-image-1-mini.
 * Supports high and low. Defaults to low.
 */
export const InputFidelity = {
  High: "high",
  Low: "low",
} as const;
/**
 * Control how much effort the model will exert to match the style and features, especially facial features, of input images.
 *
 * @remarks
 * This parameter is only supported for gpt-image-1. Unsupported for gpt-image-1-mini.
 * Supports high and low. Defaults to low.
 */
export type InputFidelity = ClosedEnum<typeof InputFidelity>;

export const ImageEditRequestModeration = {
  Low: "low",
  Auto: "auto",
} as const;
export type ImageEditRequestModeration = ClosedEnum<
  typeof ImageEditRequestModeration
>;

export const ImageEditRequestOutputFormat = {
  Png: "png",
  Jpeg: "jpeg",
  Webp: "webp",
} as const;
export type ImageEditRequestOutputFormat = ClosedEnum<
  typeof ImageEditRequestOutputFormat
>;

export const ImageEditRequestQuality = {
  Auto: "auto",
  High: "high",
  Medium: "medium",
  Low: "low",
  Hd: "hd",
  Standard: "standard",
} as const;
export type ImageEditRequestQuality = ClosedEnum<
  typeof ImageEditRequestQuality
>;

export const ImageEditRequestResponseFormat = {
  Url: "url",
  B64Json: "b64_json",
} as const;
export type ImageEditRequestResponseFormat = ClosedEnum<
  typeof ImageEditRequestResponseFormat
>;

export const ImageEditRequestSize = {
  OneThousandAndTwentyFourx1024: "1024x1024",
  OneThousandFiveHundredAndThirtySixx1024: "1536x1024",
  OneThousandAndTwentyFourx1536: "1024x1536",
  Auto: "auto",
  TwoHundredAndFiftySixx256: "256x256",
  FiveHundredAndTwelvex512: "512x512",
  OneThousandSevenHundredAndNinetyTwox1024: "1792x1024",
  OneThousandAndTwentyFourx1792: "1024x1792",
} as const;
export type ImageEditRequestSize = ClosedEnum<typeof ImageEditRequestSize>;

export const ImageEditRequestStyle = {
  Vivid: "vivid",
  Natural: "natural",
} as const;
export type ImageEditRequestStyle = ClosedEnum<typeof ImageEditRequestStyle>;

export type ImageEditRequest = {
  /**
   * The image(s) to edit. Must be a supported image file or an array of images.
   *
   * @remarks
   *
   * For the GPT image models (gpt-image-1, gpt-image-1-mini, and gpt-image-1.5):
   * - Each image should be a png, webp, or jpg file less than 50MB
   * - You can provide up to 16 images
   *
   * For dall-e-2:
   * - You can only provide one image
   * - It should be a square png file less than 4MB
   */
  image: ImageEditRequest1 | Array<ImageEditRequest2>;
  /**
   * A text description of the desired image(s).
   *
   * @remarks
   * - Maximum length is 32000 characters for GPT image models
   * - Maximum length is 1000 characters for dall-e-2
   * - Maximum length is 4000 characters for dall-e-3
   */
  prompt: string;
  /**
   * An additional image whose fully transparent areas (e.g. where alpha is zero) indicate where image should be edited.
   *
   * @remarks
   * If there are multiple images provided, the mask will be applied on the first image.
   * Must be a valid PNG file, less than 4MB, and have the same dimensions as image.
   */
  mask?: Mask | Blob | undefined;
  /**
   * Allows to set transparency for the background of the generated image(s).
   *
   * @remarks
   * This parameter is only supported for the GPT image models.
   * Must be one of transparent, opaque or auto (default value).
   * When auto is used, the model will automatically determine the best background for the image.
   *
   * If transparent, the output format needs to support transparency, so it should be set to either png (default value) or webp.
   */
  background?: ImageEditRequestBackground | null | undefined;
  /**
   * Control how much effort the model will exert to match the style and features, especially facial features, of input images.
   *
   * @remarks
   * This parameter is only supported for gpt-image-1. Unsupported for gpt-image-1-mini.
   * Supports high and low. Defaults to low.
   */
  inputFidelity?: InputFidelity | undefined;
  /**
   * The model to use for image generation. One of dall-e-2, dall-e-3, or a GPT image model (gpt-image-1, gpt-image-1-mini, gpt-image-1.5).
   *
   * @remarks
   * Defaults to dall-e-2 unless a parameter specific to the GPT image models is used.
   */
  model?: string | undefined;
  /**
   * Control the content-moderation level for images generated by the GPT image models.
   *
   * @remarks
   * Must be either low for less restrictive filtering or auto (default value).
   */
  moderation?: ImageEditRequestModeration | null | undefined;
  /**
   * The number of images to generate. Must be between 1 and 10.
   *
   * @remarks
   * For dall-e-3, only n=1 is supported.
   */
  n?: number | null | undefined;
  /**
   * The compression level (0-100%) for the generated images.
   *
   * @remarks
   * This parameter is only supported for the GPT image models with the webp or jpeg output formats, and defaults to 100.
   */
  outputCompression?: number | null | undefined;
  /**
   * The format in which the generated images are returned.
   *
   * @remarks
   * This parameter is only supported for the GPT image models.
   * Must be one of png, jpeg, or webp.
   */
  outputFormat?: ImageEditRequestOutputFormat | null | undefined;
  /**
   * The number of partial images to generate.
   *
   * @remarks
   * This parameter is used for streaming responses that return partial images.
   * Value must be between 0 and 3. When set to 0, the response will be a single image sent in one streaming event.
   *
   * Note that the final image may be sent before the full number of partial images are generated if the full image is generated more quickly.
   */
  partialImages?: number | undefined;
  /**
   * The quality of the image that will be generated.
   *
   * @remarks
   * - auto (default value) will automatically select the best quality for the given model.
   * - high, medium and low are supported for the GPT image models.
   * - hd and standard are supported for dall-e-3.
   * - standard is the only option for dall-e-2.
   */
  quality?: ImageEditRequestQuality | null | undefined;
  /**
   * The format in which generated images with dall-e-2 and dall-e-3 are returned.
   *
   * @remarks
   * Must be one of url or b64_json. URLs are only valid for 60 minutes after the image has been generated.
   * This parameter isn't supported for the GPT image models, which always return base64-encoded images.
   */
  responseFormat?: ImageEditRequestResponseFormat | null | undefined;
  /**
   * The size of the generated images.
   *
   * @remarks
   * Must be one of 1024x1024, 1536x1024 (landscape), 1024x1536 (portrait), or auto (default value) for the GPT image models,
   * one of 256x256, 512x512, or 1024x1024 for dall-e-2,
   * and one of 1024x1024, 1792x1024, or 1024x1792 for dall-e-3.
   */
  size?: ImageEditRequestSize | null | undefined;
  /**
   * Generate the image in streaming mode. Defaults to false.
   *
   * @remarks
   * See the Image generation guide for more information.
   * This parameter is only supported for the GPT image models.
   */
  stream?: boolean | undefined;
  /**
   * The style of the generated images. This parameter is only supported for dall-e-3.
   *
   * @remarks
   * Must be one of vivid or natural.
   * Vivid causes the model to lean towards generating hyper-real and dramatic images.
   * Natural causes the model to produce more natural, less hyper-real looking images.
   */
  style?: ImageEditRequestStyle | null | undefined;
  /**
   * A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse.
   */
  user?: string | undefined;
};

/** @internal */
export type ImageEditRequest2$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const ImageEditRequest2$outboundSchema: z.ZodMiniType<
  ImageEditRequest2$Outbound,
  ImageEditRequest2
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
    z.custom<Blob>(x => x instanceof Blob),
    z.custom<ArrayBuffer>(x => x instanceof ArrayBuffer),
    z.custom<Uint8Array>(x => x instanceof Uint8Array),
  ]),
});

export function imageEditRequest2ToJSON(
  imageEditRequest2: ImageEditRequest2,
): string {
  return JSON.stringify(
    ImageEditRequest2$outboundSchema.parse(imageEditRequest2),
  );
}

/** @internal */
export type ImageEditRequest1$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const ImageEditRequest1$outboundSchema: z.ZodMiniType<
  ImageEditRequest1$Outbound,
  ImageEditRequest1
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
    z.custom<Blob>(x => x instanceof Blob),
    z.custom<ArrayBuffer>(x => x instanceof ArrayBuffer),
    z.custom<Uint8Array>(x => x instanceof Uint8Array),
  ]),
});

export function imageEditRequest1ToJSON(
  imageEditRequest1: ImageEditRequest1,
): string {
  return JSON.stringify(
    ImageEditRequest1$outboundSchema.parse(imageEditRequest1),
  );
}

/** @internal */
export type Image$Outbound =
  | ImageEditRequest1$Outbound
  | Array<ImageEditRequest2$Outbound>;

/** @internal */
export const Image$outboundSchema: z.ZodMiniType<Image$Outbound, Image> =
  smartUnion([
    z.lazy(() => ImageEditRequest1$outboundSchema),
    z.array(z.lazy(() => ImageEditRequest2$outboundSchema)),
  ]);

export function imageToJSON(image: Image): string {
  return JSON.stringify(Image$outboundSchema.parse(image));
}

/** @internal */
export type Mask$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const Mask$outboundSchema: z.ZodMiniType<Mask$Outbound, Mask> = z.object(
  {
    fileName: z.string(),
    content: z.union([
      z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
      z.custom<Blob>(x => x instanceof Blob),
      z.custom<ArrayBuffer>(x => x instanceof ArrayBuffer),
      z.custom<Uint8Array>(x => x instanceof Uint8Array),
    ]),
  },
);

export function maskToJSON(mask: Mask): string {
  return JSON.stringify(Mask$outboundSchema.parse(mask));
}

/** @internal */
export const ImageEditRequestBackground$outboundSchema: z.ZodMiniEnum<
  typeof ImageEditRequestBackground
> = z.enum(ImageEditRequestBackground);

/** @internal */
export const InputFidelity$outboundSchema: z.ZodMiniEnum<typeof InputFidelity> =
  z.enum(InputFidelity);

/** @internal */
export const ImageEditRequestModeration$outboundSchema: z.ZodMiniEnum<
  typeof ImageEditRequestModeration
> = z.enum(ImageEditRequestModeration);

/** @internal */
export const ImageEditRequestOutputFormat$outboundSchema: z.ZodMiniEnum<
  typeof ImageEditRequestOutputFormat
> = z.enum(ImageEditRequestOutputFormat);

/** @internal */
export const ImageEditRequestQuality$outboundSchema: z.ZodMiniEnum<
  typeof ImageEditRequestQuality
> = z.enum(ImageEditRequestQuality);

/** @internal */
export const ImageEditRequestResponseFormat$outboundSchema: z.ZodMiniEnum<
  typeof ImageEditRequestResponseFormat
> = z.enum(ImageEditRequestResponseFormat);

/** @internal */
export const ImageEditRequestSize$outboundSchema: z.ZodMiniEnum<
  typeof ImageEditRequestSize
> = z.enum(ImageEditRequestSize);

/** @internal */
export const ImageEditRequestStyle$outboundSchema: z.ZodMiniEnum<
  typeof ImageEditRequestStyle
> = z.enum(ImageEditRequestStyle);

/** @internal */
export type ImageEditRequest$Outbound = {
  image: ImageEditRequest1$Outbound | Array<ImageEditRequest2$Outbound>;
  prompt: string;
  mask?: Mask$Outbound | Blob | undefined;
  background?: string | null | undefined;
  input_fidelity: string;
  model?: string | undefined;
  moderation?: string | null | undefined;
  n?: number | null | undefined;
  output_compression?: number | null | undefined;
  output_format?: string | null | undefined;
  partial_images: number;
  quality?: string | null | undefined;
  response_format?: string | null | undefined;
  size?: string | null | undefined;
  stream: boolean;
  style?: string | null | undefined;
  user?: string | undefined;
};

/** @internal */
export const ImageEditRequest$outboundSchema: z.ZodMiniType<
  ImageEditRequest$Outbound,
  ImageEditRequest
> = z.pipe(
  z.object({
    image: smartUnion([
      z.lazy(() => ImageEditRequest1$outboundSchema),
      z.array(z.lazy(() => ImageEditRequest2$outboundSchema)),
    ]),
    prompt: z.string(),
    mask: z.optional(
      z.union([z.lazy(() => Mask$outboundSchema), blobLikeSchema]),
    ),
    background: z.optional(
      z.nullable(ImageEditRequestBackground$outboundSchema),
    ),
    inputFidelity: z._default(InputFidelity$outboundSchema, "low"),
    model: z.optional(z.string()),
    moderation: z.optional(
      z.nullable(ImageEditRequestModeration$outboundSchema),
    ),
    n: z.optional(z.nullable(z.int())),
    outputCompression: z.optional(z.nullable(z.int())),
    outputFormat: z.optional(
      z.nullable(ImageEditRequestOutputFormat$outboundSchema),
    ),
    partialImages: z._default(z.int(), 0),
    quality: z.optional(z.nullable(ImageEditRequestQuality$outboundSchema)),
    responseFormat: z.optional(
      z.nullable(ImageEditRequestResponseFormat$outboundSchema),
    ),
    size: z.optional(z.nullable(ImageEditRequestSize$outboundSchema)),
    stream: z._default(z.boolean(), false),
    style: z.optional(z.nullable(ImageEditRequestStyle$outboundSchema)),
    user: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      inputFidelity: "input_fidelity",
      outputCompression: "output_compression",
      outputFormat: "output_format",
      partialImages: "partial_images",
      responseFormat: "response_format",
    });
  }),
);

export function imageEditRequestToJSON(
  imageEditRequest: ImageEditRequest,
): string {
  return JSON.stringify(
    ImageEditRequest$outboundSchema.parse(imageEditRequest),
  );
}
