/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ImageEditStreamData,
  ImageEditStreamData$inboundSchema,
} from "./imageeditstreamdata.js";
import { ImageUsage, ImageUsage$inboundSchema } from "./imageusage.js";

/**
 * Object type identifier
 */
export const ImageEditStreamEventObject = {
  ImageEditChunk: "image.edit.chunk",
} as const;
/**
 * Object type identifier
 */
export type ImageEditStreamEventObject = ClosedEnum<
  typeof ImageEditStreamEventObject
>;

export type ImageEditStreamEvent = {
  /**
   * Unique edit request identifier
   */
  id: string;
  /**
   * Unix timestamp
   */
  created: number;
  /**
   * Model used for editing
   */
  model: string;
  /**
   * Object type identifier
   */
  object: ImageEditStreamEventObject;
  /**
   * Array of image data chunks
   */
  data: Array<ImageEditStreamData>;
  /**
   * Usage information for image generation (provider-dependent)
   */
  usage?: ImageUsage | undefined;
};

/** @internal */
export const ImageEditStreamEventObject$inboundSchema: z.ZodMiniEnum<
  typeof ImageEditStreamEventObject
> = z.enum(ImageEditStreamEventObject);

/** @internal */
export const ImageEditStreamEvent$inboundSchema: z.ZodMiniType<
  ImageEditStreamEvent,
  unknown
> = z.object({
  id: types.string(),
  created: types.number(),
  model: types.string(),
  object: ImageEditStreamEventObject$inboundSchema,
  data: z.array(ImageEditStreamData$inboundSchema),
  usage: types.optional(ImageUsage$inboundSchema),
});

export function imageEditStreamEventFromJSON(
  jsonString: string,
): SafeParseResult<ImageEditStreamEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImageEditStreamEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImageEditStreamEvent' from JSON`,
  );
}
