/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

/**
 * Usage information for image generation (provider-dependent)
 */
export type ImageUsage = {
  /**
   * Token count for the prompt
   */
  promptTokens?: number | undefined;
  /**
   * Token count for the generated image (GPT-Image-1/1.5)
   */
  imageTokens?: number | undefined;
  /**
   * Input text token count (Qwen)
   */
  inputTextTokens?: number | undefined;
  /**
   * Output image token count (Qwen)
   */
  outputImageTokens?: number | undefined;
  /**
   * Generated image width (Qwen)
   */
  width?: number | undefined;
  /**
   * Generated image height (Qwen)
   */
  height?: number | undefined;
  /**
   * Number of images generated (Qwen)
   */
  imageCount?: number | undefined;
};

/** @internal */
export const ImageUsage$inboundSchema: z.ZodMiniType<ImageUsage, unknown> = z
  .pipe(
    z.object({
      prompt_tokens: types.optional(types.number()),
      image_tokens: types.optional(types.number()),
      input_text_tokens: types.optional(types.number()),
      output_image_tokens: types.optional(types.number()),
      width: types.optional(types.number()),
      height: types.optional(types.number()),
      image_count: types.optional(types.number()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "prompt_tokens": "promptTokens",
        "image_tokens": "imageTokens",
        "input_text_tokens": "inputTextTokens",
        "output_image_tokens": "outputImageTokens",
        "image_count": "imageCount",
      });
    }),
  );

export function imageUsageFromJSON(
  jsonString: string,
): SafeParseResult<ImageUsage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImageUsage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImageUsage' from JSON`,
  );
}
