/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

export const Background = {
  Transparent: "transparent",
  Opaque: "opaque",
  Auto: "auto",
} as const;
export type Background = ClosedEnum<typeof Background>;

export const Moderation = {
  Low: "low",
  Auto: "auto",
} as const;
export type Moderation = ClosedEnum<typeof Moderation>;

export const OutputFormat = {
  Png: "png",
  Jpeg: "jpeg",
  Webp: "webp",
} as const;
export type OutputFormat = ClosedEnum<typeof OutputFormat>;

export const Quality = {
  Auto: "auto",
  High: "high",
  Medium: "medium",
  Low: "low",
  Hd: "hd",
  Standard: "standard",
} as const;
export type Quality = ClosedEnum<typeof Quality>;

export const ImageGenerationRequestResponseFormat = {
  Url: "url",
  B64Json: "b64_json",
} as const;
export type ImageGenerationRequestResponseFormat = ClosedEnum<
  typeof ImageGenerationRequestResponseFormat
>;

export const Size = {
  OneThousandAndTwentyFourx1024: "1024x1024",
  OneThousandFiveHundredAndThirtySixx1024: "1536x1024",
  OneThousandAndTwentyFourx1536: "1024x1536",
  Auto: "auto",
  TwoHundredAndFiftySixx256: "256x256",
  FiveHundredAndTwelvex512: "512x512",
  OneThousandSevenHundredAndNinetyTwox1024: "1792x1024",
  OneThousandAndTwentyFourx1792: "1024x1792",
} as const;
export type Size = ClosedEnum<typeof Size>;

export const Style = {
  Vivid: "vivid",
  Natural: "natural",
} as const;
export type Style = ClosedEnum<typeof Style>;

export type ImageGenerationRequest = {
  /**
   * A text description of the desired image(s).
   *
   * @remarks
   * - Maximum length is 32000 characters for the GPT image models
   * - Maximum length is 1000 characters for dall-e-2
   * - Maximum length is 4000 characters for dall-e-3
   */
  prompt: string;
  /**
   * Allows to set transparency for the background of the generated image(s).
   *
   * @remarks
   * This parameter is only supported for the GPT image models.
   * Must be one of transparent, opaque or auto (default value).
   * When auto is used, the model will automatically determine the best background for the image.
   *
   * If transparent, the output format needs to support transparency, so it should be set to either png (default value) or webp.
   */
  background?: Background | null | undefined;
  /**
   * The model to use for image generation. One of dall-e-2, dall-e-3, or a GPT image model (gpt-image-1, gpt-image-1-mini, gpt-image-1.5).
   *
   * @remarks
   * Defaults to dall-e-2 unless a parameter specific to the GPT image models is used.
   */
  model?: string | undefined;
  /**
   * Control the content-moderation level for images generated by the GPT image models.
   *
   * @remarks
   * Must be either low for less restrictive filtering or auto (default value).
   */
  moderation?: Moderation | null | undefined;
  /**
   * The number of images to generate. Must be between 1 and 10.
   *
   * @remarks
   * For dall-e-3, only n=1 is supported.
   */
  n?: number | null | undefined;
  /**
   * The compression level (0-100%) for the generated images.
   *
   * @remarks
   * This parameter is only supported for the GPT image models with the webp or jpeg output formats, and defaults to 100.
   */
  outputCompression?: number | null | undefined;
  /**
   * The format in which the generated images are returned.
   *
   * @remarks
   * This parameter is only supported for the GPT image models.
   * Must be one of png, jpeg, or webp.
   */
  outputFormat?: OutputFormat | null | undefined;
  /**
   * The number of partial images to generate.
   *
   * @remarks
   * This parameter is used for streaming responses that return partial images.
   * Value must be between 0 and 3. When set to 0, the response will be a single image sent in one streaming event.
   *
   * Note that the final image may be sent before the full number of partial images are generated if the full image is generated more quickly.
   */
  partialImages?: number | undefined;
  /**
   * The quality of the image that will be generated.
   *
   * @remarks
   * - auto (default value) will automatically select the best quality for the given model.
   * - high, medium and low are supported for the GPT image models.
   * - hd and standard are supported for dall-e-3.
   * - standard is the only option for dall-e-2.
   */
  quality?: Quality | null | undefined;
  /**
   * The format in which generated images with dall-e-2 and dall-e-3 are returned.
   *
   * @remarks
   * Must be one of url or b64_json. URLs are only valid for 60 minutes after the image has been generated.
   * This parameter isn't supported for the GPT image models, which always return base64-encoded images.
   */
  responseFormat?: ImageGenerationRequestResponseFormat | null | undefined;
  /**
   * The size of the generated images.
   *
   * @remarks
   * Must be one of 1024x1024, 1536x1024 (landscape), 1024x1536 (portrait), or auto (default value) for the GPT image models,
   * one of 256x256, 512x512, or 1024x1024 for dall-e-2,
   * and one of 1024x1024, 1792x1024, or 1024x1792 for dall-e-3.
   */
  size?: Size | null | undefined;
  /**
   * Generate the image in streaming mode. Defaults to false.
   *
   * @remarks
   * See the Image generation guide for more information.
   * This parameter is only supported for the GPT image models.
   */
  stream?: boolean | undefined;
  /**
   * The style of the generated images. This parameter is only supported for dall-e-3.
   *
   * @remarks
   * Must be one of vivid or natural.
   * Vivid causes the model to lean towards generating hyper-real and dramatic images.
   * Natural causes the model to produce more natural, less hyper-real looking images.
   */
  style?: Style | null | undefined;
  /**
   * A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse.
   */
  user?: string | undefined;
};

/** @internal */
export const Background$outboundSchema: z.ZodMiniEnum<typeof Background> = z
  .enum(Background);

/** @internal */
export const Moderation$outboundSchema: z.ZodMiniEnum<typeof Moderation> = z
  .enum(Moderation);

/** @internal */
export const OutputFormat$outboundSchema: z.ZodMiniEnum<typeof OutputFormat> = z
  .enum(OutputFormat);

/** @internal */
export const Quality$outboundSchema: z.ZodMiniEnum<typeof Quality> = z.enum(
  Quality,
);

/** @internal */
export const ImageGenerationRequestResponseFormat$outboundSchema: z.ZodMiniEnum<
  typeof ImageGenerationRequestResponseFormat
> = z.enum(ImageGenerationRequestResponseFormat);

/** @internal */
export const Size$outboundSchema: z.ZodMiniEnum<typeof Size> = z.enum(Size);

/** @internal */
export const Style$outboundSchema: z.ZodMiniEnum<typeof Style> = z.enum(Style);

/** @internal */
export type ImageGenerationRequest$Outbound = {
  prompt: string;
  background?: string | null | undefined;
  model?: string | undefined;
  moderation?: string | null | undefined;
  n?: number | null | undefined;
  output_compression?: number | null | undefined;
  output_format?: string | null | undefined;
  partial_images: number;
  quality?: string | null | undefined;
  response_format?: string | null | undefined;
  size?: string | null | undefined;
  stream: boolean;
  style?: string | null | undefined;
  user?: string | undefined;
};

/** @internal */
export const ImageGenerationRequest$outboundSchema: z.ZodMiniType<
  ImageGenerationRequest$Outbound,
  ImageGenerationRequest
> = z.pipe(
  z.object({
    prompt: z.string(),
    background: z.optional(z.nullable(Background$outboundSchema)),
    model: z.optional(z.string()),
    moderation: z.optional(z.nullable(Moderation$outboundSchema)),
    n: z.optional(z.nullable(z.int())),
    outputCompression: z.optional(z.nullable(z.int())),
    outputFormat: z.optional(z.nullable(OutputFormat$outboundSchema)),
    partialImages: z._default(z.int(), 0),
    quality: z.optional(z.nullable(Quality$outboundSchema)),
    responseFormat: z.optional(
      z.nullable(ImageGenerationRequestResponseFormat$outboundSchema),
    ),
    size: z.optional(z.nullable(Size$outboundSchema)),
    stream: z._default(z.boolean(), false),
    style: z.optional(z.nullable(Style$outboundSchema)),
    user: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      outputCompression: "output_compression",
      outputFormat: "output_format",
      partialImages: "partial_images",
      responseFormat: "response_format",
    });
  }),
);

export function imageGenerationRequestToJSON(
  imageGenerationRequest: ImageGenerationRequest,
): string {
  return JSON.stringify(
    ImageGenerationRequest$outboundSchema.parse(imageGenerationRequest),
  );
}
