/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

export const Detail = {
  Auto: "auto",
  Low: "low",
  High: "high",
} as const;
export type Detail = OpenEnum<typeof Detail>;

export type ImageURL = {
  url: string;
  detail?: Detail | undefined;
};

/** @internal */
export const Detail$inboundSchema: z.ZodMiniType<Detail, unknown> = openEnums
  .inboundSchema(Detail);
/** @internal */
export const Detail$outboundSchema: z.ZodMiniType<string, Detail> = openEnums
  .outboundSchema(Detail);

/** @internal */
export const ImageURL$inboundSchema: z.ZodMiniType<ImageURL, unknown> = z
  .object({
    url: types.string(),
    detail: types.optional(Detail$inboundSchema),
  });
/** @internal */
export type ImageURL$Outbound = {
  url: string;
  detail?: string | undefined;
};

/** @internal */
export const ImageURL$outboundSchema: z.ZodMiniType<
  ImageURL$Outbound,
  ImageURL
> = z.object({
  url: z.string(),
  detail: z.optional(Detail$outboundSchema),
});

export function imageURLToJSON(imageURL: ImageURL): string {
  return JSON.stringify(ImageURL$outboundSchema.parse(imageURL));
}
export function imageURLFromJSON(
  jsonString: string,
): SafeParseResult<ImageURL, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImageURL$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImageURL' from JSON`,
  );
}
