/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { ImageObject, ImageObject$inboundSchema } from "./imageobject.js";

export type ImageGenerationResponse = {
  created: number;
  data: Array<ImageObject>;
};

/** @internal */
export const ImageGenerationResponse$inboundSchema: z.ZodMiniType<
  ImageGenerationResponse,
  unknown
> = z.object({
  created: types.number(),
  data: z.array(ImageObject$inboundSchema),
});

export function imageGenerationResponseFromJSON(
  jsonString: string,
): SafeParseResult<ImageGenerationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImageGenerationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImageGenerationResponse' from JSON`,
  );
}
