/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ImageGenerationStreamData,
  ImageGenerationStreamData$inboundSchema,
} from "./imagegenerationstreamdata.js";
import { ImageUsage, ImageUsage$inboundSchema } from "./imageusage.js";

/**
 * Object type identifier
 */
export const ObjectT = {
  ImageGenerationChunk: "image.generation.chunk",
} as const;
/**
 * Object type identifier
 */
export type ObjectT = ClosedEnum<typeof ObjectT>;

export type ImageGenerationStreamEvent = {
  /**
   * Unique generation request identifier
   */
  id: string;
  /**
   * Unix timestamp
   */
  created: number;
  /**
   * Model used for generation
   */
  model: string;
  /**
   * Object type identifier
   */
  object: ObjectT;
  /**
   * Array of image data chunks
   */
  data: Array<ImageGenerationStreamData>;
  /**
   * Usage information for image generation (provider-dependent)
   */
  usage?: ImageUsage | undefined;
};

/** @internal */
export const ObjectT$inboundSchema: z.ZodMiniEnum<typeof ObjectT> = z.enum(
  ObjectT,
);

/** @internal */
export const ImageGenerationStreamEvent$inboundSchema: z.ZodMiniType<
  ImageGenerationStreamEvent,
  unknown
> = z.object({
  id: types.string(),
  created: types.number(),
  model: types.string(),
  object: ObjectT$inboundSchema,
  data: z.array(ImageGenerationStreamData$inboundSchema),
  usage: types.optional(ImageUsage$inboundSchema),
});

export function imageGenerationStreamEventFromJSON(
  jsonString: string,
): SafeParseResult<ImageGenerationStreamEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImageGenerationStreamEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImageGenerationStreamEvent' from JSON`,
  );
}
