/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

export type ImageGenerationStreamData = {
  /**
   * Image index in the batch
   */
  index: number;
  /**
   * Base64-encoded partial or final image
   */
  b64Json?: string | undefined;
  /**
   * Image URL (alternative to b64_json)
   */
  url?: string | undefined;
  /**
   * Generation progress (0.0-1.0)
   */
  progress?: number | undefined;
  /**
   * Whether this is the final image
   */
  isFinal?: boolean | undefined;
  /**
   * Revised prompt (if applicable)
   */
  revisedPrompt?: string | undefined;
};

/** @internal */
export const ImageGenerationStreamData$inboundSchema: z.ZodMiniType<
  ImageGenerationStreamData,
  unknown
> = z.pipe(
  z.object({
    index: types.number(),
    b64_json: types.optional(types.string()),
    url: types.optional(types.string()),
    progress: types.optional(types.number()),
    is_final: types.optional(types.boolean()),
    revised_prompt: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "b64_json": "b64Json",
      "is_final": "isFinal",
      "revised_prompt": "revisedPrompt",
    });
  }),
);

export function imageGenerationStreamDataFromJSON(
  jsonString: string,
): SafeParseResult<ImageGenerationStreamData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImageGenerationStreamData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImageGenerationStreamData' from JSON`,
  );
}
