/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type JsonSchema = {
  name?: string | undefined;
  description?: string | undefined;
  schema?: { [k: string]: any } | undefined;
};

/** @internal */
export type JsonSchema$Outbound = {
  name?: string | undefined;
  description?: string | undefined;
  schema?: { [k: string]: any } | undefined;
};

/** @internal */
export const JsonSchema$outboundSchema: z.ZodMiniType<
  JsonSchema$Outbound,
  JsonSchema
> = z.object({
  name: z.optional(z.string()),
  description: z.optional(z.string()),
  schema: z.optional(z.record(z.string(), z.any())),
});

export function jsonSchemaToJSON(jsonSchema: JsonSchema): string {
  return JSON.stringify(JsonSchema$outboundSchema.parse(jsonSchema));
}
