/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ImageURL,
  ImageURL$inboundSchema,
  ImageURL$Outbound,
  ImageURL$outboundSchema,
} from "./imageurl.js";

export const Type = {
  Text: "text",
  ImageUrl: "image_url",
} as const;
export type Type = OpenEnum<typeof Type>;

export type MessageContent = {
  type: Type;
  text?: string | undefined;
  imageUrl?: ImageURL | undefined;
};

/** @internal */
export const Type$inboundSchema: z.ZodMiniType<Type, unknown> = openEnums
  .inboundSchema(Type);
/** @internal */
export const Type$outboundSchema: z.ZodMiniType<string, Type> = openEnums
  .outboundSchema(Type);

/** @internal */
export const MessageContent$inboundSchema: z.ZodMiniType<
  MessageContent,
  unknown
> = z.pipe(
  z.object({
    type: Type$inboundSchema,
    text: types.optional(types.string()),
    image_url: types.optional(ImageURL$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "image_url": "imageUrl",
    });
  }),
);
/** @internal */
export type MessageContent$Outbound = {
  type: string;
  text?: string | undefined;
  image_url?: ImageURL$Outbound | undefined;
};

/** @internal */
export const MessageContent$outboundSchema: z.ZodMiniType<
  MessageContent$Outbound,
  MessageContent
> = z.pipe(
  z.object({
    type: Type$outboundSchema,
    text: z.optional(z.string()),
    imageUrl: z.optional(ImageURL$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      imageUrl: "image_url",
    });
  }),
);

export function messageContentToJSON(messageContent: MessageContent): string {
  return JSON.stringify(MessageContent$outboundSchema.parse(messageContent));
}
export function messageContentFromJSON(
  jsonString: string,
): SafeParseResult<MessageContent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MessageContent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MessageContent' from JSON`,
  );
}
