/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

export type ModerationCategories = {
  hate?: boolean | undefined;
  hateThreatening?: boolean | undefined;
  harassment?: boolean | undefined;
  harassmentThreatening?: boolean | undefined;
  selfHarm?: boolean | undefined;
  selfHarmIntent?: boolean | undefined;
  selfHarmInstructions?: boolean | undefined;
  sexual?: boolean | undefined;
  sexualMinors?: boolean | undefined;
  violence?: boolean | undefined;
  violenceGraphic?: boolean | undefined;
};

/** @internal */
export const ModerationCategories$inboundSchema: z.ZodMiniType<
  ModerationCategories,
  unknown
> = z.pipe(
  z.object({
    hate: types.optional(types.boolean()),
    "hate/threatening": types.optional(types.boolean()),
    harassment: types.optional(types.boolean()),
    "harassment/threatening": types.optional(types.boolean()),
    "self-harm": types.optional(types.boolean()),
    "self-harm/intent": types.optional(types.boolean()),
    "self-harm/instructions": types.optional(types.boolean()),
    sexual: types.optional(types.boolean()),
    "sexual/minors": types.optional(types.boolean()),
    violence: types.optional(types.boolean()),
    "violence/graphic": types.optional(types.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "hate/threatening": "hateThreatening",
      "harassment/threatening": "harassmentThreatening",
      "self-harm": "selfHarm",
      "self-harm/intent": "selfHarmIntent",
      "self-harm/instructions": "selfHarmInstructions",
      "sexual/minors": "sexualMinors",
      "violence/graphic": "violenceGraphic",
    });
  }),
);

export function moderationCategoriesFromJSON(
  jsonString: string,
): SafeParseResult<ModerationCategories, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModerationCategories$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModerationCategories' from JSON`,
  );
}
