/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

export type ModerationCategoryScores = {
  hate?: number | undefined;
  hateThreatening?: number | undefined;
  harassment?: number | undefined;
  harassmentThreatening?: number | undefined;
  selfHarm?: number | undefined;
  selfHarmIntent?: number | undefined;
  selfHarmInstructions?: number | undefined;
  sexual?: number | undefined;
  sexualMinors?: number | undefined;
  violence?: number | undefined;
  violenceGraphic?: number | undefined;
};

/** @internal */
export const ModerationCategoryScores$inboundSchema: z.ZodMiniType<
  ModerationCategoryScores,
  unknown
> = z.pipe(
  z.object({
    hate: types.optional(types.number()),
    "hate/threatening": types.optional(types.number()),
    harassment: types.optional(types.number()),
    "harassment/threatening": types.optional(types.number()),
    "self-harm": types.optional(types.number()),
    "self-harm/intent": types.optional(types.number()),
    "self-harm/instructions": types.optional(types.number()),
    sexual: types.optional(types.number()),
    "sexual/minors": types.optional(types.number()),
    violence: types.optional(types.number()),
    "violence/graphic": types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "hate/threatening": "hateThreatening",
      "harassment/threatening": "harassmentThreatening",
      "self-harm": "selfHarm",
      "self-harm/intent": "selfHarmIntent",
      "self-harm/instructions": "selfHarmInstructions",
      "sexual/minors": "sexualMinors",
      "violence/graphic": "violenceGraphic",
    });
  }),
);

export function moderationCategoryScoresFromJSON(
  jsonString: string,
): SafeParseResult<ModerationCategoryScores, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModerationCategoryScores$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModerationCategoryScores' from JSON`,
  );
}
