/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { Model, Model$inboundSchema } from "./model.js";

export type ModelListResponse = {
  object: "list";
  data: Array<Model>;
};

/** @internal */
export const ModelListResponse$inboundSchema: z.ZodMiniType<
  ModelListResponse,
  unknown
> = z.object({
  object: types.literal("list"),
  data: z.array(Model$inboundSchema),
});

export function modelListResponseFromJSON(
  jsonString: string,
): SafeParseResult<ModelListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelListResponse' from JSON`,
  );
}
