/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { smartUnion } from "../types/smartUnion.js";

/**
 * Input text to moderate
 */
export type ModerationRequestInput = string | Array<string>;

export type ModerationRequest = {
  /**
   * Input text to moderate
   */
  input: string | Array<string>;
  /**
   * Model name
   */
  model?: string | undefined;
};

/** @internal */
export type ModerationRequestInput$Outbound = string | Array<string>;

/** @internal */
export const ModerationRequestInput$outboundSchema: z.ZodMiniType<
  ModerationRequestInput$Outbound,
  ModerationRequestInput
> = smartUnion([z.string(), z.array(z.string())]);

export function moderationRequestInputToJSON(
  moderationRequestInput: ModerationRequestInput,
): string {
  return JSON.stringify(
    ModerationRequestInput$outboundSchema.parse(moderationRequestInput),
  );
}

/** @internal */
export type ModerationRequest$Outbound = {
  input: string | Array<string>;
  model: string;
};

/** @internal */
export const ModerationRequest$outboundSchema: z.ZodMiniType<
  ModerationRequest$Outbound,
  ModerationRequest
> = z.object({
  input: smartUnion([z.string(), z.array(z.string())]),
  model: z._default(z.string(), "gpt-4o-mini"),
});

export function moderationRequestToJSON(
  moderationRequest: ModerationRequest,
): string {
  return JSON.stringify(
    ModerationRequest$outboundSchema.parse(moderationRequest),
  );
}
