/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ModerationCategories,
  ModerationCategories$inboundSchema,
} from "./moderationcategories.js";
import {
  ModerationCategoryScores,
  ModerationCategoryScores$inboundSchema,
} from "./moderationcategoryscores.js";

export type ModerationResult = {
  flagged: boolean;
  categories: ModerationCategories;
  categoryScores: ModerationCategoryScores;
};

/** @internal */
export const ModerationResult$inboundSchema: z.ZodMiniType<
  ModerationResult,
  unknown
> = z.pipe(
  z.object({
    flagged: types.boolean(),
    categories: ModerationCategories$inboundSchema,
    category_scores: ModerationCategoryScores$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "category_scores": "categoryScores",
    });
  }),
);

export function moderationResultFromJSON(
  jsonString: string,
): SafeParseResult<ModerationResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModerationResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModerationResult' from JSON`,
  );
}
