/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

export type Model = {
  /**
   * Model identifier
   */
  id: string;
  object: "model";
  /**
   * Creation timestamp
   */
  created: number;
  /**
   * Model owner
   */
  ownedBy: string;
};

/** @internal */
export const Model$inboundSchema: z.ZodMiniType<Model, unknown> = z.pipe(
  z.object({
    id: types.string(),
    object: types.literal("model"),
    created: types.number(),
    owned_by: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "owned_by": "ownedBy",
    });
  }),
);

export function modelFromJSON(
  jsonString: string,
): SafeParseResult<Model, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Model$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Model' from JSON`,
  );
}
