/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ModerationResult,
  ModerationResult$inboundSchema,
} from "./moderationresult.js";

export type ModerationResponse = {
  id: string;
  model: string;
  results: Array<ModerationResult>;
};

/** @internal */
export const ModerationResponse$inboundSchema: z.ZodMiniType<
  ModerationResponse,
  unknown
> = z.object({
  id: types.string(),
  model: types.string(),
  results: z.array(ModerationResult$inboundSchema),
});

export function moderationResponseFromJSON(
  jsonString: string,
): SafeParseResult<ModerationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModerationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModerationResponse' from JSON`,
  );
}
