/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

/**
 * Details about input tokens
 */
export type InputTokensDetails = {
  /**
   * Number of cached tokens
   */
  cachedTokens?: number | undefined;
};

/**
 * Details about output tokens
 */
export type OutputTokensDetails = {
  /**
   * Number of reasoning tokens
   */
  reasoningTokens?: number | undefined;
};

export type ResponseUsage = {
  /**
   * Number of tokens in the input
   */
  inputTokens: number;
  /**
   * Details about input tokens
   */
  inputTokensDetails?: InputTokensDetails | undefined;
  /**
   * Number of tokens in the output
   */
  outputTokens: number;
  /**
   * Details about output tokens
   */
  outputTokensDetails?: OutputTokensDetails | undefined;
  /**
   * Total number of tokens (input + output)
   */
  totalTokens: number;
};

/** @internal */
export const InputTokensDetails$inboundSchema: z.ZodMiniType<
  InputTokensDetails,
  unknown
> = z.pipe(
  z.object({
    cached_tokens: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "cached_tokens": "cachedTokens",
    });
  }),
);

export function inputTokensDetailsFromJSON(
  jsonString: string,
): SafeParseResult<InputTokensDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InputTokensDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InputTokensDetails' from JSON`,
  );
}

/** @internal */
export const OutputTokensDetails$inboundSchema: z.ZodMiniType<
  OutputTokensDetails,
  unknown
> = z.pipe(
  z.object({
    reasoning_tokens: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "reasoning_tokens": "reasoningTokens",
    });
  }),
);

export function outputTokensDetailsFromJSON(
  jsonString: string,
): SafeParseResult<OutputTokensDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutputTokensDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutputTokensDetails' from JSON`,
  );
}

/** @internal */
export const ResponseUsage$inboundSchema: z.ZodMiniType<
  ResponseUsage,
  unknown
> = z.pipe(
  z.object({
    input_tokens: types.number(),
    input_tokens_details: types.optional(
      z.lazy(() => InputTokensDetails$inboundSchema),
    ),
    output_tokens: types.number(),
    output_tokens_details: types.optional(
      z.lazy(() => OutputTokensDetails$inboundSchema),
    ),
    total_tokens: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "input_tokens": "inputTokens",
      "input_tokens_details": "inputTokensDetails",
      "output_tokens": "outputTokens",
      "output_tokens_details": "outputTokensDetails",
      "total_tokens": "totalTokens",
    });
  }),
);

export function responseUsageFromJSON(
  jsonString: string,
): SafeParseResult<ResponseUsage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseUsage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseUsage' from JSON`,
  );
}
