/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";

/**
 * Tool type, currently only supports function
 */
export const ResponseToolType = {
  Function: "function",
} as const;
/**
 * Tool type, currently only supports function
 */
export type ResponseToolType = ClosedEnum<typeof ResponseToolType>;

export const ResponseToolSchemasType = {
  Object: "object",
} as const;
export type ResponseToolSchemasType = ClosedEnum<
  typeof ResponseToolSchemasType
>;

/**
 * Function parameter definition in JSON Schema format
 */
export type ParametersT = {
  type?: ResponseToolSchemasType | undefined;
  properties?: { [k: string]: any } | undefined;
  required?: Array<string> | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

/**
 * Tool definition (flat format). Dedicated for /v1/responses endpoint.
 *
 * @remarks
 * Format: { "type": "function", "name": "...", "description": "...", "parameters": {...} }
 */
export type ResponseTool = {
  /**
   * Tool type, currently only supports function
   */
  type: ResponseToolType;
  /**
   * Function name
   */
  name: string;
  /**
   * Function description, helps model understand when to call this function
   */
  description?: string | undefined;
  /**
   * Function parameter definition in JSON Schema format
   */
  parameters?: ParametersT | undefined;
};

/** @internal */
export const ResponseToolType$inboundSchema: z.ZodMiniEnum<
  typeof ResponseToolType
> = z.enum(ResponseToolType);
/** @internal */
export const ResponseToolType$outboundSchema: z.ZodMiniEnum<
  typeof ResponseToolType
> = ResponseToolType$inboundSchema;

/** @internal */
export const ResponseToolSchemasType$inboundSchema: z.ZodMiniEnum<
  typeof ResponseToolSchemasType
> = z.enum(ResponseToolSchemasType);
/** @internal */
export const ResponseToolSchemasType$outboundSchema: z.ZodMiniEnum<
  typeof ResponseToolSchemasType
> = ResponseToolSchemasType$inboundSchema;

/** @internal */
export const ParametersT$inboundSchema: z.ZodMiniType<ParametersT, unknown> =
  collectExtraKeys$(
    z.catchall(
      z.object({
        type: types.optional(ResponseToolSchemasType$inboundSchema),
        properties: types.optional(z.record(z.string(), z.any())),
        required: types.optional(z.array(types.string())),
      }),
      z.any(),
    ),
    "additionalProperties",
    true,
  );
/** @internal */
export type ParametersT$Outbound = {
  type?: string | undefined;
  properties?: { [k: string]: any } | undefined;
  required?: Array<string> | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const ParametersT$outboundSchema: z.ZodMiniType<
  ParametersT$Outbound,
  ParametersT
> = z.pipe(
  z.object({
    type: z.optional(ResponseToolSchemasType$outboundSchema),
    properties: z.optional(z.record(z.string(), z.any())),
    required: z.optional(z.array(z.string())),
    additionalProperties: z.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return {
      ...v.additionalProperties,
      ...remap$(v, {
        additionalProperties: null,
      }),
    };
  }),
);

export function parametersToJSON(parametersT: ParametersT): string {
  return JSON.stringify(ParametersT$outboundSchema.parse(parametersT));
}
export function parametersFromJSON(
  jsonString: string,
): SafeParseResult<ParametersT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ParametersT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ParametersT' from JSON`,
  );
}

/** @internal */
export const ResponseTool$inboundSchema: z.ZodMiniType<ResponseTool, unknown> =
  z.object({
    type: ResponseToolType$inboundSchema,
    name: types.string(),
    description: types.optional(types.string()),
    parameters: types.optional(z.lazy(() => ParametersT$inboundSchema)),
  });
/** @internal */
export type ResponseTool$Outbound = {
  type: string;
  name: string;
  description?: string | undefined;
  parameters?: ParametersT$Outbound | undefined;
};

/** @internal */
export const ResponseTool$outboundSchema: z.ZodMiniType<
  ResponseTool$Outbound,
  ResponseTool
> = z.object({
  type: ResponseToolType$outboundSchema,
  name: z.string(),
  description: z.optional(z.string()),
  parameters: z.optional(z.lazy(() => ParametersT$outboundSchema)),
});

export function responseToolToJSON(responseTool: ResponseTool): string {
  return JSON.stringify(ResponseTool$outboundSchema.parse(responseTool));
}
export function responseToolFromJSON(
  jsonString: string,
): SafeParseResult<ResponseTool, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseTool$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseTool' from JSON`,
  );
}
