/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import {
  ResponseObject,
  ResponseObject$inboundSchema,
} from "./responseobject.js";
import {
  ResponseOutputItem,
  ResponseOutputItem$inboundSchema,
} from "./responseoutputitem.js";

/**
 * Delta updates object format
 */
export type ResponseStreamEvent2 = {
  /**
   * Text delta content
   */
  text?: string | undefined;
  /**
   * Role delta
   */
  role?: string | undefined;
  /**
   * Content delta
   */
  content?: string | undefined;
};

/**
 * Delta updates (present in response.text.delta events), can be a string or object
 */
export type Delta = string | ResponseStreamEvent2;

/**
 * Response stream event (data payload for SSE stream)
 */
export type ResponseStreamEvent = {
  /**
   * Event type (e.g., response.created, response.output_item.added, response.text.delta, response.completed)
   */
  type: string;
  /**
   * Sequence number of the event
   */
  sequenceNumber?: number | undefined;
  response?: ResponseObject | undefined;
  outputItem?: ResponseOutputItem | undefined;
  /**
   * Index of the output item
   */
  outputItemIndex?: number | undefined;
  /**
   * Index of the content block
   */
  contentIndex?: number | undefined;
  /**
   * Delta updates (present in response.text.delta events), can be a string or object
   */
  delta?: string | ResponseStreamEvent2 | undefined;
};

/** @internal */
export const ResponseStreamEvent2$inboundSchema: z.ZodMiniType<
  ResponseStreamEvent2,
  unknown
> = z.object({
  text: types.optional(types.string()),
  role: types.optional(types.string()),
  content: types.optional(types.string()),
});

export function responseStreamEvent2FromJSON(
  jsonString: string,
): SafeParseResult<ResponseStreamEvent2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseStreamEvent2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseStreamEvent2' from JSON`,
  );
}

/** @internal */
export const Delta$inboundSchema: z.ZodMiniType<Delta, unknown> = smartUnion([
  types.string(),
  z.lazy(() => ResponseStreamEvent2$inboundSchema),
]);

export function deltaFromJSON(
  jsonString: string,
): SafeParseResult<Delta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Delta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Delta' from JSON`,
  );
}

/** @internal */
export const ResponseStreamEvent$inboundSchema: z.ZodMiniType<
  ResponseStreamEvent,
  unknown
> = z.pipe(
  z.object({
    type: types.string(),
    sequence_number: types.optional(types.number()),
    response: types.optional(ResponseObject$inboundSchema),
    output_item: types.optional(ResponseOutputItem$inboundSchema),
    output_item_index: types.optional(types.number()),
    content_index: types.optional(types.number()),
    delta: types.optional(smartUnion([
      types.string(),
      z.lazy(() => ResponseStreamEvent2$inboundSchema),
    ])),
  }),
  z.transform((v) => {
    return remap$(v, {
      "sequence_number": "sequenceNumber",
      "output_item": "outputItem",
      "output_item_index": "outputItemIndex",
      "content_index": "contentIndex",
    });
  }),
);

export function responseStreamEventFromJSON(
  jsonString: string,
): SafeParseResult<ResponseStreamEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseStreamEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseStreamEvent' from JSON`,
  );
}
