/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import {
  JsonSchema,
  JsonSchema$Outbound,
  JsonSchema$outboundSchema,
} from "./jsonschema.js";

export const ResponseFormatType = {
  Text: "text",
  JsonObject: "json_object",
  JsonSchema: "json_schema",
} as const;
export type ResponseFormatType = ClosedEnum<typeof ResponseFormatType>;

export type ResponseFormat = {
  type?: ResponseFormatType | undefined;
  jsonSchema?: JsonSchema | undefined;
};

/** @internal */
export const ResponseFormatType$outboundSchema: z.ZodMiniEnum<
  typeof ResponseFormatType
> = z.enum(ResponseFormatType);

/** @internal */
export type ResponseFormat$Outbound = {
  type?: string | undefined;
  json_schema?: JsonSchema$Outbound | undefined;
};

/** @internal */
export const ResponseFormat$outboundSchema: z.ZodMiniType<
  ResponseFormat$Outbound,
  ResponseFormat
> = z.pipe(
  z.object({
    type: z.optional(ResponseFormatType$outboundSchema),
    jsonSchema: z.optional(JsonSchema$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      jsonSchema: "json_schema",
    });
  }),
);

export function responseFormatToJSON(responseFormat: ResponseFormat): string {
  return JSON.stringify(ResponseFormat$outboundSchema.parse(responseFormat));
}
