/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type RetrieveModelRequest = {
  /**
   * Model name
   */
  model: string;
};

/** @internal */
export type RetrieveModelRequest$Outbound = {
  model: string;
};

/** @internal */
export const RetrieveModelRequest$outboundSchema: z.ZodMiniType<
  RetrieveModelRequest$Outbound,
  RetrieveModelRequest
> = z.object({
  model: z.string(),
});

export function retrieveModelRequestToJSON(
  retrieveModelRequest: RetrieveModelRequest,
): string {
  return JSON.stringify(
    RetrieveModelRequest$outboundSchema.parse(retrieveModelRequest),
  );
}
