/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

/**
 * Search engine name (optional, defaults to exa)
 *
 * @remarks
 * - exa: AI-native search engine, suitable for semantic search
 * - tavily: AI search API, supports deep search and summary answers
 * - google: Google custom search, most comprehensive index
 */
export const Engine = {
  Exa: "exa",
  Tavily: "tavily",
  Google: "google",
} as const;
/**
 * Search engine name (optional, defaults to exa)
 *
 * @remarks
 * - exa: AI-native search engine, suitable for semantic search
 * - tavily: AI search API, supports deep search and summary answers
 * - google: Google custom search, most comprehensive index
 */
export type Engine = ClosedEnum<typeof Engine>;

/**
 * Engine-specific parameters. Different engines support different parameters:
 *
 * @remarks
 *
 * **Exa engine parameters:**
 * - query (string, required): Search query
 * - num (integer): Number of results to return, default 10
 * - contents.text (boolean): Whether to return full text content
 *
 * **Tavily engine parameters:**
 * - query (string, required): Search query
 * - max_results (integer): Maximum number of results, default 10
 * - search_depth (string): Search depth, "basic" or "advanced", default "basic"
 * - include_answer (boolean): Whether to include AI-generated summary answer, default true
 *
 * **Google engine parameters:**
 * - query (string, required): Search query
 * - num (integer): Number of results (1-10), default 10
 * - start (integer): Starting position (pagination), default 1
 * - safe (string): Safe search, "active" or "off", default "active"
 */
export type Extra = {
  /**
   * Search query (required for all engines)
   */
  query: string;
  additionalProperties?: { [k: string]: any } | undefined;
};

export type SearchRequest = {
  /**
   * Search engine name (optional, defaults to exa)
   *
   * @remarks
   * - exa: AI-native search engine, suitable for semantic search
   * - tavily: AI search API, supports deep search and summary answers
   * - google: Google custom search, most comprehensive index
   */
  engine?: Engine | undefined;
  /**
   * Engine-specific parameters. Different engines support different parameters:
   *
   * @remarks
   *
   * **Exa engine parameters:**
   * - query (string, required): Search query
   * - num (integer): Number of results to return, default 10
   * - contents.text (boolean): Whether to return full text content
   *
   * **Tavily engine parameters:**
   * - query (string, required): Search query
   * - max_results (integer): Maximum number of results, default 10
   * - search_depth (string): Search depth, "basic" or "advanced", default "basic"
   * - include_answer (boolean): Whether to include AI-generated summary answer, default true
   *
   * **Google engine parameters:**
   * - query (string, required): Search query
   * - num (integer): Number of results (1-10), default 10
   * - start (integer): Starting position (pagination), default 1
   * - safe (string): Safe search, "active" or "off", default "active"
   */
  extra: Extra;
};

/** @internal */
export const Engine$outboundSchema: z.ZodMiniEnum<typeof Engine> = z.enum(
  Engine,
);

/** @internal */
export type Extra$Outbound = {
  query: string;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const Extra$outboundSchema: z.ZodMiniType<Extra$Outbound, Extra> = z
  .pipe(
    z.object({
      query: z.string(),
      additionalProperties: z.optional(z.record(z.string(), z.any())),
    }),
    z.transform((v) => {
      return {
        ...v.additionalProperties,
        ...remap$(v, {
          additionalProperties: null,
        }),
      };
    }),
  );

export function extraToJSON(extra: Extra): string {
  return JSON.stringify(Extra$outboundSchema.parse(extra));
}

/** @internal */
export type SearchRequest$Outbound = {
  engine: string;
  extra: Extra$Outbound;
};

/** @internal */
export const SearchRequest$outboundSchema: z.ZodMiniType<
  SearchRequest$Outbound,
  SearchRequest
> = z.object({
  engine: z._default(Engine$outboundSchema, "exa"),
  extra: z.lazy(() => Extra$outboundSchema),
});

export function searchRequestToJSON(searchRequest: SearchRequest): string {
  return JSON.stringify(SearchRequest$outboundSchema.parse(searchRequest));
}
