/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";

/**
 * Search engine used
 */
export const SearchResponseEngine = {
  Exa: "exa",
  Tavily: "tavily",
  Google: "google",
} as const;
/**
 * Search engine used
 */
export type SearchResponseEngine = OpenEnum<typeof SearchResponseEngine>;

export type SearchResponse = {
  /**
   * Search engine used
   */
  engine: SearchResponseEngine;
  /**
   * Search results, format depends on the engine used.
   *
   * @remarks
   *
   * **Exa response format:**
   * - requestId: Request ID
   * - results: Results array (includes id, title, url, text, publishedDate, author, etc.)
   * - searchTime: Search duration
   *
   * **Tavily response format:**
   * - query: Original query
   * - answer: AI-generated summary answer (if enabled)
   * - results: Results array (includes title, url, content, score, etc.)
   * - response_time: Response time
   * - request_id: Request ID
   *
   * **Google response format:**
   * - items: Results array (includes title, link, snippet, etc.)
   * - searchInformation: Search metadata (totalResults, searchTime)
   */
  result: { [k: string]: any };
};

/** @internal */
export const SearchResponseEngine$inboundSchema: z.ZodMiniType<
  SearchResponseEngine,
  unknown
> = openEnums.inboundSchema(SearchResponseEngine);

/** @internal */
export const SearchResponse$inboundSchema: z.ZodMiniType<
  SearchResponse,
  unknown
> = z.object({
  engine: SearchResponseEngine$inboundSchema,
  result: z.record(z.string(), z.any()),
});

export function searchResponseFromJSON(
  jsonString: string,
): SafeParseResult<SearchResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchResponse' from JSON`,
  );
}
