/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type StreamOptions = {
  /**
   * Whether to include usage statistics
   */
  includeUsage?: boolean | undefined;
};

/** @internal */
export type StreamOptions$Outbound = {
  include_usage?: boolean | undefined;
};

/** @internal */
export const StreamOptions$outboundSchema: z.ZodMiniType<
  StreamOptions$Outbound,
  StreamOptions
> = z.pipe(
  z.object({
    includeUsage: z.optional(z.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      includeUsage: "include_usage",
    });
  }),
);

export function streamOptionsToJSON(streamOptions: StreamOptions): string {
  return JSON.stringify(StreamOptions$outboundSchema.parse(streamOptions));
}
