/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  GeminiGenerateContentRequest,
  GeminiGenerateContentRequest$Outbound,
  GeminiGenerateContentRequest$outboundSchema,
} from "./geminigeneratecontentrequest.js";
import {
  GeminiGenerateContentResponse,
  GeminiGenerateContentResponse$inboundSchema,
} from "./geminigeneratecontentresponse.js";

export type StreamGenerateContentSecurity = {
  googApiKey: string;
};

/**
 * Data format for the response (use 'sse' for server-sent events)
 */
export const Alt = {
  Sse: "sse",
} as const;
/**
 * Data format for the response (use 'sse' for server-sent events)
 */
export type Alt = ClosedEnum<typeof Alt>;

export type StreamGenerateContentRequest = {
  /**
   * The model resource name in format models/{model}.
   *
   * @remarks
   * Examples: models/gemini-3-flash, models/gemini-3-pro
   */
  model: string;
  /**
   * Data format for the response (use 'sse' for server-sent events)
   */
  alt?: Alt | undefined;
  geminiGenerateContentRequest: GeminiGenerateContentRequest;
};

/**
 * Successful streaming response (Server-Sent Events)
 */
export type StreamGenerateContentResponseBody = {
  /**
   * Response from generateContent or streamGenerateContent
   */
  data: GeminiGenerateContentResponse;
  id?: string | undefined;
  event?: string | undefined;
  retry?: number | undefined;
};

/** @internal */
export type StreamGenerateContentSecurity$Outbound = {
  goog_api_key: string;
};

/** @internal */
export const StreamGenerateContentSecurity$outboundSchema: z.ZodMiniType<
  StreamGenerateContentSecurity$Outbound,
  StreamGenerateContentSecurity
> = z.pipe(
  z.object({
    googApiKey: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      googApiKey: "goog_api_key",
    });
  }),
);

export function streamGenerateContentSecurityToJSON(
  streamGenerateContentSecurity: StreamGenerateContentSecurity,
): string {
  return JSON.stringify(
    StreamGenerateContentSecurity$outboundSchema.parse(
      streamGenerateContentSecurity,
    ),
  );
}

/** @internal */
export const Alt$outboundSchema: z.ZodMiniEnum<typeof Alt> = z.enum(Alt);

/** @internal */
export type StreamGenerateContentRequest$Outbound = {
  model: string;
  alt: string;
  GeminiGenerateContentRequest: GeminiGenerateContentRequest$Outbound;
};

/** @internal */
export const StreamGenerateContentRequest$outboundSchema: z.ZodMiniType<
  StreamGenerateContentRequest$Outbound,
  StreamGenerateContentRequest
> = z.pipe(
  z.object({
    model: z.string(),
    alt: z._default(Alt$outboundSchema, "sse"),
    geminiGenerateContentRequest: GeminiGenerateContentRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      geminiGenerateContentRequest: "GeminiGenerateContentRequest",
    });
  }),
);

export function streamGenerateContentRequestToJSON(
  streamGenerateContentRequest: StreamGenerateContentRequest,
): string {
  return JSON.stringify(
    StreamGenerateContentRequest$outboundSchema.parse(
      streamGenerateContentRequest,
    ),
  );
}

/** @internal */
export const StreamGenerateContentResponseBody$inboundSchema: z.ZodMiniType<
  StreamGenerateContentResponseBody,
  unknown
> = z.object({
  data: z.pipe(
    z.pipe(
      z.string(),
      z.transform((v, ctx) => {
        try {
          return JSON.parse(v);
        } catch (err) {
          ctx.issues.push({
            input: v,
            code: "custom",
            message: `malformed json: ${err}`,
          });
          return z.NEVER;
        }
      }),
    ),
    GeminiGenerateContentResponse$inboundSchema,
  ),
  id: types.optional(types.string()),
  event: types.optional(types.string()),
  retry: types.optional(types.number()),
});

export function streamGenerateContentResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<StreamGenerateContentResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StreamGenerateContentResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StreamGenerateContentResponseBody' from JSON`,
  );
}
