/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * Tool type, currently only supports function
 */
export const ToolType = {
  Function: "function",
} as const;
/**
 * Tool type, currently only supports function
 */
export type ToolType = ClosedEnum<typeof ToolType>;

export type FunctionT = {
  /**
   * Function name
   */
  name: string;
  /**
   * Function description, helps model understand when to call this function
   */
  description?: string | undefined;
  /**
   * Function parameter definition in JSON Schema format
   */
  parameters?: { [k: string]: any } | undefined;
};

/**
 * Tool definition (nested format). Used for /v1/chat/completions and other endpoints.
 *
 * @remarks
 * Format: { "type": "function", "function": { "name": "...", "description": "...", "parameters": {...} } }
 */
export type Tool = {
  /**
   * Tool type, currently only supports function
   */
  type: ToolType;
  function: FunctionT;
};

/** @internal */
export const ToolType$outboundSchema: z.ZodMiniEnum<typeof ToolType> = z.enum(
  ToolType,
);

/** @internal */
export type FunctionT$Outbound = {
  name: string;
  description?: string | undefined;
  parameters?: { [k: string]: any } | undefined;
};

/** @internal */
export const FunctionT$outboundSchema: z.ZodMiniType<
  FunctionT$Outbound,
  FunctionT
> = z.object({
  name: z.string(),
  description: z.optional(z.string()),
  parameters: z.optional(z.record(z.string(), z.any())),
});

export function functionToJSON(functionT: FunctionT): string {
  return JSON.stringify(FunctionT$outboundSchema.parse(functionT));
}

/** @internal */
export type Tool$Outbound = {
  type: string;
  function: FunctionT$Outbound;
};

/** @internal */
export const Tool$outboundSchema: z.ZodMiniType<Tool$Outbound, Tool> = z.object(
  {
    type: ToolType$outboundSchema,
    function: z.lazy(() => FunctionT$outboundSchema),
  },
);

export function toolToJSON(tool: Tool): string {
  return JSON.stringify(Tool$outboundSchema.parse(tool));
}
