/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  FunctionCall,
  FunctionCall$inboundSchema,
  FunctionCall$Outbound,
  FunctionCall$outboundSchema,
} from "./functioncall.js";

export type ToolCall = {
  id: string;
  type: string;
  function: FunctionCall;
};

/** @internal */
export const ToolCall$inboundSchema: z.ZodMiniType<ToolCall, unknown> = z
  .object({
    id: types.string(),
    type: types.string(),
    function: FunctionCall$inboundSchema,
  });
/** @internal */
export type ToolCall$Outbound = {
  id: string;
  type: string;
  function: FunctionCall$Outbound;
};

/** @internal */
export const ToolCall$outboundSchema: z.ZodMiniType<
  ToolCall$Outbound,
  ToolCall
> = z.object({
  id: z.string(),
  type: z.string(),
  function: FunctionCall$outboundSchema,
});

export function toolCallToJSON(toolCall: ToolCall): string {
  return JSON.stringify(ToolCall$outboundSchema.parse(toolCall));
}
export function toolCallFromJSON(
  jsonString: string,
): SafeParseResult<ToolCall, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ToolCall$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ToolCall' from JSON`,
  );
}
