/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ToolChoiceFunction = {
  /**
   * Function name to call
   */
  name: string;
};

/**
 * Specify specific tool selection
 */
export type ToolChoice = {
  /**
   * Tool type
   */
  type: "function";
  function: ToolChoiceFunction;
};

/** @internal */
export type ToolChoiceFunction$Outbound = {
  name: string;
};

/** @internal */
export const ToolChoiceFunction$outboundSchema: z.ZodMiniType<
  ToolChoiceFunction$Outbound,
  ToolChoiceFunction
> = z.object({
  name: z.string(),
});

export function toolChoiceFunctionToJSON(
  toolChoiceFunction: ToolChoiceFunction,
): string {
  return JSON.stringify(
    ToolChoiceFunction$outboundSchema.parse(toolChoiceFunction),
  );
}

/** @internal */
export type ToolChoice$Outbound = {
  type: "function";
  function: ToolChoiceFunction$Outbound;
};

/** @internal */
export const ToolChoice$outboundSchema: z.ZodMiniType<
  ToolChoice$Outbound,
  ToolChoice
> = z.object({
  type: z.literal("function"),
  function: z.lazy(() => ToolChoiceFunction$outboundSchema),
});

export function toolChoiceToJSON(toolChoice: ToolChoice): string {
  return JSON.stringify(ToolChoice$outboundSchema.parse(toolChoice));
}
